// Code generated by opnsense-cli/generate; DO NOT EDIT.

package diagnostics

import "github.com/jontk/opnsense-cli/opnsense"

// Settings represents a settings model item.
type Settings struct {
	Hostname string `json:"hostname"` // Required.
	Server   string `json:"server,omitempty"`
}

// Template represents a template model item.
type Template struct {
	Name    string           `json:"name"`    // Required.
	Or      opnsense.OPNBool `json:"or"`      // Required. Default: 0.
	Filters string           `json:"filters"` // Required.
}

type templateGetItemResponse struct {
	Template Template `json:"template"`
}
