// Code generated by opnsense-cli/generate; DO NOT EDIT.

package stunnel

import "github.com/jontk/opnsense-cli/opnsense"

// General represents a general model item.
type General struct {
	Enabled           opnsense.OPNBool `json:"enabled"`
	Chroot            opnsense.OPNBool `json:"chroot"`
	EnableIdentServer opnsense.OPNBool `json:"enable_ident_server"`
}

// Service represents a service model item.
type Service struct {
	Enabled        opnsense.OPNBool `json:"enabled"`
	AcceptPort     opnsense.OPNInt  `json:"accept_port"`
	AcceptAddress  string           `json:"accept_address"`
	ConnectAddress string           `json:"connect_address"`
	ConnectPort    opnsense.OPNInt  `json:"connect_port"`
	Protocol       string           `json:"protocol,omitempty"` // Valid values: imap, ldap, nntp, pop3, smtp
	Cacert         string           `json:"cacert,omitempty"`
	EnableCRL      opnsense.OPNBool `json:"enableCRL"`
	Clientmode     opnsense.OPNBool `json:"clientmode"`
	Ciphers        string           `json:"ciphers"`
	Servercert     string           `json:"servercert"`
	Description    string           `json:"description,omitempty"`
}

type serviceGetItemResponse struct {
	Service Service `json:"service"`
}
