// Code generated by opnsense-cli/generate; DO NOT EDIT.

package puppetagent

// General represents a general model item.
type General struct {
	Enabled           string `json:"Enabled"`
	FQDN              string `json:"FQDN"`
	Environment       string `json:"Environment"`
	RunInterval       string `json:"RunInterval"`
	RunTimeout        string `json:"RunTimeout"`
	UseCacheOnFailure string `json:"UseCacheOnFailure"`
}
