// Code generated by opnsense-cli/generate; DO NOT EDIT.

package ids

// Rule represents a rule model item.
type Rule struct {
	Sid     string `json:"sid"`
	Enabled string `json:"enabled"`
	Action  string `json:"action"` // Valid values: alert, drop
	Msg     string `json:"msg,omitempty"`
	Source  string `json:"source,omitempty"`
}

// Policy represents a policy model item.
type Policy struct {
	Enabled     string `json:"enabled"`
	Prio        string `json:"prio"`
	Action      string `json:"action,omitempty"` // Valid values: disable, alert, drop
	Rulesets    string `json:"rulesets,omitempty"`
	Content     string `json:"content,omitempty"`
	NewAction   string `json:"new_action"` // Valid values: default, alert, drop, disable
	Description string `json:"description,omitempty"`
}

// File represents a file model item.
type File struct {
	Filename string `json:"filename"`
	Enabled  string `json:"enabled"`
}

// Tag represents a tag model item.
type Tag struct {
	Property string `json:"property"`
	Value    string `json:"value,omitempty"`
}

// Detect represents a detect model item.
type Detect struct {
	Profile        string `json:"Profile,omitempty"` // Valid values: low, medium, high, custom
	ToclientGroups string `json:"toclient_groups,omitempty"`
	ToserverGroups string `json:"toserver_groups,omitempty"`
}

type policyGetItemResponse struct {
	Policy Policy `json:"policy"`
}

type ruleGetItemResponse struct {
	Rule Rule `json:"rule"`
}
