// Code generated by opnsense-cli/generate; DO NOT EDIT.

// Package zerotier provides a client for the OPNsense zerotier API.
package zerotier

import (
	"context"

	"github.com/jontk/opnsense-cli/opnsense"
)

// Client wraps the base OPNsense client for zerotier API calls.
type Client struct {
	client *opnsense.Client
}

// NewClient creates a new zerotier API client.
func NewClient(c *opnsense.Client) *Client {
	return &Client{client: c}
}

// NetworkAdd calls POST /api/zerotier/network/add
func (c *Client) NetworkAdd(ctx context.Context, body any) (any, error) {
	path := "/api/zerotier/network/add"
	var resp any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// NetworkDel calls POST /api/zerotier/network/del
// Parameters:
//   - uuid (optional, default: null)
func (c *Client) NetworkDel(ctx context.Context, body any, opts ...string) (any, error) {
	path := "/api/zerotier/network/del"
	for _, o := range opts {
		path += "/" + o
	}
	var resp any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// NetworkGet calls GET /api/zerotier/network/get
// Parameters:
//   - uuid (optional, default: null)
func (c *Client) NetworkGet(ctx context.Context, opts ...string) (any, error) {
	path := "/api/zerotier/network/get"
	for _, o := range opts {
		path += "/" + o
	}
	var resp any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// NetworkInfo calls GET /api/zerotier/network/info
// Parameters:
//   - uuid (optional, default: null)
func (c *Client) NetworkInfo(ctx context.Context, opts ...string) (any, error) {
	path := "/api/zerotier/network/info"
	for _, o := range opts {
		path += "/" + o
	}
	var resp any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// NetworkSearch calls GET /api/zerotier/network/search
func (c *Client) NetworkSearch(ctx context.Context) (any, error) {
	path := "/api/zerotier/network/search"
	var resp any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// NetworkSet calls POST /api/zerotier/network/set
// Parameters:
//   - uuid (optional, default: null)
func (c *Client) NetworkSet(ctx context.Context, body any, opts ...string) (any, error) {
	path := "/api/zerotier/network/set"
	for _, o := range opts {
		path += "/" + o
	}
	var resp any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// NetworkToggle calls POST /api/zerotier/network/toggle
// Parameters:
//   - uuid (optional, default: null)
func (c *Client) NetworkToggle(ctx context.Context, body any, opts ...string) (any, error) {
	path := "/api/zerotier/network/toggle"
	for _, o := range opts {
		path += "/" + o
	}
	var resp any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// SettingsGet calls GET /api/zerotier/settings/get
func (c *Client) SettingsGet(ctx context.Context) (any, error) {
	path := "/api/zerotier/settings/get"
	var resp any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// SettingsSet calls POST /api/zerotier/settings/set
func (c *Client) SettingsSet(ctx context.Context, body any) (any, error) {
	path := "/api/zerotier/settings/set"
	var resp any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// SettingsStatus calls GET /api/zerotier/settings/status
func (c *Client) SettingsStatus(ctx context.Context) (any, error) {
	path := "/api/zerotier/settings/status"
	var resp any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}
