// Code generated by opnsense-cli/generate; DO NOT EDIT.

package wazuhagent

import (
	"context"

	"github.com/jontk/opnsense-cli/opnsense"
)

// Client wraps the base OPNsense client for wazuhagent API calls.
type Client struct {
	client *opnsense.Client
}

// NewClient creates a new wazuhagent API client.
func NewClient(c *opnsense.Client) *Client {
	return &Client{client: c}
}

// ServiceReconfigure calls POST /api/wazuhagent/service/reconfigure
func (c *Client) ServiceReconfigure(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/wazuhagent/service/reconfigure"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// ServiceRestart calls POST /api/wazuhagent/service/restart
func (c *Client) ServiceRestart(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/wazuhagent/service/restart"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// ServiceStart calls POST /api/wazuhagent/service/start
func (c *Client) ServiceStart(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/wazuhagent/service/start"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// ServiceStatus calls GET /api/wazuhagent/service/status
func (c *Client) ServiceStatus(ctx context.Context) (map[string]any, error) {
	path := "/api/wazuhagent/service/status"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// ServiceStop calls POST /api/wazuhagent/service/stop
func (c *Client) ServiceStop(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/wazuhagent/service/stop"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// SettingsGet calls GET /api/wazuhagent/settings/get
func (c *Client) SettingsGet(ctx context.Context) (map[string]any, error) {
	path := "/api/wazuhagent/settings/get"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// SettingsSet calls POST /api/wazuhagent/settings/set
func (c *Client) SettingsSet(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/wazuhagent/settings/set"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}
