// Code generated by opnsense-cli/generate; DO NOT EDIT.

package nut

import "github.com/jontk/opnsense-cli/opnsense"

// General represents a general model item.
type General struct {
	Enable opnsense.OPNBool `json:"enable"`
	Mode   string           `json:"mode"` // Valid values: standalone, netclient
	Name   string           `json:"name"`
	Listen string           `json:"listen"`
}

// Account represents a account model item.
type Account struct {
	AdminPassword string `json:"admin_password"`
	MonPassword   string `json:"mon_password"`
}

// Usbhid represents a usbhid model item.
type Usbhid struct {
	Enable opnsense.OPNBool `json:"enable"`
	Args   string           `json:"args,omitempty"`
}

// Apcsmart represents a apcsmart model item.
type Apcsmart struct {
	Enable opnsense.OPNBool `json:"enable"`
	Args   string           `json:"args,omitempty"`
}

// Apcupsd represents a apcupsd model item.
type Apcupsd struct {
	Enable   opnsense.OPNBool `json:"enable"`
	Hostname string           `json:"hostname"`
	Port     string           `json:"port,omitempty"`
}

// Bcmxcpusb represents a bcmxcpusb model item.
type Bcmxcpusb struct {
	Enable opnsense.OPNBool `json:"enable"`
	Args   string           `json:"args,omitempty"`
}

// Blazerusb represents a blazerusb model item.
type Blazerusb struct {
	Enable opnsense.OPNBool `json:"enable"`
	Args   string           `json:"args,omitempty"`
}

// Blazerser represents a blazerser model item.
type Blazerser struct {
	Enable opnsense.OPNBool `json:"enable"`
	Args   string           `json:"args,omitempty"`
}

// Netclient represents a netclient model item.
type Netclient struct {
	Enable   opnsense.OPNBool `json:"enable"`
	Address  string           `json:"address,omitempty"`
	Port     string           `json:"port,omitempty"`
	User     string           `json:"user,omitempty"`
	Password string           `json:"password,omitempty"`
}

// Qx represents a qx model item.
type Qx struct {
	Enable opnsense.OPNBool `json:"enable"`
	Args   string           `json:"args,omitempty"`
}

// Riello represents a riello model item.
type Riello struct {
	Enable opnsense.OPNBool `json:"enable"`
	Args   string           `json:"args,omitempty"`
}

// Snmp represents a snmp model item.
type Snmp struct {
	Enable opnsense.OPNBool `json:"enable"`
	Args   string           `json:"args,omitempty"`
}
