// Code generated by opnsense-cli/generate; DO NOT EDIT.

// Package cron provides a client for the OPNsense cron API.
package cron

import (
	"context"
	"fmt"

	"github.com/jontk/opnsense-cli/opnsense"
)

// Client wraps the base OPNsense client for cron API calls.
type Client struct {
	client *opnsense.Client
}

// NewClient creates a new cron API client.
func NewClient(c *opnsense.Client) *Client {
	return &Client{client: c}
}

// ServiceReconfigure calls POST /api/cron/service/reconfigure
func (c *Client) ServiceReconfigure(ctx context.Context, body any) (any, error) {
	path := "/api/cron/service/reconfigure"
	var resp any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// SettingsAddJob calls POST /api/cron/settings/addJob
func (c *Client) SettingsAddJob(ctx context.Context, body *Job) (*opnsense.GenericResponse, error) {
	path := "/api/cron/settings/addJob"
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"job": body}, &resp)
	return &resp, err
}

// SettingsDelJob calls POST /api/cron/settings/delJob
// Parameters:
//   - uuid
func (c *Client) SettingsDelJob(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/cron/settings/delJob/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// SettingsGet calls GET /api/cron/settings/get
func (c *Client) SettingsGet(ctx context.Context) (any, error) {
	path := "/api/cron/settings/get"
	var resp any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// SettingsGetJob calls GET /api/cron/settings/getJob
// Parameters:
//   - uuid (optional, default: null)
func (c *Client) SettingsGetJob(ctx context.Context, opts ...string) (*Job, error) {
	path := "/api/cron/settings/getJob"
	for _, o := range opts {
		path += "/" + o
	}
	var resp jobGetItemResponse
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return &resp.Job, err
}

// SettingsSearchJobs calls GET,POST /api/cron/settings/searchJobs
func (c *Client) SettingsSearchJobs(ctx context.Context, body any) (*opnsense.SearchResult[Job], error) {
	path := "/api/cron/settings/searchJobs"
	var resp opnsense.SearchResult[Job]
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return &resp, err
}

// SettingsSet calls POST /api/cron/settings/set
func (c *Client) SettingsSet(ctx context.Context, body any) (any, error) {
	path := "/api/cron/settings/set"
	var resp any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// SettingsSetJob calls POST /api/cron/settings/setJob
// Parameters:
//   - uuid
func (c *Client) SettingsSetJob(ctx context.Context, uuid string, body *Job) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/cron/settings/setJob/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"job": body}, &resp)
	return &resp, err
}

// SettingsToggleJob calls POST /api/cron/settings/toggleJob
// Parameters:
//   - uuid
//   - enabled (optional, default: null)
func (c *Client) SettingsToggleJob(ctx context.Context, uuid string, opts ...string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/cron/settings/toggleJob/%s", uuid)
	for _, o := range opts {
		path += "/" + o
	}
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}
