// Code generated by opnsense-cli/generate; DO NOT EDIT.

package turnserver

import "github.com/jontk/opnsense-cli/opnsense"

// Settings represents a settings model item.
type Settings struct {
	Enabled             opnsense.OPNBool `json:"Enabled"`
	ListenIP            string           `json:"ListenIP"`
	ListenPort          string           `json:"ListenPort"`
	MinPort             string           `json:"MinPort"`
	MaxPort             string           `json:"MaxPort"`
	TlsEnabled          opnsense.OPNBool `json:"TlsEnabled"`
	TlsCertificate      string           `json:"TlsCertificate,omitempty"`
	TlsPort             string           `json:"TlsPort"`
	UseAuthSecret       opnsense.OPNBool `json:"UseAuthSecret"`
	StaticAuthSecret    string           `json:"StaticAuthSecret,omitempty"`
	Realm               string           `json:"Realm,omitempty"`
	FingerprintsEnabled opnsense.OPNBool `json:"FingerprintsEnabled"`
	UserQuota           opnsense.OPNInt  `json:"UserQuota"`
	TotalQuota          opnsense.OPNInt  `json:"TotalQuota"`
	StaleNonce          opnsense.OPNInt  `json:"StaleNonce"`
	ChannelLifetime     opnsense.OPNInt  `json:"ChannelLifetime"`
	PermissionLifetime  opnsense.OPNInt  `json:"PermissionLifetime"`
}
