// Code generated by opnsense-cli/generate; DO NOT EDIT.

package gridexample

import "github.com/jontk/opnsense-cli/opnsense"

// Address represents a address model item.
type Address struct {
	Enabled     opnsense.OPNBool `json:"enabled"` // Required. Default: 1.
	Email       string           `json:"email"`   // Required.
	Description string           `json:"description,omitempty"`
}

type addressGetItemResponse struct {
	Address Address `json:"address"`
}
