// Code generated by opnsense-cli/generate; DO NOT EDIT.

// Package muninnode provides a client for the OPNsense muninnode API.
package muninnode

import (
	"context"

	"github.com/jontk/opnsense-cli/opnsense"
)

// Client wraps the base OPNsense client for muninnode API calls.
type Client struct {
	client *opnsense.Client
}

// NewClient creates a new muninnode API client.
func NewClient(c *opnsense.Client) *Client {
	return &Client{client: c}
}

// GeneralGet calls GET /api/muninnode/general/get
func (c *Client) GeneralGet(ctx context.Context) (any, error) {
	path := "/api/muninnode/general/get"
	var resp any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// GeneralSet calls POST /api/muninnode/general/set
func (c *Client) GeneralSet(ctx context.Context, body any) (any, error) {
	path := "/api/muninnode/general/set"
	var resp any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// ServiceReconfigure calls POST /api/muninnode/service/reconfigure
func (c *Client) ServiceReconfigure(ctx context.Context, body any) (any, error) {
	path := "/api/muninnode/service/reconfigure"
	var resp any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// ServiceRestart calls POST /api/muninnode/service/restart
func (c *Client) ServiceRestart(ctx context.Context, body any) (any, error) {
	path := "/api/muninnode/service/restart"
	var resp any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// ServiceStart calls POST /api/muninnode/service/start
func (c *Client) ServiceStart(ctx context.Context, body any) (any, error) {
	path := "/api/muninnode/service/start"
	var resp any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// ServiceStatus calls GET /api/muninnode/service/status
func (c *Client) ServiceStatus(ctx context.Context) (any, error) {
	path := "/api/muninnode/service/status"
	var resp any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// ServiceStop calls POST /api/muninnode/service/stop
func (c *Client) ServiceStop(ctx context.Context, body any) (any, error) {
	path := "/api/muninnode/service/stop"
	var resp any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}
