// Code generated by opnsense-cli/generate; DO NOT EDIT.

package openconnect

// Settings represents a settings model item.
type Settings struct {
	Enabled           string `json:"enabled"`
	Server            string `json:"server"`
	User              string `json:"user"`
	Password          string `json:"password"`
	Servercert        string `json:"servercert,omitempty"`
	Hash              string `json:"hash"` // Valid values: sha256, sha1, pin-sha256
	Group             string `json:"group,omitempty"`
	Clientcertificate string `json:"clientcertificate,omitempty"`
	Tokenmode         string `json:"tokenmode,omitempty"` // Valid values: rsa, totp, hotp, oidc
	Tokensecret       string `json:"tokensecret,omitempty"`
	Allowinsecure     string `json:"allowinsecure"`
	Protocol          string `json:"protocol"` // Valid values: anyconnect, nc, pulse, gp, f5, fortinet, array
}
