// Code generated by opnsense-cli/generate; DO NOT EDIT.

package netdata

import "github.com/jontk/opnsense-cli/opnsense"

// Settings represents a settings model item.
type Settings struct {
	Enabled opnsense.OPNBool `json:"enabled"`
	Listen  string           `json:"listen"`
	Port    string           `json:"port"`
}
