// Code generated by opnsense-cli/generate; DO NOT EDIT.

package dnscryptproxy

import (
	"context"
	"fmt"

	"github.com/jontk/opnsense-cli/opnsense"
)

// Client wraps the base OPNsense client for dnscryptproxy API calls.
type Client struct {
	client *opnsense.Client
}

// NewClient creates a new dnscryptproxy API client.
func NewClient(c *opnsense.Client) *Client {
	return &Client{client: c}
}

// CloakAddCloak calls POST /api/dnscryptproxy/cloak/addCloak
func (c *Client) CloakAddCloak(ctx context.Context, body *Cloak) (*opnsense.GenericResponse, error) {
	path := "/api/dnscryptproxy/cloak/addCloak"
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"cloak": body}, &resp)
	return &resp, err
}

// CloakDelCloak calls POST /api/dnscryptproxy/cloak/delCloak
// Parameters:
//   - uuid
func (c *Client) CloakDelCloak(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/dnscryptproxy/cloak/delCloak/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// CloakGet calls GET /api/dnscryptproxy/cloak/get
func (c *Client) CloakGet(ctx context.Context) (map[string]any, error) {
	path := "/api/dnscryptproxy/cloak/get"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// CloakGetCloak calls GET /api/dnscryptproxy/cloak/getCloak
// Parameters:
//   - uuid (optional, default: null)
func (c *Client) CloakGetCloak(ctx context.Context, opts ...string) (*Cloak, error) {
	path := "/api/dnscryptproxy/cloak/getCloak"
	for _, o := range opts {
		path += "/" + o
	}
	var resp cloakGetItemResponse
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return &resp.Cloak, err
}

// CloakSearchCloak calls GET,POST /api/dnscryptproxy/cloak/searchCloak
func (c *Client) CloakSearchCloak(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/dnscryptproxy/cloak/searchCloak"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// CloakSet calls POST /api/dnscryptproxy/cloak/set
func (c *Client) CloakSet(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/dnscryptproxy/cloak/set"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// CloakSetCloak calls POST /api/dnscryptproxy/cloak/setCloak
// Parameters:
//   - uuid
func (c *Client) CloakSetCloak(ctx context.Context, uuid string, body *Cloak) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/dnscryptproxy/cloak/setCloak/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"cloak": body}, &resp)
	return &resp, err
}

// CloakToggleCloak calls POST /api/dnscryptproxy/cloak/toggleCloak
// Parameters:
//   - uuid
func (c *Client) CloakToggleCloak(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/dnscryptproxy/cloak/toggleCloak/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// DnsblGet calls GET /api/dnscryptproxy/dnsbl/get
func (c *Client) DnsblGet(ctx context.Context) (map[string]any, error) {
	path := "/api/dnscryptproxy/dnsbl/get"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// DnsblSet calls POST /api/dnscryptproxy/dnsbl/set
func (c *Client) DnsblSet(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/dnscryptproxy/dnsbl/set"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// ForwardAddForward calls POST /api/dnscryptproxy/forward/addForward
func (c *Client) ForwardAddForward(ctx context.Context, body *Forward) (*opnsense.GenericResponse, error) {
	path := "/api/dnscryptproxy/forward/addForward"
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"forward": body}, &resp)
	return &resp, err
}

// ForwardDelForward calls POST /api/dnscryptproxy/forward/delForward
// Parameters:
//   - uuid
func (c *Client) ForwardDelForward(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/dnscryptproxy/forward/delForward/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// ForwardGet calls GET /api/dnscryptproxy/forward/get
func (c *Client) ForwardGet(ctx context.Context) (map[string]any, error) {
	path := "/api/dnscryptproxy/forward/get"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// ForwardGetForward calls GET /api/dnscryptproxy/forward/getForward
// Parameters:
//   - uuid (optional, default: null)
func (c *Client) ForwardGetForward(ctx context.Context, opts ...string) (*Forward, error) {
	path := "/api/dnscryptproxy/forward/getForward"
	for _, o := range opts {
		path += "/" + o
	}
	var resp forwardGetItemResponse
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return &resp.Forward, err
}

// ForwardSearchForward calls GET,POST /api/dnscryptproxy/forward/searchForward
func (c *Client) ForwardSearchForward(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/dnscryptproxy/forward/searchForward"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// ForwardSet calls POST /api/dnscryptproxy/forward/set
func (c *Client) ForwardSet(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/dnscryptproxy/forward/set"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// ForwardSetForward calls POST /api/dnscryptproxy/forward/setForward
// Parameters:
//   - uuid
func (c *Client) ForwardSetForward(ctx context.Context, uuid string, body *Forward) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/dnscryptproxy/forward/setForward/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"forward": body}, &resp)
	return &resp, err
}

// ForwardToggleForward calls POST /api/dnscryptproxy/forward/toggleForward
// Parameters:
//   - uuid
func (c *Client) ForwardToggleForward(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/dnscryptproxy/forward/toggleForward/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// GeneralGet calls GET /api/dnscryptproxy/general/get
func (c *Client) GeneralGet(ctx context.Context) (map[string]any, error) {
	path := "/api/dnscryptproxy/general/get"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// GeneralSet calls POST /api/dnscryptproxy/general/set
func (c *Client) GeneralSet(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/dnscryptproxy/general/set"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// ServerAddServer calls POST /api/dnscryptproxy/server/addServer
func (c *Client) ServerAddServer(ctx context.Context, body *Server) (*opnsense.GenericResponse, error) {
	path := "/api/dnscryptproxy/server/addServer"
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"server": body}, &resp)
	return &resp, err
}

// ServerDelServer calls POST /api/dnscryptproxy/server/delServer
// Parameters:
//   - uuid
func (c *Client) ServerDelServer(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/dnscryptproxy/server/delServer/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// ServerGet calls GET /api/dnscryptproxy/server/get
func (c *Client) ServerGet(ctx context.Context) (map[string]any, error) {
	path := "/api/dnscryptproxy/server/get"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// ServerGetServer calls GET /api/dnscryptproxy/server/getServer
// Parameters:
//   - uuid (optional, default: null)
func (c *Client) ServerGetServer(ctx context.Context, opts ...string) (*Server, error) {
	path := "/api/dnscryptproxy/server/getServer"
	for _, o := range opts {
		path += "/" + o
	}
	var resp serverGetItemResponse
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return &resp.Server, err
}

// ServerSearchServer calls GET,POST /api/dnscryptproxy/server/searchServer
func (c *Client) ServerSearchServer(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/dnscryptproxy/server/searchServer"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// ServerSet calls POST /api/dnscryptproxy/server/set
func (c *Client) ServerSet(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/dnscryptproxy/server/set"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// ServerSetServer calls POST /api/dnscryptproxy/server/setServer
// Parameters:
//   - uuid
func (c *Client) ServerSetServer(ctx context.Context, uuid string, body *Server) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/dnscryptproxy/server/setServer/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"server": body}, &resp)
	return &resp, err
}

// ServerToggleServer calls POST /api/dnscryptproxy/server/toggleServer
// Parameters:
//   - uuid
func (c *Client) ServerToggleServer(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/dnscryptproxy/server/toggleServer/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// ServiceDnsbl calls GET /api/dnscryptproxy/service/dnsbl
func (c *Client) ServiceDnsbl(ctx context.Context) (map[string]any, error) {
	path := "/api/dnscryptproxy/service/dnsbl"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// ServiceReconfigure calls POST /api/dnscryptproxy/service/reconfigure
func (c *Client) ServiceReconfigure(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/dnscryptproxy/service/reconfigure"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// ServiceRestart calls POST /api/dnscryptproxy/service/restart
func (c *Client) ServiceRestart(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/dnscryptproxy/service/restart"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// ServiceStart calls POST /api/dnscryptproxy/service/start
func (c *Client) ServiceStart(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/dnscryptproxy/service/start"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// ServiceStatus calls GET /api/dnscryptproxy/service/status
func (c *Client) ServiceStatus(ctx context.Context) (map[string]any, error) {
	path := "/api/dnscryptproxy/service/status"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// ServiceStop calls POST /api/dnscryptproxy/service/stop
func (c *Client) ServiceStop(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/dnscryptproxy/service/stop"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// WhitelistAddWhitelist calls POST /api/dnscryptproxy/whitelist/addWhitelist
func (c *Client) WhitelistAddWhitelist(ctx context.Context, body *Whitelist) (*opnsense.GenericResponse, error) {
	path := "/api/dnscryptproxy/whitelist/addWhitelist"
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"whitelist": body}, &resp)
	return &resp, err
}

// WhitelistDelWhitelist calls POST /api/dnscryptproxy/whitelist/delWhitelist
// Parameters:
//   - uuid
func (c *Client) WhitelistDelWhitelist(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/dnscryptproxy/whitelist/delWhitelist/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// WhitelistGet calls GET /api/dnscryptproxy/whitelist/get
func (c *Client) WhitelistGet(ctx context.Context) (map[string]any, error) {
	path := "/api/dnscryptproxy/whitelist/get"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// WhitelistGetWhitelist calls GET /api/dnscryptproxy/whitelist/getWhitelist
// Parameters:
//   - uuid (optional, default: null)
func (c *Client) WhitelistGetWhitelist(ctx context.Context, opts ...string) (*Whitelist, error) {
	path := "/api/dnscryptproxy/whitelist/getWhitelist"
	for _, o := range opts {
		path += "/" + o
	}
	var resp whitelistGetItemResponse
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return &resp.Whitelist, err
}

// WhitelistSearchWhitelist calls GET,POST /api/dnscryptproxy/whitelist/searchWhitelist
func (c *Client) WhitelistSearchWhitelist(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/dnscryptproxy/whitelist/searchWhitelist"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// WhitelistSet calls POST /api/dnscryptproxy/whitelist/set
func (c *Client) WhitelistSet(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/dnscryptproxy/whitelist/set"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// WhitelistSetWhitelist calls POST /api/dnscryptproxy/whitelist/setWhitelist
// Parameters:
//   - uuid
func (c *Client) WhitelistSetWhitelist(ctx context.Context, uuid string, body *Whitelist) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/dnscryptproxy/whitelist/setWhitelist/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"whitelist": body}, &resp)
	return &resp, err
}

// WhitelistToggleWhitelist calls POST /api/dnscryptproxy/whitelist/toggleWhitelist
// Parameters:
//   - uuid
func (c *Client) WhitelistToggleWhitelist(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/dnscryptproxy/whitelist/toggleWhitelist/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}
