// Code generated by opnsense-cli/generate; DO NOT EDIT.

package core

// Settings represents a settings model item.
type Settings struct {
	Disablepreempt  string `json:"disablepreempt"`
	Disconnectppps  string `json:"disconnectppps"`
	Pfsyncinterface string `json:"pfsyncinterface,omitempty"`
	Pfsyncpeerip    string `json:"pfsyncpeerip,omitempty"`
	Pfsyncversion   string `json:"pfsyncversion"` // Valid values: v1301, v1400
	Pfsyncdefer     string `json:"pfsyncdefer,omitempty"`
	Synchronizetoip string `json:"synchronizetoip,omitempty"`
	Verifypeer      string `json:"verifypeer"`
	Username        string `json:"username,omitempty"`
	Password        string `json:"password,omitempty"`
	Syncitems       string `json:"syncitems,omitempty"`
}

// Unbound represents a unbound model item.
type Unbound struct {
	Enabled        string `json:"enabled"`
	Dnssec         string `json:"dnssec"`
	Dnssecstripped string `json:"dnssecstripped"`
}

// Wan represents a wan model item.
type Wan struct {
	Disable       string `json:"disable,omitempty"`
	Ipv4Type      string `json:"ipv4_type"` // Valid values: dhcp, static, pppoe
	Spoofmac      string `json:"spoofmac,omitempty"`
	Mtu           string `json:"mtu,omitempty"`
	Mss           string `json:"mss,omitempty"`
	Ipaddr        string `json:"ipaddr,omitempty"`
	Gateway       string `json:"gateway,omitempty"`
	Dhcphostname  string `json:"dhcphostname,omitempty"`
	PppoeUsername string `json:"pppoe_username,omitempty"`
	PppoePassword string `json:"pppoe_password,omitempty"`
	PppoeProvider string `json:"pppoe_provider,omitempty"`
	Blockpriv     string `json:"blockpriv,omitempty"`
	Blockbogons   string `json:"blockbogons,omitempty"`
}

// Lan represents a lan model item.
type Lan struct {
	Ipaddr        string `json:"ipaddr,omitempty"`
	Disable       string `json:"disable,omitempty"`
	ConfigureDhcp string `json:"configure_dhcp"`
}

// DeploymentType represents a deployment_type model item.
type DeploymentType struct {
	Multiwan            string `json:"multiwan,omitempty"`
	DhcpDnsRegistration string `json:"dhcp_dns_registration,omitempty"`
	Maxthreads          string `json:"maxthreads,omitempty"`
}

// Item represents a item model item.
type Item struct {
	Tunable      string `json:"tunable,omitempty"`
	Value        string `json:"value,omitempty"`
	Descr        string `json:"descr,omitempty"`
	DefaultValue string `json:"default_value,omitempty"`
	Type         string `json:"type,omitempty"`
}

type itemGetItemResponse struct {
	Item Item `json:"item"`
}
