// Code generated by opnsense-cli/generate; DO NOT EDIT.

package cicap

// Settings represents a settings model item.
type Settings struct {
	EnableClamav              string `json:"enable_clamav"`
	Scanfiletypes             string `json:"scanfiletypes"` // Valid values: TEXT, DATA, EXECUTABLE, ARCHIVE, GIF, JPEG, MSOFFICE
	Sendpercentdata           string `json:"sendpercentdata"`
	Startsendpercentdataafter string `json:"startsendpercentdataafter"`
	Allow204responses         string `json:"allow204responses"`
	Passonerror               string `json:"passonerror"`
	Maxobjectsize             string `json:"maxobjectsize"`
}
