// Code generated by opnsense-cli/generate; DO NOT EDIT.

// Package freeradius provides a client for the OPNsense freeradius API.
package freeradius

import (
	"context"
	"fmt"

	"github.com/jontk/opnsense-cli/opnsense"
)

// Client wraps the base OPNsense client for freeradius API calls.
type Client struct {
	client *opnsense.Client
}

// NewClient creates a new freeradius API client.
func NewClient(c *opnsense.Client) *Client {
	return &Client{client: c}
}

// AvpairAddAvpair calls POST /api/freeradius/avpair/addAvpair
func (c *Client) AvpairAddAvpair(ctx context.Context, body *Avpair) (*opnsense.GenericResponse, error) {
	path := "/api/freeradius/avpair/addAvpair"
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"avpair": body}, &resp)
	return &resp, err
}

// AvpairDelAvpair calls POST /api/freeradius/avpair/delAvpair
// Parameters:
//   - uuid
func (c *Client) AvpairDelAvpair(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/freeradius/avpair/delAvpair/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// AvpairGet calls GET /api/freeradius/avpair/get
func (c *Client) AvpairGet(ctx context.Context) (any, error) {
	path := "/api/freeradius/avpair/get"
	var resp any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// AvpairGetAvpair calls GET /api/freeradius/avpair/getAvpair
// Parameters:
//   - uuid (optional, default: null)
func (c *Client) AvpairGetAvpair(ctx context.Context, opts ...string) (*Avpair, error) {
	path := "/api/freeradius/avpair/getAvpair"
	for _, o := range opts {
		path += "/" + o
	}
	var resp avpairGetItemResponse
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return &resp.Avpair, err
}

// AvpairSearchAvpair calls GET,POST /api/freeradius/avpair/searchAvpair
func (c *Client) AvpairSearchAvpair(ctx context.Context, body any) (*opnsense.SearchResult[Avpair], error) {
	path := "/api/freeradius/avpair/searchAvpair"
	var resp opnsense.SearchResult[Avpair]
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return &resp, err
}

// AvpairSet calls POST /api/freeradius/avpair/set
func (c *Client) AvpairSet(ctx context.Context, body any) (any, error) {
	path := "/api/freeradius/avpair/set"
	var resp any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// AvpairSetAvpair calls POST /api/freeradius/avpair/setAvpair
// Parameters:
//   - uuid
func (c *Client) AvpairSetAvpair(ctx context.Context, uuid string, body *Avpair) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/freeradius/avpair/setAvpair/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"avpair": body}, &resp)
	return &resp, err
}

// AvpairToggleAvpair calls POST /api/freeradius/avpair/toggleAvpair
// Parameters:
//   - uuid
func (c *Client) AvpairToggleAvpair(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/freeradius/avpair/toggleAvpair/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// ClientAddClient calls POST /api/freeradius/client/addClient
func (c *Client) ClientAddClient(ctx context.Context, body *ClientConfig) (*opnsense.GenericResponse, error) {
	path := "/api/freeradius/client/addClient"
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"client": body}, &resp)
	return &resp, err
}

// ClientDelClient calls POST /api/freeradius/client/delClient
// Parameters:
//   - uuid
func (c *Client) ClientDelClient(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/freeradius/client/delClient/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// ClientGet calls GET /api/freeradius/client/get
func (c *Client) ClientGet(ctx context.Context) (any, error) {
	path := "/api/freeradius/client/get"
	var resp any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// ClientGetClient calls GET /api/freeradius/client/getClient
// Parameters:
//   - uuid (optional, default: null)
func (c *Client) ClientGetClient(ctx context.Context, opts ...string) (*ClientConfig, error) {
	path := "/api/freeradius/client/getClient"
	for _, o := range opts {
		path += "/" + o
	}
	var resp clientGetItemResponse
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return &resp.ClientConfig, err
}

// ClientSearchClient calls GET /api/freeradius/client/searchClient
func (c *Client) ClientSearchClient(ctx context.Context) (*opnsense.SearchResult[ClientConfig], error) {
	path := "/api/freeradius/client/searchClient"
	var resp opnsense.SearchResult[ClientConfig]
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return &resp, err
}

// ClientSet calls POST /api/freeradius/client/set
func (c *Client) ClientSet(ctx context.Context, body any) (any, error) {
	path := "/api/freeradius/client/set"
	var resp any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// ClientSetClient calls POST /api/freeradius/client/setClient
// Parameters:
//   - uuid
func (c *Client) ClientSetClient(ctx context.Context, uuid string, body *ClientConfig) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/freeradius/client/setClient/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"client": body}, &resp)
	return &resp, err
}

// ClientToggleClient calls GET /api/freeradius/client/toggleClient
// Parameters:
//   - uuid
func (c *Client) ClientToggleClient(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/freeradius/client/toggleClient/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// DhcpAddDhcp calls POST /api/freeradius/dhcp/addDhcp
func (c *Client) DhcpAddDhcp(ctx context.Context, body *Dhcp) (*opnsense.GenericResponse, error) {
	path := "/api/freeradius/dhcp/addDhcp"
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"dhcp": body}, &resp)
	return &resp, err
}

// DhcpDelDhcp calls POST /api/freeradius/dhcp/delDhcp
// Parameters:
//   - uuid
func (c *Client) DhcpDelDhcp(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/freeradius/dhcp/delDhcp/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// DhcpGet calls GET /api/freeradius/dhcp/get
func (c *Client) DhcpGet(ctx context.Context) (any, error) {
	path := "/api/freeradius/dhcp/get"
	var resp any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// DhcpGetDhcp calls GET /api/freeradius/dhcp/getDhcp
// Parameters:
//   - uuid (optional, default: null)
func (c *Client) DhcpGetDhcp(ctx context.Context, opts ...string) (*Dhcp, error) {
	path := "/api/freeradius/dhcp/getDhcp"
	for _, o := range opts {
		path += "/" + o
	}
	var resp dhcpGetItemResponse
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return &resp.Dhcp, err
}

// DhcpSearchDhcp calls GET,POST /api/freeradius/dhcp/searchDhcp
func (c *Client) DhcpSearchDhcp(ctx context.Context, body any) (*opnsense.SearchResult[Dhcp], error) {
	path := "/api/freeradius/dhcp/searchDhcp"
	var resp opnsense.SearchResult[Dhcp]
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return &resp, err
}

// DhcpSet calls POST /api/freeradius/dhcp/set
func (c *Client) DhcpSet(ctx context.Context, body any) (any, error) {
	path := "/api/freeradius/dhcp/set"
	var resp any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// DhcpSetDhcp calls POST /api/freeradius/dhcp/setDhcp
// Parameters:
//   - uuid
func (c *Client) DhcpSetDhcp(ctx context.Context, uuid string, body *Dhcp) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/freeradius/dhcp/setDhcp/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"dhcp": body}, &resp)
	return &resp, err
}

// DhcpToggleDhcp calls POST /api/freeradius/dhcp/toggleDhcp
// Parameters:
//   - uuid
func (c *Client) DhcpToggleDhcp(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/freeradius/dhcp/toggleDhcp/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// EapGet calls GET /api/freeradius/eap/get
func (c *Client) EapGet(ctx context.Context) (any, error) {
	path := "/api/freeradius/eap/get"
	var resp any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// EapSet calls POST /api/freeradius/eap/set
func (c *Client) EapSet(ctx context.Context, body any) (any, error) {
	path := "/api/freeradius/eap/set"
	var resp any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// GeneralGet calls GET /api/freeradius/general/get
func (c *Client) GeneralGet(ctx context.Context) (any, error) {
	path := "/api/freeradius/general/get"
	var resp any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// GeneralSet calls POST /api/freeradius/general/set
func (c *Client) GeneralSet(ctx context.Context, body any) (any, error) {
	path := "/api/freeradius/general/set"
	var resp any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// LdapGet calls GET /api/freeradius/ldap/get
func (c *Client) LdapGet(ctx context.Context) (any, error) {
	path := "/api/freeradius/ldap/get"
	var resp any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// LdapSet calls POST /api/freeradius/ldap/set
func (c *Client) LdapSet(ctx context.Context, body any) (any, error) {
	path := "/api/freeradius/ldap/set"
	var resp any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// LdapgroupAddLdapgroup calls POST /api/freeradius/ldapgroup/addLdapgroup
func (c *Client) LdapgroupAddLdapgroup(ctx context.Context, body *Ldapgroup) (*opnsense.GenericResponse, error) {
	path := "/api/freeradius/ldapgroup/addLdapgroup"
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"ldapgroup": body}, &resp)
	return &resp, err
}

// LdapgroupDelLdapgroup calls POST /api/freeradius/ldapgroup/delLdapgroup
// Parameters:
//   - uuid
func (c *Client) LdapgroupDelLdapgroup(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/freeradius/ldapgroup/delLdapgroup/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// LdapgroupGet calls GET /api/freeradius/ldapgroup/get
func (c *Client) LdapgroupGet(ctx context.Context) (any, error) {
	path := "/api/freeradius/ldapgroup/get"
	var resp any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// LdapgroupGetLdapgroup calls GET /api/freeradius/ldapgroup/getLdapgroup
// Parameters:
//   - uuid (optional, default: null)
func (c *Client) LdapgroupGetLdapgroup(ctx context.Context, opts ...string) (*Ldapgroup, error) {
	path := "/api/freeradius/ldapgroup/getLdapgroup"
	for _, o := range opts {
		path += "/" + o
	}
	var resp ldapgroupGetItemResponse
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return &resp.Ldapgroup, err
}

// LdapgroupSearchLdapgroup calls GET /api/freeradius/ldapgroup/searchLdapgroup
func (c *Client) LdapgroupSearchLdapgroup(ctx context.Context) (*opnsense.SearchResult[Ldapgroup], error) {
	path := "/api/freeradius/ldapgroup/searchLdapgroup"
	var resp opnsense.SearchResult[Ldapgroup]
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return &resp, err
}

// LdapgroupSet calls POST /api/freeradius/ldapgroup/set
func (c *Client) LdapgroupSet(ctx context.Context, body any) (any, error) {
	path := "/api/freeradius/ldapgroup/set"
	var resp any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// LdapgroupSetLdapgroup calls POST /api/freeradius/ldapgroup/setLdapgroup
// Parameters:
//   - uuid
func (c *Client) LdapgroupSetLdapgroup(ctx context.Context, uuid string, body *Ldapgroup) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/freeradius/ldapgroup/setLdapgroup/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"ldapgroup": body}, &resp)
	return &resp, err
}

// LdapgroupToggleLdapgroup calls GET /api/freeradius/ldapgroup/toggleLdapgroup
// Parameters:
//   - uuid
func (c *Client) LdapgroupToggleLdapgroup(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/freeradius/ldapgroup/toggleLdapgroup/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// LeaseAddLease calls POST /api/freeradius/lease/addLease
func (c *Client) LeaseAddLease(ctx context.Context, body *Lease) (*opnsense.GenericResponse, error) {
	path := "/api/freeradius/lease/addLease"
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"lease": body}, &resp)
	return &resp, err
}

// LeaseDelLease calls POST /api/freeradius/lease/delLease
// Parameters:
//   - uuid
func (c *Client) LeaseDelLease(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/freeradius/lease/delLease/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// LeaseGet calls GET /api/freeradius/lease/get
func (c *Client) LeaseGet(ctx context.Context) (any, error) {
	path := "/api/freeradius/lease/get"
	var resp any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// LeaseGetLease calls GET /api/freeradius/lease/getLease
// Parameters:
//   - uuid (optional, default: null)
func (c *Client) LeaseGetLease(ctx context.Context, opts ...string) (*Lease, error) {
	path := "/api/freeradius/lease/getLease"
	for _, o := range opts {
		path += "/" + o
	}
	var resp leaseGetItemResponse
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return &resp.Lease, err
}

// LeaseSearchLease calls GET,POST /api/freeradius/lease/searchLease
func (c *Client) LeaseSearchLease(ctx context.Context, body any) (*opnsense.SearchResult[Lease], error) {
	path := "/api/freeradius/lease/searchLease"
	var resp opnsense.SearchResult[Lease]
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return &resp, err
}

// LeaseSet calls POST /api/freeradius/lease/set
func (c *Client) LeaseSet(ctx context.Context, body any) (any, error) {
	path := "/api/freeradius/lease/set"
	var resp any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// LeaseSetLease calls POST /api/freeradius/lease/setLease
// Parameters:
//   - uuid
func (c *Client) LeaseSetLease(ctx context.Context, uuid string, body *Lease) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/freeradius/lease/setLease/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"lease": body}, &resp)
	return &resp, err
}

// LeaseToggleLease calls POST /api/freeradius/lease/toggleLease
// Parameters:
//   - uuid
func (c *Client) LeaseToggleLease(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/freeradius/lease/toggleLease/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// ProxyAddHomeserver calls POST /api/freeradius/proxy/addHomeserver
func (c *Client) ProxyAddHomeserver(ctx context.Context, body *Homeserver) (*opnsense.GenericResponse, error) {
	path := "/api/freeradius/proxy/addHomeserver"
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"homeserver": body}, &resp)
	return &resp, err
}

// ProxyAddHomeserverpool calls POST /api/freeradius/proxy/addHomeserverpool
func (c *Client) ProxyAddHomeserverpool(ctx context.Context, body *Homeserverpool) (*opnsense.GenericResponse, error) {
	path := "/api/freeradius/proxy/addHomeserverpool"
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"homeserverpool": body}, &resp)
	return &resp, err
}

// ProxyAddRealm calls POST /api/freeradius/proxy/addRealm
func (c *Client) ProxyAddRealm(ctx context.Context, body *Realm) (*opnsense.GenericResponse, error) {
	path := "/api/freeradius/proxy/addRealm"
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"realm": body}, &resp)
	return &resp, err
}

// ProxyDelHomeserver calls POST /api/freeradius/proxy/delHomeserver
// Parameters:
//   - uuid
func (c *Client) ProxyDelHomeserver(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/freeradius/proxy/delHomeserver/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// ProxyDelHomeserverpool calls POST /api/freeradius/proxy/delHomeserverpool
// Parameters:
//   - uuid
func (c *Client) ProxyDelHomeserverpool(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/freeradius/proxy/delHomeserverpool/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// ProxyDelRealm calls POST /api/freeradius/proxy/delRealm
// Parameters:
//   - uuid
func (c *Client) ProxyDelRealm(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/freeradius/proxy/delRealm/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// ProxyGet calls GET /api/freeradius/proxy/get
func (c *Client) ProxyGet(ctx context.Context) (any, error) {
	path := "/api/freeradius/proxy/get"
	var resp any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// ProxyGetHomeserver calls GET /api/freeradius/proxy/getHomeserver
// Parameters:
//   - uuid (optional, default: null)
func (c *Client) ProxyGetHomeserver(ctx context.Context, opts ...string) (*Homeserver, error) {
	path := "/api/freeradius/proxy/getHomeserver"
	for _, o := range opts {
		path += "/" + o
	}
	var resp homeserverGetItemResponse
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return &resp.Homeserver, err
}

// ProxyGetHomeserverpool calls GET /api/freeradius/proxy/getHomeserverpool
// Parameters:
//   - uuid (optional, default: null)
func (c *Client) ProxyGetHomeserverpool(ctx context.Context, opts ...string) (*Homeserverpool, error) {
	path := "/api/freeradius/proxy/getHomeserverpool"
	for _, o := range opts {
		path += "/" + o
	}
	var resp homeserverpoolGetItemResponse
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return &resp.Homeserverpool, err
}

// ProxyGetRealm calls GET /api/freeradius/proxy/getRealm
// Parameters:
//   - uuid (optional, default: null)
func (c *Client) ProxyGetRealm(ctx context.Context, opts ...string) (*Realm, error) {
	path := "/api/freeradius/proxy/getRealm"
	for _, o := range opts {
		path += "/" + o
	}
	var resp realmGetItemResponse
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return &resp.Realm, err
}

// ProxySearchHomeserver calls GET /api/freeradius/proxy/searchHomeserver
func (c *Client) ProxySearchHomeserver(ctx context.Context) (*opnsense.SearchResult[Homeserver], error) {
	path := "/api/freeradius/proxy/searchHomeserver"
	var resp opnsense.SearchResult[Homeserver]
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return &resp, err
}

// ProxySearchHomeserverpool calls GET /api/freeradius/proxy/searchHomeserverpool
func (c *Client) ProxySearchHomeserverpool(ctx context.Context) (*opnsense.SearchResult[Homeserverpool], error) {
	path := "/api/freeradius/proxy/searchHomeserverpool"
	var resp opnsense.SearchResult[Homeserverpool]
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return &resp, err
}

// ProxySearchRealm calls GET /api/freeradius/proxy/searchRealm
func (c *Client) ProxySearchRealm(ctx context.Context) (*opnsense.SearchResult[Realm], error) {
	path := "/api/freeradius/proxy/searchRealm"
	var resp opnsense.SearchResult[Realm]
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return &resp, err
}

// ProxySet calls POST /api/freeradius/proxy/set
func (c *Client) ProxySet(ctx context.Context, body any) (any, error) {
	path := "/api/freeradius/proxy/set"
	var resp any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// ProxySetHomeserver calls POST /api/freeradius/proxy/setHomeserver
// Parameters:
//   - uuid
func (c *Client) ProxySetHomeserver(ctx context.Context, uuid string, body *Homeserver) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/freeradius/proxy/setHomeserver/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"homeserver": body}, &resp)
	return &resp, err
}

// ProxySetHomeserverpool calls POST /api/freeradius/proxy/setHomeserverpool
// Parameters:
//   - uuid
func (c *Client) ProxySetHomeserverpool(ctx context.Context, uuid string, body *Homeserverpool) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/freeradius/proxy/setHomeserverpool/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"homeserverpool": body}, &resp)
	return &resp, err
}

// ProxySetRealm calls POST /api/freeradius/proxy/setRealm
// Parameters:
//   - uuid
func (c *Client) ProxySetRealm(ctx context.Context, uuid string, body *Realm) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/freeradius/proxy/setRealm/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"realm": body}, &resp)
	return &resp, err
}

// ProxyToggleHomeserver calls GET /api/freeradius/proxy/toggleHomeserver
// Parameters:
//   - uuid
func (c *Client) ProxyToggleHomeserver(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/freeradius/proxy/toggleHomeserver/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// ProxyToggleHomeserverpool calls GET /api/freeradius/proxy/toggleHomeserverpool
// Parameters:
//   - uuid
func (c *Client) ProxyToggleHomeserverpool(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/freeradius/proxy/toggleHomeserverpool/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// ProxyToggleRealm calls GET /api/freeradius/proxy/toggleRealm
// Parameters:
//   - uuid
func (c *Client) ProxyToggleRealm(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/freeradius/proxy/toggleRealm/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// ServiceReconfigure calls POST /api/freeradius/service/reconfigure
func (c *Client) ServiceReconfigure(ctx context.Context, body any) (any, error) {
	path := "/api/freeradius/service/reconfigure"
	var resp any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// ServiceRestart calls POST /api/freeradius/service/restart
func (c *Client) ServiceRestart(ctx context.Context, body any) (any, error) {
	path := "/api/freeradius/service/restart"
	var resp any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// ServiceStart calls POST /api/freeradius/service/start
func (c *Client) ServiceStart(ctx context.Context, body any) (any, error) {
	path := "/api/freeradius/service/start"
	var resp any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// ServiceStatus calls GET /api/freeradius/service/status
func (c *Client) ServiceStatus(ctx context.Context) (any, error) {
	path := "/api/freeradius/service/status"
	var resp any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// ServiceStop calls POST /api/freeradius/service/stop
func (c *Client) ServiceStop(ctx context.Context, body any) (any, error) {
	path := "/api/freeradius/service/stop"
	var resp any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// UserAddUser calls POST /api/freeradius/user/addUser
func (c *Client) UserAddUser(ctx context.Context, body *User) (*opnsense.GenericResponse, error) {
	path := "/api/freeradius/user/addUser"
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"user": body}, &resp)
	return &resp, err
}

// UserDelUser calls POST /api/freeradius/user/delUser
// Parameters:
//   - uuid
func (c *Client) UserDelUser(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/freeradius/user/delUser/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// UserGet calls GET /api/freeradius/user/get
func (c *Client) UserGet(ctx context.Context) (any, error) {
	path := "/api/freeradius/user/get"
	var resp any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// UserGetUser calls GET /api/freeradius/user/getUser
// Parameters:
//   - uuid (optional, default: null)
func (c *Client) UserGetUser(ctx context.Context, opts ...string) (*User, error) {
	path := "/api/freeradius/user/getUser"
	for _, o := range opts {
		path += "/" + o
	}
	var resp userGetItemResponse
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return &resp.User, err
}

// UserSearchUser calls GET /api/freeradius/user/searchUser
func (c *Client) UserSearchUser(ctx context.Context) (*opnsense.SearchResult[User], error) {
	path := "/api/freeradius/user/searchUser"
	var resp opnsense.SearchResult[User]
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return &resp, err
}

// UserSet calls POST /api/freeradius/user/set
func (c *Client) UserSet(ctx context.Context, body any) (any, error) {
	path := "/api/freeradius/user/set"
	var resp any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// UserSetUser calls POST /api/freeradius/user/setUser
// Parameters:
//   - uuid
func (c *Client) UserSetUser(ctx context.Context, uuid string, body *User) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/freeradius/user/setUser/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"user": body}, &resp)
	return &resp, err
}

// UserToggleUser calls GET /api/freeradius/user/toggleUser
// Parameters:
//   - uuid
func (c *Client) UserToggleUser(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/freeradius/user/toggleUser/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}
