// Code generated by opnsense-cli/generate; DO NOT EDIT.

package freeradius

import "github.com/jontk/opnsense-cli/opnsense"

// Avpair represents a avpair model item.
type Avpair struct {
	Enabled  opnsense.OPNBool `json:"enabled"`
	Name     string           `json:"name"`
	Operator string           `json:"operator"`
	Value    string           `json:"value"`
}

// ClientConfig represents a client model item.
type ClientConfig struct {
	Enabled   opnsense.OPNBool `json:"enabled"`
	Name      string           `json:"name"`
	Secret    string           `json:"secret"`
	Ip        string           `json:"ip,omitempty"`
	RequireMa opnsense.OPNBool `json:"require_ma"`
}

// Dhcp represents a dhcp model item.
type Dhcp struct {
	Enabled   opnsense.OPNBool `json:"enabled"`
	Dns       string           `json:"dns"`
	Netmask   string           `json:"netmask"`
	Gatewayip string           `json:"gatewayip"`
}

// Settings represents a settings model item.
type Settings struct {
	Innertunnel  opnsense.OPNBool `json:"innertunnel"`
	Protocol     string           `json:"protocol"` // Valid values: LDAP, LDAPS
	Server       string           `json:"server,omitempty"`
	Serverport   string           `json:"serverport,omitempty"`
	Ldapcert     string           `json:"ldapcert,omitempty"`
	Ldapstarttls opnsense.OPNBool `json:"ldapstarttls"`
	Identity     string           `json:"identity,omitempty"`
	Password     string           `json:"password,omitempty"`
	BaseDn       string           `json:"base_dn,omitempty"`
	UserFilter   string           `json:"user_filter,omitempty"`
	GroupFilter  string           `json:"group_filter,omitempty"`
}

// Ldapgroup represents a ldapgroup model item.
type Ldapgroup struct {
	Enabled       opnsense.OPNBool `json:"enabled"`
	Ldapgroupname string           `json:"ldapgroupname"`
	Vlan          *opnsense.OPNInt `json:"vlan,omitempty"`
}

// Lease represents a lease model item.
type Lease struct {
	Enabled opnsense.OPNBool `json:"enabled"`
	Mac     string           `json:"mac"`
	Ip      string           `json:"ip"`
}

// Homeserver represents a homeserver model item.
type Homeserver struct {
	Enabled             opnsense.OPNBool  `json:"enabled"`
	Name                string            `json:"name"`
	Type                string            `json:"type"`        // Valid values: auth, acct, authacct, coa
	Addresstype         string            `json:"addresstype"` // Valid values: ipv4, ipv6, virtual_server
	Ipaddr              string            `json:"ipaddr,omitempty"`
	Ipaddr6             string            `json:"ipaddr6,omitempty"`
	Virtualserver       string            `json:"virtualserver,omitempty"`
	Port                opnsense.OPNInt   `json:"port"`
	Proto               string            `json:"proto"` // Valid values: udp, tcp
	Secret              string            `json:"secret,omitempty"`
	Sourceip            string            `json:"sourceip,omitempty"`
	ResponseWindow      opnsense.OPNInt   `json:"response_window"`
	NoResponseFail      *opnsense.OPNBool `json:"no_response_fail,omitempty"`
	Zombieperiod        opnsense.OPNInt   `json:"zombieperiod"`
	Reviveinterval      opnsense.OPNInt   `json:"reviveinterval"`
	Statuscheck         string            `json:"statuscheck"` // Valid values: none, status-server, request
	Checkinterval       opnsense.OPNInt   `json:"checkinterval"`
	Numanswersalive     opnsense.OPNInt   `json:"numanswersalive"`
	MaxOutstanding      opnsense.OPNInt   `json:"max_outstanding"`
	LimitMaxconnections opnsense.OPNInt   `json:"limit_maxconnections"`
	LimitMaxrequests    opnsense.OPNInt   `json:"limit_maxrequests"`
	LimitLifetime       opnsense.OPNInt   `json:"limit_lifetime"`
	LimitIdletimeout    opnsense.OPNInt   `json:"limit_idletimeout"`
}

// Homeserverpool represents a homeserverpool model item.
type Homeserverpool struct {
	Enabled       opnsense.OPNBool `json:"enabled"`
	Name          string           `json:"name"`
	Type          string           `json:"type"` // Valid values: fail-over, load-balance, client-balance, client-port-balance, keyed-balance
	Virtualserver string           `json:"virtualserver,omitempty"`
	Homeservers   string           `json:"homeservers"`
	Fallback      string           `json:"fallback,omitempty"`
}

// Realm represents a realm model item.
type Realm struct {
	Enabled  opnsense.OPNBool  `json:"enabled"`
	Name     string            `json:"name"`
	AuthPool string            `json:"auth_pool,omitempty"`
	AcctPool string            `json:"acct_pool,omitempty"`
	Nostrip  *opnsense.OPNBool `json:"nostrip,omitempty"`
}

// User represents a user model item.
type User struct {
	Enabled                     opnsense.OPNBool `json:"enabled"`
	Username                    string           `json:"username"`
	Password                    string           `json:"password"`
	Passwordencryption          string           `json:"passwordencryption"` // Valid values: cleartext, ntprehashed
	Description                 string           `json:"description,omitempty"`
	Ip                          string           `json:"ip,omitempty"`
	Subnet                      string           `json:"subnet,omitempty"`
	Route                       string           `json:"route,omitempty"`
	Ip6                         string           `json:"ip6,omitempty"`
	Vlan                        *opnsense.OPNInt `json:"vlan,omitempty"`
	Logintime                   string           `json:"logintime,omitempty"`
	Simuse                      *opnsense.OPNInt `json:"simuse,omitempty"`
	ExosVlanUntagged            *opnsense.OPNInt `json:"exos_vlan_untagged,omitempty"`
	ExosVlanTagged              string           `json:"exos_vlan_tagged,omitempty"`
	ExosPolicy                  string           `json:"exos_policy,omitempty"`
	WisprBwMinUp                *opnsense.OPNInt `json:"wispr_bw_min_up,omitempty"`
	WisprBwMaxUp                *opnsense.OPNInt `json:"wispr_bw_max_up,omitempty"`
	WisprBwMinDown              *opnsense.OPNInt `json:"wispr_bw_min_down,omitempty"`
	WisprBwMaxDown              *opnsense.OPNInt `json:"wispr_bw_max_down,omitempty"`
	ChillispotBwMaxUp           *opnsense.OPNInt `json:"chillispot_bw_max_up,omitempty"`
	ChillispotBwMaxDown         *opnsense.OPNInt `json:"chillispot_bw_max_down,omitempty"`
	MikrotikVlanIdNumber        *opnsense.OPNInt `json:"mikrotik_vlan_id_number,omitempty"`
	MikrotikVlanIdType          *opnsense.OPNInt `json:"mikrotik_vlan_id_type,omitempty"`
	SessionlimitMaxSessionLimit *opnsense.OPNInt `json:"sessionlimit_max_session_limit,omitempty"`
	Servicetype                 string           `json:"servicetype,omitempty"` // Valid values: Option1, Option2, Option3, Option4, Option5, Option6, Option7, Option8, Option9, Option10, Option11, Option12, Option13, Option14, Option15, Option16, Option17, Option18, Option19
	LinkedAVPair                string           `json:"linkedAVPair,omitempty"`
	TunnelPassword              string           `json:"tunnel_password,omitempty"`
}

type avpairGetItemResponse struct {
	Avpair Avpair `json:"avpair"`
}

type clientGetItemResponse struct {
	ClientConfig ClientConfig `json:"client"`
}

type dhcpGetItemResponse struct {
	Dhcp Dhcp `json:"dhcp"`
}

type ldapgroupGetItemResponse struct {
	Ldapgroup Ldapgroup `json:"ldapgroup"`
}

type leaseGetItemResponse struct {
	Lease Lease `json:"lease"`
}

type homeserverGetItemResponse struct {
	Homeserver Homeserver `json:"homeserver"`
}

type homeserverpoolGetItemResponse struct {
	Homeserverpool Homeserverpool `json:"homeserverpool"`
}

type realmGetItemResponse struct {
	Realm Realm `json:"realm"`
}

type userGetItemResponse struct {
	User User `json:"user"`
}
