// Code generated by opnsense-cli/generate; DO NOT EDIT.

package clamav

import "github.com/jontk/opnsense-cli/opnsense"

// Settings represents a settings model item.
type Settings struct {
	Enabled          opnsense.OPNBool  `json:"enabled"`
	FcEnabled        opnsense.OPNBool  `json:"fc_enabled"`
	Enabletcp        opnsense.OPNBool  `json:"enabletcp"`
	Maxthreads       *opnsense.OPNInt  `json:"maxthreads,omitempty"`
	Maxqueue         *opnsense.OPNInt  `json:"maxqueue,omitempty"`
	Idletimeout      *opnsense.OPNInt  `json:"idletimeout,omitempty"`
	Maxdirrecursion  *opnsense.OPNInt  `json:"maxdirrecursion,omitempty"`
	Followdirsym     *opnsense.OPNBool `json:"followdirsym,omitempty"`
	Followfilesym    *opnsense.OPNBool `json:"followfilesym,omitempty"`
	Disablecache     string            `json:"disablecache,omitempty"`
	Scanpe           *opnsense.OPNBool `json:"scanpe,omitempty"`
	Scanelf          *opnsense.OPNBool `json:"scanelf,omitempty"`
	Detectbroken     *opnsense.OPNBool `json:"detectbroken,omitempty"`
	Scanole2         *opnsense.OPNBool `json:"scanole2,omitempty"`
	Ole2blockmarcros *opnsense.OPNBool `json:"ole2blockmarcros,omitempty"`
	Scanpdf          *opnsense.OPNBool `json:"scanpdf,omitempty"`
	Scanswf          *opnsense.OPNBool `json:"scanswf,omitempty"`
	Scanxmldocs      *opnsense.OPNBool `json:"scanxmldocs,omitempty"`
	Scanhwp3         *opnsense.OPNBool `json:"scanhwp3,omitempty"`
	Scanmailfiles    *opnsense.OPNBool `json:"scanmailfiles,omitempty"`
	Scanhtml         *opnsense.OPNBool `json:"scanhtml,omitempty"`
	Scanarchive      *opnsense.OPNBool `json:"scanarchive,omitempty"`
	Arcblockenc      *opnsense.OPNBool `json:"arcblockenc,omitempty"`
	Maxscansize      string            `json:"maxscansize,omitempty"`
	Maxfilesize      string            `json:"maxfilesize,omitempty"`
	Maxrecursion     *opnsense.OPNInt  `json:"maxrecursion,omitempty"`
	Maxfiles         *opnsense.OPNInt  `json:"maxfiles,omitempty"`
	Logverbose       *opnsense.OPNBool `json:"logverbose,omitempty"`
	FcLogverbose     *opnsense.OPNBool `json:"fc_logverbose,omitempty"`
	FcDatabasemirror string            `json:"fc_databasemirror"`
	FcTimeout        string            `json:"fc_timeout"`
	FcMalwareexpert  *opnsense.OPNBool `json:"fc_malwareexpert,omitempty"`
	FcBlurl          *opnsense.OPNBool `json:"fc_blurl,omitempty"`
	FcJurlbla        *opnsense.OPNBool `json:"fc_jurlbla,omitempty"`
	FcBofhland       *opnsense.OPNBool `json:"fc_bofhland,omitempty"`
}

// List represents a list model item.
type List struct {
	Enabled opnsense.OPNBool `json:"enabled"`
	Name    string           `json:"name"`
	Link    string           `json:"link"`
}

type listGetItemResponse struct {
	List List `json:"list"`
}
