// Code generated by opnsense-cli/generate; DO NOT EDIT.

// Package routes provides a client for the OPNsense routes API.
package routes

import (
	"context"
	"fmt"

	"github.com/jontk/opnsense-cli/opnsense"
)

// Client wraps the base OPNsense client for routes API calls.
type Client struct {
	client *opnsense.Client
}

// NewClient creates a new routes API client.
func NewClient(c *opnsense.Client) *Client {
	return &Client{client: c}
}

// GatewayStatus calls GET /api/routes/gateway/status
func (c *Client) GatewayStatus(ctx context.Context) (map[string]any, error) {
	path := "/api/routes/gateway/status"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// RoutesAddroute calls POST /api/routes/routes/addroute
func (c *Client) RoutesAddroute(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/routes/routes/addroute"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// RoutesDelroute calls POST /api/routes/routes/delroute
// Parameters:
//   - uuid
func (c *Client) RoutesDelroute(ctx context.Context, uuid string, body any) (map[string]any, error) {
	path := fmt.Sprintf("/api/routes/routes/delroute/%s", uuid)
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// RoutesGet calls GET /api/routes/routes/get
func (c *Client) RoutesGet(ctx context.Context) (map[string]any, error) {
	path := "/api/routes/routes/get"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// RoutesGetroute calls GET /api/routes/routes/getroute
// Parameters:
//   - uuid (optional, default: null)
func (c *Client) RoutesGetroute(ctx context.Context, opts ...string) (map[string]any, error) {
	path := "/api/routes/routes/getroute"
	for _, o := range opts {
		path += "/" + o
	}
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// RoutesReconfigure calls POST /api/routes/routes/reconfigure
func (c *Client) RoutesReconfigure(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/routes/routes/reconfigure"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// RoutesSearchroute calls GET,POST /api/routes/routes/searchroute
func (c *Client) RoutesSearchroute(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/routes/routes/searchroute"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// RoutesSet calls POST /api/routes/routes/set
func (c *Client) RoutesSet(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/routes/routes/set"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// RoutesSetroute calls POST /api/routes/routes/setroute
// Parameters:
//   - uuid
func (c *Client) RoutesSetroute(ctx context.Context, uuid string, body any) (map[string]any, error) {
	path := fmt.Sprintf("/api/routes/routes/setroute/%s", uuid)
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// RoutesToggleroute calls POST /api/routes/routes/toggleroute
// Parameters:
//   - uuid
//   - disabled (optional, default: null)
func (c *Client) RoutesToggleroute(ctx context.Context, uuid string, body any, opts ...string) (map[string]any, error) {
	path := fmt.Sprintf("/api/routes/routes/toggleroute/%s", uuid)
	for _, o := range opts {
		path += "/" + o
	}
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}
