// Code generated by opnsense-cli/generate; DO NOT EDIT.

// Package routing provides a client for the OPNsense routing API.
package routing

import (
	"context"
	"fmt"

	"github.com/jontk/opnsense-cli/opnsense"
)

// Client wraps the base OPNsense client for routing API calls.
type Client struct {
	client *opnsense.Client
}

// NewClient creates a new routing API client.
func NewClient(c *opnsense.Client) *Client {
	return &Client{client: c}
}

// SettingsAddGateway calls POST /api/routing/settings/addGateway
func (c *Client) SettingsAddGateway(ctx context.Context, body *GatewayItem) (*opnsense.GenericResponse, error) {
	path := "/api/routing/settings/addGateway"
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"gateway_item": body}, &resp)
	return &resp, err
}

// SettingsDelGateway calls POST /api/routing/settings/delGateway
// Parameters:
//   - uuid
func (c *Client) SettingsDelGateway(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/routing/settings/delGateway/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// SettingsGet calls GET /api/routing/settings/get
func (c *Client) SettingsGet(ctx context.Context) (map[string]any, error) {
	path := "/api/routing/settings/get"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// SettingsGetGateway calls GET /api/routing/settings/getGateway
// Parameters:
//   - uuid (optional, default: null)
func (c *Client) SettingsGetGateway(ctx context.Context, opts ...string) (*GatewayItem, error) {
	path := "/api/routing/settings/getGateway"
	for _, o := range opts {
		path += "/" + o
	}
	var resp gateway_itemGetItemResponse
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return &resp.GatewayItem, err
}

// SettingsReconfigure calls POST /api/routing/settings/reconfigure
func (c *Client) SettingsReconfigure(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/routing/settings/reconfigure"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// SettingsSearchGateway calls GET /api/routing/settings/searchGateway
func (c *Client) SettingsSearchGateway(ctx context.Context) (*opnsense.SearchResult[GatewayItem], error) {
	path := "/api/routing/settings/searchGateway"
	var resp opnsense.SearchResult[GatewayItem]
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return &resp, err
}

// SettingsSet calls POST /api/routing/settings/set
func (c *Client) SettingsSet(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/routing/settings/set"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// SettingsSetGateway calls POST /api/routing/settings/setGateway
// Parameters:
//   - uuid
func (c *Client) SettingsSetGateway(ctx context.Context, uuid string, body *GatewayItem) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/routing/settings/setGateway/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"gateway_item": body}, &resp)
	return &resp, err
}

// SettingsToggleGateway calls POST /api/routing/settings/toggleGateway
// Parameters:
//   - uuid
//   - enabled (optional, default: null)
func (c *Client) SettingsToggleGateway(ctx context.Context, uuid string, opts ...string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/routing/settings/toggleGateway/%s", uuid)
	for _, o := range opts {
		path += "/" + o
	}
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}
