// Code generated by opnsense-cli/generate; DO NOT EDIT.

// Package redis provides a client for the OPNsense redis API.
package redis

import (
	"context"

	"github.com/jontk/opnsense-cli/opnsense"
)

// Client wraps the base OPNsense client for redis API calls.
type Client struct {
	client *opnsense.Client
}

// NewClient creates a new redis API client.
func NewClient(c *opnsense.Client) *Client {
	return &Client{client: c}
}

// ServiceReconfigure calls POST /api/redis/service/reconfigure
func (c *Client) ServiceReconfigure(ctx context.Context, body any) (any, error) {
	path := "/api/redis/service/reconfigure"
	var resp any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// ServiceResetdb calls GET /api/redis/service/resetdb
func (c *Client) ServiceResetdb(ctx context.Context) (any, error) {
	path := "/api/redis/service/resetdb"
	var resp any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// ServiceRestart calls POST /api/redis/service/restart
func (c *Client) ServiceRestart(ctx context.Context, body any) (any, error) {
	path := "/api/redis/service/restart"
	var resp any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// ServiceStart calls POST /api/redis/service/start
func (c *Client) ServiceStart(ctx context.Context, body any) (any, error) {
	path := "/api/redis/service/start"
	var resp any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// ServiceStatus calls GET /api/redis/service/status
func (c *Client) ServiceStatus(ctx context.Context) (any, error) {
	path := "/api/redis/service/status"
	var resp any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// ServiceStop calls POST /api/redis/service/stop
func (c *Client) ServiceStop(ctx context.Context, body any) (any, error) {
	path := "/api/redis/service/stop"
	var resp any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// SettingsGet calls GET /api/redis/settings/get
func (c *Client) SettingsGet(ctx context.Context) (any, error) {
	path := "/api/redis/settings/get"
	var resp any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// SettingsSet calls POST /api/redis/settings/set
func (c *Client) SettingsSet(ctx context.Context, body any) (any, error) {
	path := "/api/redis/settings/set"
	var resp any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}
