// Code generated by opnsense-cli/generate; DO NOT EDIT.

package redis

import "github.com/jontk/opnsense-cli/opnsense"

// General represents a general model item.
type General struct {
	Enabled        opnsense.OPNBool `json:"enabled"`
	Listen         string           `json:"listen,omitempty"`
	ProtectedMode  opnsense.OPNBool `json:"protected_mode"`
	Port           *opnsense.OPNInt `json:"port,omitempty"`
	LogLevel       string           `json:"log_level"` // Valid values: debug, verbose, notice, warning
	SyslogEnabled  opnsense.OPNBool `json:"syslog_enabled"`
	SyslogFacility string           `json:"syslog_facility"` // Valid values: USER, LOCAL0, LOCAL1, LOCAL2, LOCAL3, LOCAL4, LOCAL5, LOCAL6, LOCAL7
	Databases      opnsense.OPNInt  `json:"databases"`
}

// Security represents a security model item.
type Security struct {
	Password        string `json:"password,omitempty"`
	DisableCommands string `json:"disable_commands,omitempty"`
}

// Limits represents a limits model item.
type Limits struct {
	Maxclients       *opnsense.OPNInt `json:"maxclients,omitempty"`
	Maxmemory        *opnsense.OPNInt `json:"maxmemory,omitempty"`
	MaxmemoryPolicy  string           `json:"maxmemory_policy"` // Valid values: noeviction, volatile-ttl, allkeys-random, volatile-random, allkeys-lru, volatile-lru
	MaxmemorySamples *opnsense.OPNInt `json:"maxmemory_samples,omitempty"`
}

// Slowlog represents a slowlog model item.
type Slowlog struct {
	SlowerThan *opnsense.OPNInt `json:"slower_than,omitempty"`
	MaxLen     *opnsense.OPNInt `json:"max_len,omitempty"`
}
