// Code generated by opnsense-cli/generate; DO NOT EDIT.

package wireguard

import (
	"context"
	"fmt"

	"github.com/jontk/opnsense-cli/opnsense"
)

// Client wraps the base OPNsense client for wireguard API calls.
type Client struct {
	client *opnsense.Client
}

// NewClient creates a new wireguard API client.
func NewClient(c *opnsense.Client) *Client {
	return &Client{client: c}
}

// ClientAddClient calls GET /api/wireguard/client/addClient
func (c *Client) ClientAddClient(ctx context.Context, body *ClientConfig) (*opnsense.GenericResponse, error) {
	path := "/api/wireguard/client/addClient"
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"client": body}, &resp)
	return &resp, err
}

// ClientAddClientBuilder calls POST /api/wireguard/client/addClientBuilder
func (c *Client) ClientAddClientBuilder(ctx context.Context, body *ClientConfig) (*opnsense.GenericResponse, error) {
	path := "/api/wireguard/client/addClientBuilder"
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"client": body}, &resp)
	return &resp, err
}

// ClientDelClient calls POST /api/wireguard/client/delClient
// Parameters:
//   - uuid
func (c *Client) ClientDelClient(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/wireguard/client/delClient/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// ClientGet calls GET /api/wireguard/client/get
func (c *Client) ClientGet(ctx context.Context) (map[string]any, error) {
	path := "/api/wireguard/client/get"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// ClientGetClient calls GET /api/wireguard/client/getClient
// Parameters:
//   - uuid (optional, default: null)
func (c *Client) ClientGetClient(ctx context.Context, opts ...string) (*ClientConfig, error) {
	path := "/api/wireguard/client/getClient"
	for _, o := range opts {
		path += "/" + o
	}
	var resp clientGetItemResponse
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return &resp.ClientConfig, err
}

// ClientGetClientBuilder calls GET /api/wireguard/client/getClientBuilder
func (c *Client) ClientGetClientBuilder(ctx context.Context) (*ClientConfig, error) {
	path := "/api/wireguard/client/getClientBuilder"
	var resp clientGetItemResponse
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return &resp.ClientConfig, err
}

// ClientGetServerInfo calls GET /api/wireguard/client/getServerInfo
// Parameters:
//   - uuid (optional, default: null)
func (c *Client) ClientGetServerInfo(ctx context.Context, opts ...string) (map[string]any, error) {
	path := "/api/wireguard/client/getServerInfo"
	for _, o := range opts {
		path += "/" + o
	}
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// ClientListServers calls GET /api/wireguard/client/listServers
func (c *Client) ClientListServers(ctx context.Context) (map[string]any, error) {
	path := "/api/wireguard/client/listServers"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// ClientPsk calls GET /api/wireguard/client/psk
func (c *Client) ClientPsk(ctx context.Context) (map[string]any, error) {
	path := "/api/wireguard/client/psk"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// ClientSearchClient calls GET,POST /api/wireguard/client/searchClient
func (c *Client) ClientSearchClient(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/wireguard/client/searchClient"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// ClientSet calls POST /api/wireguard/client/set
func (c *Client) ClientSet(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/wireguard/client/set"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// ClientSetClient calls POST /api/wireguard/client/setClient
// Parameters:
//   - uuid
func (c *Client) ClientSetClient(ctx context.Context, uuid string, body *ClientConfig) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/wireguard/client/setClient/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"client": body}, &resp)
	return &resp, err
}

// ClientToggleClient calls POST /api/wireguard/client/toggleClient
// Parameters:
//   - uuid
func (c *Client) ClientToggleClient(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/wireguard/client/toggleClient/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// GeneralGet calls GET /api/wireguard/general/get
func (c *Client) GeneralGet(ctx context.Context) (map[string]any, error) {
	path := "/api/wireguard/general/get"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// GeneralSet calls POST /api/wireguard/general/set
func (c *Client) GeneralSet(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/wireguard/general/set"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// ServerAddServer calls POST /api/wireguard/server/addServer
// Parameters:
//   - uuid (optional, default: null)
func (c *Client) ServerAddServer(ctx context.Context, body *Server, opts ...string) (*opnsense.GenericResponse, error) {
	path := "/api/wireguard/server/addServer"
	for _, o := range opts {
		path += "/" + o
	}
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"server": body}, &resp)
	return &resp, err
}

// ServerDelServer calls POST /api/wireguard/server/delServer
// Parameters:
//   - uuid
func (c *Client) ServerDelServer(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/wireguard/server/delServer/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// ServerGet calls GET /api/wireguard/server/get
func (c *Client) ServerGet(ctx context.Context) (map[string]any, error) {
	path := "/api/wireguard/server/get"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// ServerGetServer calls GET /api/wireguard/server/getServer
// Parameters:
//   - uuid (optional, default: null)
func (c *Client) ServerGetServer(ctx context.Context, opts ...string) (*Server, error) {
	path := "/api/wireguard/server/getServer"
	for _, o := range opts {
		path += "/" + o
	}
	var resp serverGetItemResponse
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return &resp.Server, err
}

// ServerKeyPair calls GET /api/wireguard/server/keyPair
func (c *Client) ServerKeyPair(ctx context.Context) (map[string]any, error) {
	path := "/api/wireguard/server/keyPair"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// ServerSearchServer calls GET,POST /api/wireguard/server/searchServer
func (c *Client) ServerSearchServer(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/wireguard/server/searchServer"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// ServerSet calls POST /api/wireguard/server/set
func (c *Client) ServerSet(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/wireguard/server/set"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// ServerSetServer calls POST /api/wireguard/server/setServer
// Parameters:
//   - uuid (optional, default: null)
func (c *Client) ServerSetServer(ctx context.Context, body *Server, opts ...string) (*opnsense.GenericResponse, error) {
	path := "/api/wireguard/server/setServer"
	for _, o := range opts {
		path += "/" + o
	}
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"server": body}, &resp)
	return &resp, err
}

// ServerToggleServer calls POST /api/wireguard/server/toggleServer
// Parameters:
//   - uuid
func (c *Client) ServerToggleServer(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/wireguard/server/toggleServer/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// ServiceReconfigure calls POST /api/wireguard/service/reconfigure
func (c *Client) ServiceReconfigure(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/wireguard/service/reconfigure"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// ServiceRestart calls POST /api/wireguard/service/restart
func (c *Client) ServiceRestart(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/wireguard/service/restart"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// ServiceShow calls GET /api/wireguard/service/show
func (c *Client) ServiceShow(ctx context.Context) (map[string]any, error) {
	path := "/api/wireguard/service/show"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// ServiceStart calls POST /api/wireguard/service/start
func (c *Client) ServiceStart(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/wireguard/service/start"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// ServiceStatus calls GET /api/wireguard/service/status
func (c *Client) ServiceStatus(ctx context.Context) (map[string]any, error) {
	path := "/api/wireguard/service/status"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// ServiceStop calls POST /api/wireguard/service/stop
func (c *Client) ServiceStop(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/wireguard/service/stop"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}
