// Code generated by opnsense-cli/generate; DO NOT EDIT.

package hwprobe

import (
	"context"

	"github.com/jontk/opnsense-cli/opnsense"
)

// Client wraps the base OPNsense client for hwprobe API calls.
type Client struct {
	client *opnsense.Client
}

// NewClient creates a new hwprobe API client.
func NewClient(c *opnsense.Client) *Client {
	return &Client{client: c}
}

// GeneralGet calls GET /api/hwprobe/general/get
func (c *Client) GeneralGet(ctx context.Context) (map[string]any, error) {
	path := "/api/hwprobe/general/get"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// GeneralSet calls POST /api/hwprobe/general/set
func (c *Client) GeneralSet(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/hwprobe/general/set"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// ServiceReconfigure calls POST /api/hwprobe/service/reconfigure
func (c *Client) ServiceReconfigure(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/hwprobe/service/reconfigure"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// ServiceReport calls GET /api/hwprobe/service/report
func (c *Client) ServiceReport(ctx context.Context) (map[string]any, error) {
	path := "/api/hwprobe/service/report"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// ServiceRestart calls POST /api/hwprobe/service/restart
func (c *Client) ServiceRestart(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/hwprobe/service/restart"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// ServiceStart calls POST /api/hwprobe/service/start
func (c *Client) ServiceStart(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/hwprobe/service/start"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// ServiceStatus calls GET /api/hwprobe/service/status
func (c *Client) ServiceStatus(ctx context.Context) (map[string]any, error) {
	path := "/api/hwprobe/service/status"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// ServiceStop calls POST /api/hwprobe/service/stop
func (c *Client) ServiceStop(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/hwprobe/service/stop"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}
