// Code generated by opnsense-cli/generate; DO NOT EDIT.

package hwprobe

import "github.com/jontk/opnsense-cli/opnsense"

// Settings represents a settings model item.
type Settings struct {
	Enabled opnsense.OPNBool `json:"enabled"` // Required. Default: 0.
}
