// Code generated by opnsense-cli/generate; DO NOT EDIT.

package tftp

import "github.com/jontk/opnsense-cli/opnsense"

// Settings represents a settings model item.
type Settings struct {
	Enabled opnsense.OPNBool `json:"enabled"` // Required. Default: 0.
	Listen  string           `json:"listen"`  // Required. Default: 127.0.0.1.
}
