// Code generated by opnsense-cli/generate; DO NOT EDIT.

package telegraf

import "github.com/jontk/opnsense-cli/opnsense"

// Key represents a key model item.
type Key struct {
	Enabled opnsense.OPNBool `json:"enabled"`
	Name    string           `json:"name,omitempty"`
	Value   string           `json:"value,omitempty"`
}

type keyGetItemResponse struct {
	Key Key `json:"key"`
}
