// Code generated by opnsense-cli/generate; DO NOT EDIT.

package captiveportal

// Zone represents a zone model item.
type Zone struct {
	Enabled                  string `json:"enabled"`
	Zoneid                   string `json:"zoneid"`
	Interfaces               string `json:"interfaces"`
	DisableRules             string `json:"disableRules"`
	Authservers              string `json:"authservers,omitempty"`
	AlwaysSendAccountingReqs string `json:"alwaysSendAccountingReqs"`
	AuthEnforceGroup         string `json:"authEnforceGroup,omitempty"`
	Idletimeout              string `json:"idletimeout"`
	Hardtimeout              string `json:"hardtimeout"`
	Concurrentlogins         string `json:"concurrentlogins"`
	Certificate              string `json:"certificate,omitempty"`
	Servername               string `json:"servername,omitempty"`
	AllowedAddresses         string `json:"allowedAddresses,omitempty"`
	AllowedMACAddresses      string `json:"allowedMACAddresses,omitempty"`
	ExtendedPreAuthData      string `json:"extendedPreAuthData"`
	Template                 string `json:"template,omitempty"`
	Description              string `json:"description"`
}

// Template represents a template model item.
type Template struct {
	Fileid  string `json:"fileid"`
	Name    string `json:"name"`
	Content string `json:"content"`
}

type zoneGetItemResponse struct {
	Zone Zone `json:"zone"`
}
