// Code generated by opnsense-cli/generate; DO NOT EDIT.

// Package haproxy provides a client for the OPNsense haproxy API.
package haproxy

import (
	"context"
	"fmt"

	"github.com/jontk/opnsense-cli/opnsense"
)

// Client wraps the base OPNsense client for haproxy API calls.
type Client struct {
	client *opnsense.Client
}

// NewClient creates a new haproxy API client.
func NewClient(c *opnsense.Client) *Client {
	return &Client{client: c}
}

// ExportConfig calls GET /api/haproxy/export/config
func (c *Client) ExportConfig(ctx context.Context) (any, error) {
	path := "/api/haproxy/export/config"
	var resp any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// ExportDiff calls GET /api/haproxy/export/diff
func (c *Client) ExportDiff(ctx context.Context) (any, error) {
	path := "/api/haproxy/export/diff"
	var resp any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// ExportDownload calls GET /api/haproxy/export/download
// Parameters:
//   - type
func (c *Client) ExportDownload(ctx context.Context, typeVal string) (any, error) {
	path := fmt.Sprintf("/api/haproxy/export/download/%s", typeVal)
	var resp any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// MaintenanceCertActions calls GET /api/haproxy/maintenance/certActions
func (c *Client) MaintenanceCertActions(ctx context.Context) (any, error) {
	path := "/api/haproxy/maintenance/certActions"
	var resp any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// MaintenanceCertDiff calls GET /api/haproxy/maintenance/certDiff
func (c *Client) MaintenanceCertDiff(ctx context.Context) (any, error) {
	path := "/api/haproxy/maintenance/certDiff"
	var resp any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// MaintenanceCertSync calls GET /api/haproxy/maintenance/certSync
func (c *Client) MaintenanceCertSync(ctx context.Context) (any, error) {
	path := "/api/haproxy/maintenance/certSync"
	var resp any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// MaintenanceCertSyncBulk calls GET /api/haproxy/maintenance/certSyncBulk
func (c *Client) MaintenanceCertSyncBulk(ctx context.Context) (any, error) {
	path := "/api/haproxy/maintenance/certSyncBulk"
	var resp any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// MaintenanceFetchCronIntegration calls POST /api/haproxy/maintenance/fetchCronIntegration
func (c *Client) MaintenanceFetchCronIntegration(ctx context.Context, body any) (any, error) {
	path := "/api/haproxy/maintenance/fetchCronIntegration"
	var resp any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// MaintenanceGet calls GET /api/haproxy/maintenance/get
func (c *Client) MaintenanceGet(ctx context.Context) (any, error) {
	path := "/api/haproxy/maintenance/get"
	var resp any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// MaintenanceSearchCertificateDiff calls GET /api/haproxy/maintenance/searchCertificateDiff
func (c *Client) MaintenanceSearchCertificateDiff(ctx context.Context) (any, error) {
	path := "/api/haproxy/maintenance/searchCertificateDiff"
	var resp any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// MaintenanceSearchServer calls GET /api/haproxy/maintenance/searchServer
func (c *Client) MaintenanceSearchServer(ctx context.Context) (*opnsense.SearchResult[Server], error) {
	path := "/api/haproxy/maintenance/searchServer"
	var resp opnsense.SearchResult[Server]
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return &resp, err
}

// MaintenanceServerState calls GET /api/haproxy/maintenance/serverState
func (c *Client) MaintenanceServerState(ctx context.Context) (any, error) {
	path := "/api/haproxy/maintenance/serverState"
	var resp any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// MaintenanceServerStateBulk calls GET /api/haproxy/maintenance/serverStateBulk
func (c *Client) MaintenanceServerStateBulk(ctx context.Context) (any, error) {
	path := "/api/haproxy/maintenance/serverStateBulk"
	var resp any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// MaintenanceServerWeight calls GET /api/haproxy/maintenance/serverWeight
func (c *Client) MaintenanceServerWeight(ctx context.Context) (any, error) {
	path := "/api/haproxy/maintenance/serverWeight"
	var resp any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// MaintenanceServerWeightBulk calls GET /api/haproxy/maintenance/serverWeightBulk
func (c *Client) MaintenanceServerWeightBulk(ctx context.Context) (any, error) {
	path := "/api/haproxy/maintenance/serverWeightBulk"
	var resp any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// MaintenanceSet calls POST /api/haproxy/maintenance/set
func (c *Client) MaintenanceSet(ctx context.Context, body any) (any, error) {
	path := "/api/haproxy/maintenance/set"
	var resp any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// ServiceConfigtest calls GET /api/haproxy/service/configtest
func (c *Client) ServiceConfigtest(ctx context.Context) (any, error) {
	path := "/api/haproxy/service/configtest"
	var resp any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// ServiceReconfigure calls POST /api/haproxy/service/reconfigure
func (c *Client) ServiceReconfigure(ctx context.Context, body any) (any, error) {
	path := "/api/haproxy/service/reconfigure"
	var resp any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// ServiceRestart calls POST /api/haproxy/service/restart
func (c *Client) ServiceRestart(ctx context.Context, body any) (any, error) {
	path := "/api/haproxy/service/restart"
	var resp any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// ServiceStart calls POST /api/haproxy/service/start
func (c *Client) ServiceStart(ctx context.Context, body any) (any, error) {
	path := "/api/haproxy/service/start"
	var resp any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// ServiceStatus calls GET /api/haproxy/service/status
func (c *Client) ServiceStatus(ctx context.Context) (any, error) {
	path := "/api/haproxy/service/status"
	var resp any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// ServiceStop calls POST /api/haproxy/service/stop
func (c *Client) ServiceStop(ctx context.Context, body any) (any, error) {
	path := "/api/haproxy/service/stop"
	var resp any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// SettingsAddAcl calls POST /api/haproxy/settings/addAcl
func (c *Client) SettingsAddAcl(ctx context.Context, body *Acl) (*opnsense.GenericResponse, error) {
	path := "/api/haproxy/settings/addAcl"
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"acl": body}, &resp)
	return &resp, err
}

// SettingsAddAction calls POST /api/haproxy/settings/addAction
func (c *Client) SettingsAddAction(ctx context.Context, body *Action) (*opnsense.GenericResponse, error) {
	path := "/api/haproxy/settings/addAction"
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"action": body}, &resp)
	return &resp, err
}

// SettingsAddBackend calls POST /api/haproxy/settings/addBackend
func (c *Client) SettingsAddBackend(ctx context.Context, body *Backend) (*opnsense.GenericResponse, error) {
	path := "/api/haproxy/settings/addBackend"
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"backend": body}, &resp)
	return &resp, err
}

// SettingsAddCpu calls POST /api/haproxy/settings/addCpu
func (c *Client) SettingsAddCpu(ctx context.Context, body *Cpu) (*opnsense.GenericResponse, error) {
	path := "/api/haproxy/settings/addCpu"
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"cpu": body}, &resp)
	return &resp, err
}

// SettingsAddErrorfile calls POST /api/haproxy/settings/addErrorfile
func (c *Client) SettingsAddErrorfile(ctx context.Context, body *Errorfile) (*opnsense.GenericResponse, error) {
	path := "/api/haproxy/settings/addErrorfile"
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"errorfile": body}, &resp)
	return &resp, err
}

// SettingsAddFcgi calls POST /api/haproxy/settings/addFcgi
func (c *Client) SettingsAddFcgi(ctx context.Context, body *Fcgi) (*opnsense.GenericResponse, error) {
	path := "/api/haproxy/settings/addFcgi"
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"fcgi": body}, &resp)
	return &resp, err
}

// SettingsAddFrontend calls POST /api/haproxy/settings/addFrontend
func (c *Client) SettingsAddFrontend(ctx context.Context, body *Frontend) (*opnsense.GenericResponse, error) {
	path := "/api/haproxy/settings/addFrontend"
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"frontend": body}, &resp)
	return &resp, err
}

// SettingsAddGroup calls POST /api/haproxy/settings/addGroup
func (c *Client) SettingsAddGroup(ctx context.Context, body *Group) (*opnsense.GenericResponse, error) {
	path := "/api/haproxy/settings/addGroup"
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"group": body}, &resp)
	return &resp, err
}

// SettingsAddHealthcheck calls POST /api/haproxy/settings/addHealthcheck
func (c *Client) SettingsAddHealthcheck(ctx context.Context, body *Healthcheck) (*opnsense.GenericResponse, error) {
	path := "/api/haproxy/settings/addHealthcheck"
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"healthcheck": body}, &resp)
	return &resp, err
}

// SettingsAddLua calls POST /api/haproxy/settings/addLua
func (c *Client) SettingsAddLua(ctx context.Context, body *Lua) (*opnsense.GenericResponse, error) {
	path := "/api/haproxy/settings/addLua"
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"lua": body}, &resp)
	return &resp, err
}

// SettingsAddMapfile calls POST /api/haproxy/settings/addMapfile
func (c *Client) SettingsAddMapfile(ctx context.Context, body *Mapfile) (*opnsense.GenericResponse, error) {
	path := "/api/haproxy/settings/addMapfile"
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"mapfile": body}, &resp)
	return &resp, err
}

// SettingsAddServer calls POST /api/haproxy/settings/addServer
func (c *Client) SettingsAddServer(ctx context.Context, body *Server) (*opnsense.GenericResponse, error) {
	path := "/api/haproxy/settings/addServer"
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"server": body}, &resp)
	return &resp, err
}

// SettingsAddUser calls POST /api/haproxy/settings/addUser
func (c *Client) SettingsAddUser(ctx context.Context, body *User) (*opnsense.GenericResponse, error) {
	path := "/api/haproxy/settings/addUser"
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"user": body}, &resp)
	return &resp, err
}

// SettingsAddmailer calls POST /api/haproxy/settings/addmailer
func (c *Client) SettingsAddmailer(ctx context.Context, body any) (any, error) {
	path := "/api/haproxy/settings/addmailer"
	var resp any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// SettingsAddresolver calls POST /api/haproxy/settings/addresolver
func (c *Client) SettingsAddresolver(ctx context.Context, body any) (any, error) {
	path := "/api/haproxy/settings/addresolver"
	var resp any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// SettingsDelAcl calls POST /api/haproxy/settings/delAcl
// Parameters:
//   - uuid
func (c *Client) SettingsDelAcl(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/haproxy/settings/delAcl/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// SettingsDelAction calls POST /api/haproxy/settings/delAction
// Parameters:
//   - uuid
func (c *Client) SettingsDelAction(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/haproxy/settings/delAction/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// SettingsDelBackend calls POST /api/haproxy/settings/delBackend
// Parameters:
//   - uuid
func (c *Client) SettingsDelBackend(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/haproxy/settings/delBackend/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// SettingsDelCpu calls POST /api/haproxy/settings/delCpu
// Parameters:
//   - uuid
func (c *Client) SettingsDelCpu(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/haproxy/settings/delCpu/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// SettingsDelErrorfile calls POST /api/haproxy/settings/delErrorfile
// Parameters:
//   - uuid
func (c *Client) SettingsDelErrorfile(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/haproxy/settings/delErrorfile/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// SettingsDelFcgi calls POST /api/haproxy/settings/delFcgi
// Parameters:
//   - uuid
func (c *Client) SettingsDelFcgi(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/haproxy/settings/delFcgi/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// SettingsDelFrontend calls POST /api/haproxy/settings/delFrontend
// Parameters:
//   - uuid
func (c *Client) SettingsDelFrontend(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/haproxy/settings/delFrontend/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// SettingsDelGroup calls POST /api/haproxy/settings/delGroup
// Parameters:
//   - uuid
func (c *Client) SettingsDelGroup(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/haproxy/settings/delGroup/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// SettingsDelHealthcheck calls POST /api/haproxy/settings/delHealthcheck
// Parameters:
//   - uuid
func (c *Client) SettingsDelHealthcheck(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/haproxy/settings/delHealthcheck/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// SettingsDelLua calls POST /api/haproxy/settings/delLua
// Parameters:
//   - uuid
func (c *Client) SettingsDelLua(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/haproxy/settings/delLua/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// SettingsDelMapfile calls POST /api/haproxy/settings/delMapfile
// Parameters:
//   - uuid
func (c *Client) SettingsDelMapfile(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/haproxy/settings/delMapfile/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// SettingsDelServer calls POST /api/haproxy/settings/delServer
// Parameters:
//   - uuid
func (c *Client) SettingsDelServer(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/haproxy/settings/delServer/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// SettingsDelUser calls POST /api/haproxy/settings/delUser
// Parameters:
//   - uuid
func (c *Client) SettingsDelUser(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/haproxy/settings/delUser/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// SettingsDelmailer calls POST /api/haproxy/settings/delmailer
// Parameters:
//   - uuid
func (c *Client) SettingsDelmailer(ctx context.Context, uuid string, body any) (any, error) {
	path := fmt.Sprintf("/api/haproxy/settings/delmailer/%s", uuid)
	var resp any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// SettingsDelresolver calls POST /api/haproxy/settings/delresolver
// Parameters:
//   - uuid
func (c *Client) SettingsDelresolver(ctx context.Context, uuid string, body any) (any, error) {
	path := fmt.Sprintf("/api/haproxy/settings/delresolver/%s", uuid)
	var resp any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// SettingsGet calls GET /api/haproxy/settings/get
func (c *Client) SettingsGet(ctx context.Context) (any, error) {
	path := "/api/haproxy/settings/get"
	var resp any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// SettingsGetAcl calls GET /api/haproxy/settings/getAcl
// Parameters:
//   - uuid (optional, default: null)
func (c *Client) SettingsGetAcl(ctx context.Context, opts ...string) (*Acl, error) {
	path := "/api/haproxy/settings/getAcl"
	for _, o := range opts {
		path += "/" + o
	}
	var resp aclGetItemResponse
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return &resp.Acl, err
}

// SettingsGetAction calls GET /api/haproxy/settings/getAction
// Parameters:
//   - uuid (optional, default: null)
func (c *Client) SettingsGetAction(ctx context.Context, opts ...string) (*Action, error) {
	path := "/api/haproxy/settings/getAction"
	for _, o := range opts {
		path += "/" + o
	}
	var resp actionGetItemResponse
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return &resp.Action, err
}

// SettingsGetBackend calls GET /api/haproxy/settings/getBackend
// Parameters:
//   - uuid (optional, default: null)
func (c *Client) SettingsGetBackend(ctx context.Context, opts ...string) (*Backend, error) {
	path := "/api/haproxy/settings/getBackend"
	for _, o := range opts {
		path += "/" + o
	}
	var resp backendGetItemResponse
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return &resp.Backend, err
}

// SettingsGetCpu calls GET /api/haproxy/settings/getCpu
// Parameters:
//   - uuid (optional, default: null)
func (c *Client) SettingsGetCpu(ctx context.Context, opts ...string) (*Cpu, error) {
	path := "/api/haproxy/settings/getCpu"
	for _, o := range opts {
		path += "/" + o
	}
	var resp cpuGetItemResponse
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return &resp.Cpu, err
}

// SettingsGetErrorfile calls GET /api/haproxy/settings/getErrorfile
// Parameters:
//   - uuid (optional, default: null)
func (c *Client) SettingsGetErrorfile(ctx context.Context, opts ...string) (*Errorfile, error) {
	path := "/api/haproxy/settings/getErrorfile"
	for _, o := range opts {
		path += "/" + o
	}
	var resp errorfileGetItemResponse
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return &resp.Errorfile, err
}

// SettingsGetFcgi calls GET /api/haproxy/settings/getFcgi
// Parameters:
//   - uuid (optional, default: null)
func (c *Client) SettingsGetFcgi(ctx context.Context, opts ...string) (*Fcgi, error) {
	path := "/api/haproxy/settings/getFcgi"
	for _, o := range opts {
		path += "/" + o
	}
	var resp fcgiGetItemResponse
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return &resp.Fcgi, err
}

// SettingsGetFrontend calls GET /api/haproxy/settings/getFrontend
// Parameters:
//   - uuid (optional, default: null)
func (c *Client) SettingsGetFrontend(ctx context.Context, opts ...string) (*Frontend, error) {
	path := "/api/haproxy/settings/getFrontend"
	for _, o := range opts {
		path += "/" + o
	}
	var resp frontendGetItemResponse
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return &resp.Frontend, err
}

// SettingsGetGroup calls GET /api/haproxy/settings/getGroup
// Parameters:
//   - uuid (optional, default: null)
func (c *Client) SettingsGetGroup(ctx context.Context, opts ...string) (*Group, error) {
	path := "/api/haproxy/settings/getGroup"
	for _, o := range opts {
		path += "/" + o
	}
	var resp groupGetItemResponse
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return &resp.Group, err
}

// SettingsGetHealthcheck calls GET /api/haproxy/settings/getHealthcheck
// Parameters:
//   - uuid (optional, default: null)
func (c *Client) SettingsGetHealthcheck(ctx context.Context, opts ...string) (*Healthcheck, error) {
	path := "/api/haproxy/settings/getHealthcheck"
	for _, o := range opts {
		path += "/" + o
	}
	var resp healthcheckGetItemResponse
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return &resp.Healthcheck, err
}

// SettingsGetLua calls GET /api/haproxy/settings/getLua
// Parameters:
//   - uuid (optional, default: null)
func (c *Client) SettingsGetLua(ctx context.Context, opts ...string) (*Lua, error) {
	path := "/api/haproxy/settings/getLua"
	for _, o := range opts {
		path += "/" + o
	}
	var resp luaGetItemResponse
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return &resp.Lua, err
}

// SettingsGetMapfile calls GET /api/haproxy/settings/getMapfile
// Parameters:
//   - uuid (optional, default: null)
func (c *Client) SettingsGetMapfile(ctx context.Context, opts ...string) (*Mapfile, error) {
	path := "/api/haproxy/settings/getMapfile"
	for _, o := range opts {
		path += "/" + o
	}
	var resp mapfileGetItemResponse
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return &resp.Mapfile, err
}

// SettingsGetServer calls GET /api/haproxy/settings/getServer
// Parameters:
//   - uuid (optional, default: null)
func (c *Client) SettingsGetServer(ctx context.Context, opts ...string) (*Server, error) {
	path := "/api/haproxy/settings/getServer"
	for _, o := range opts {
		path += "/" + o
	}
	var resp serverGetItemResponse
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return &resp.Server, err
}

// SettingsGetUser calls GET /api/haproxy/settings/getUser
// Parameters:
//   - uuid (optional, default: null)
func (c *Client) SettingsGetUser(ctx context.Context, opts ...string) (*User, error) {
	path := "/api/haproxy/settings/getUser"
	for _, o := range opts {
		path += "/" + o
	}
	var resp userGetItemResponse
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return &resp.User, err
}

// SettingsGetmailer calls GET /api/haproxy/settings/getmailer
// Parameters:
//   - uuid (optional, default: null)
func (c *Client) SettingsGetmailer(ctx context.Context, opts ...string) (any, error) {
	path := "/api/haproxy/settings/getmailer"
	for _, o := range opts {
		path += "/" + o
	}
	var resp any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// SettingsGetresolver calls GET /api/haproxy/settings/getresolver
// Parameters:
//   - uuid (optional, default: null)
func (c *Client) SettingsGetresolver(ctx context.Context, opts ...string) (any, error) {
	path := "/api/haproxy/settings/getresolver"
	for _, o := range opts {
		path += "/" + o
	}
	var resp any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// SettingsSearchAcls calls GET,POST /api/haproxy/settings/searchAcls
func (c *Client) SettingsSearchAcls(ctx context.Context, body any) (*opnsense.SearchResult[Acl], error) {
	path := "/api/haproxy/settings/searchAcls"
	var resp opnsense.SearchResult[Acl]
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return &resp, err
}

// SettingsSearchActions calls GET,POST /api/haproxy/settings/searchActions
func (c *Client) SettingsSearchActions(ctx context.Context, body any) (*opnsense.SearchResult[Action], error) {
	path := "/api/haproxy/settings/searchActions"
	var resp opnsense.SearchResult[Action]
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return &resp, err
}

// SettingsSearchBackends calls GET,POST /api/haproxy/settings/searchBackends
func (c *Client) SettingsSearchBackends(ctx context.Context, body any) (*opnsense.SearchResult[Backend], error) {
	path := "/api/haproxy/settings/searchBackends"
	var resp opnsense.SearchResult[Backend]
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return &resp, err
}

// SettingsSearchCpus calls GET,POST /api/haproxy/settings/searchCpus
func (c *Client) SettingsSearchCpus(ctx context.Context, body any) (*opnsense.SearchResult[Cpu], error) {
	path := "/api/haproxy/settings/searchCpus"
	var resp opnsense.SearchResult[Cpu]
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return &resp, err
}

// SettingsSearchErrorfiles calls GET,POST /api/haproxy/settings/searchErrorfiles
func (c *Client) SettingsSearchErrorfiles(ctx context.Context, body any) (*opnsense.SearchResult[Errorfile], error) {
	path := "/api/haproxy/settings/searchErrorfiles"
	var resp opnsense.SearchResult[Errorfile]
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return &resp, err
}

// SettingsSearchFcgis calls GET,POST /api/haproxy/settings/searchFcgis
func (c *Client) SettingsSearchFcgis(ctx context.Context, body any) (*opnsense.SearchResult[Fcgi], error) {
	path := "/api/haproxy/settings/searchFcgis"
	var resp opnsense.SearchResult[Fcgi]
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return &resp, err
}

// SettingsSearchFrontends calls GET,POST /api/haproxy/settings/searchFrontends
func (c *Client) SettingsSearchFrontends(ctx context.Context, body any) (*opnsense.SearchResult[Frontend], error) {
	path := "/api/haproxy/settings/searchFrontends"
	var resp opnsense.SearchResult[Frontend]
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return &resp, err
}

// SettingsSearchGroups calls GET,POST /api/haproxy/settings/searchGroups
func (c *Client) SettingsSearchGroups(ctx context.Context, body any) (*opnsense.SearchResult[Group], error) {
	path := "/api/haproxy/settings/searchGroups"
	var resp opnsense.SearchResult[Group]
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return &resp, err
}

// SettingsSearchHealthchecks calls GET,POST /api/haproxy/settings/searchHealthchecks
func (c *Client) SettingsSearchHealthchecks(ctx context.Context, body any) (*opnsense.SearchResult[Healthcheck], error) {
	path := "/api/haproxy/settings/searchHealthchecks"
	var resp opnsense.SearchResult[Healthcheck]
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return &resp, err
}

// SettingsSearchLuas calls GET,POST /api/haproxy/settings/searchLuas
func (c *Client) SettingsSearchLuas(ctx context.Context, body any) (*opnsense.SearchResult[Lua], error) {
	path := "/api/haproxy/settings/searchLuas"
	var resp opnsense.SearchResult[Lua]
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return &resp, err
}

// SettingsSearchMapfiles calls GET,POST /api/haproxy/settings/searchMapfiles
func (c *Client) SettingsSearchMapfiles(ctx context.Context, body any) (*opnsense.SearchResult[Mapfile], error) {
	path := "/api/haproxy/settings/searchMapfiles"
	var resp opnsense.SearchResult[Mapfile]
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return &resp, err
}

// SettingsSearchServers calls GET,POST /api/haproxy/settings/searchServers
func (c *Client) SettingsSearchServers(ctx context.Context, body any) (*opnsense.SearchResult[Server], error) {
	path := "/api/haproxy/settings/searchServers"
	var resp opnsense.SearchResult[Server]
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return &resp, err
}

// SettingsSearchUsers calls GET,POST /api/haproxy/settings/searchUsers
func (c *Client) SettingsSearchUsers(ctx context.Context, body any) (*opnsense.SearchResult[User], error) {
	path := "/api/haproxy/settings/searchUsers"
	var resp opnsense.SearchResult[User]
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return &resp, err
}

// SettingsSearchmailers calls GET,POST /api/haproxy/settings/searchmailers
func (c *Client) SettingsSearchmailers(ctx context.Context, body any) (any, error) {
	path := "/api/haproxy/settings/searchmailers"
	var resp any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// SettingsSearchresolvers calls GET,POST /api/haproxy/settings/searchresolvers
func (c *Client) SettingsSearchresolvers(ctx context.Context, body any) (any, error) {
	path := "/api/haproxy/settings/searchresolvers"
	var resp any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// SettingsSet calls POST /api/haproxy/settings/set
func (c *Client) SettingsSet(ctx context.Context, body any) (any, error) {
	path := "/api/haproxy/settings/set"
	var resp any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// SettingsSetAcl calls POST /api/haproxy/settings/setAcl
// Parameters:
//   - uuid
func (c *Client) SettingsSetAcl(ctx context.Context, uuid string, body *Acl) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/haproxy/settings/setAcl/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"acl": body}, &resp)
	return &resp, err
}

// SettingsSetAction calls POST /api/haproxy/settings/setAction
// Parameters:
//   - uuid
func (c *Client) SettingsSetAction(ctx context.Context, uuid string, body *Action) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/haproxy/settings/setAction/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"action": body}, &resp)
	return &resp, err
}

// SettingsSetBackend calls POST /api/haproxy/settings/setBackend
// Parameters:
//   - uuid
func (c *Client) SettingsSetBackend(ctx context.Context, uuid string, body *Backend) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/haproxy/settings/setBackend/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"backend": body}, &resp)
	return &resp, err
}

// SettingsSetCpu calls POST /api/haproxy/settings/setCpu
// Parameters:
//   - uuid
func (c *Client) SettingsSetCpu(ctx context.Context, uuid string, body *Cpu) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/haproxy/settings/setCpu/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"cpu": body}, &resp)
	return &resp, err
}

// SettingsSetErrorfile calls POST /api/haproxy/settings/setErrorfile
// Parameters:
//   - uuid
func (c *Client) SettingsSetErrorfile(ctx context.Context, uuid string, body *Errorfile) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/haproxy/settings/setErrorfile/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"errorfile": body}, &resp)
	return &resp, err
}

// SettingsSetFcgi calls POST /api/haproxy/settings/setFcgi
// Parameters:
//   - uuid
func (c *Client) SettingsSetFcgi(ctx context.Context, uuid string, body *Fcgi) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/haproxy/settings/setFcgi/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"fcgi": body}, &resp)
	return &resp, err
}

// SettingsSetFrontend calls POST /api/haproxy/settings/setFrontend
// Parameters:
//   - uuid
func (c *Client) SettingsSetFrontend(ctx context.Context, uuid string, body *Frontend) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/haproxy/settings/setFrontend/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"frontend": body}, &resp)
	return &resp, err
}

// SettingsSetGroup calls POST /api/haproxy/settings/setGroup
// Parameters:
//   - uuid
func (c *Client) SettingsSetGroup(ctx context.Context, uuid string, body *Group) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/haproxy/settings/setGroup/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"group": body}, &resp)
	return &resp, err
}

// SettingsSetHealthcheck calls POST /api/haproxy/settings/setHealthcheck
// Parameters:
//   - uuid
func (c *Client) SettingsSetHealthcheck(ctx context.Context, uuid string, body *Healthcheck) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/haproxy/settings/setHealthcheck/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"healthcheck": body}, &resp)
	return &resp, err
}

// SettingsSetLua calls POST /api/haproxy/settings/setLua
// Parameters:
//   - uuid
func (c *Client) SettingsSetLua(ctx context.Context, uuid string, body *Lua) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/haproxy/settings/setLua/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"lua": body}, &resp)
	return &resp, err
}

// SettingsSetMapfile calls POST /api/haproxy/settings/setMapfile
// Parameters:
//   - uuid
func (c *Client) SettingsSetMapfile(ctx context.Context, uuid string, body *Mapfile) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/haproxy/settings/setMapfile/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"mapfile": body}, &resp)
	return &resp, err
}

// SettingsSetServer calls POST /api/haproxy/settings/setServer
// Parameters:
//   - uuid
func (c *Client) SettingsSetServer(ctx context.Context, uuid string, body *Server) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/haproxy/settings/setServer/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"server": body}, &resp)
	return &resp, err
}

// SettingsSetUser calls POST /api/haproxy/settings/setUser
// Parameters:
//   - uuid
func (c *Client) SettingsSetUser(ctx context.Context, uuid string, body *User) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/haproxy/settings/setUser/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"user": body}, &resp)
	return &resp, err
}

// SettingsSetmailer calls POST /api/haproxy/settings/setmailer
// Parameters:
//   - uuid
func (c *Client) SettingsSetmailer(ctx context.Context, uuid string, body any) (any, error) {
	path := fmt.Sprintf("/api/haproxy/settings/setmailer/%s", uuid)
	var resp any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// SettingsSetresolver calls POST /api/haproxy/settings/setresolver
// Parameters:
//   - uuid
func (c *Client) SettingsSetresolver(ctx context.Context, uuid string, body any) (any, error) {
	path := fmt.Sprintf("/api/haproxy/settings/setresolver/%s", uuid)
	var resp any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// SettingsToggleBackend calls POST /api/haproxy/settings/toggleBackend
// Parameters:
//   - uuid
//   - enabled (optional, default: null)
func (c *Client) SettingsToggleBackend(ctx context.Context, uuid string, opts ...string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/haproxy/settings/toggleBackend/%s", uuid)
	for _, o := range opts {
		path += "/" + o
	}
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// SettingsToggleCpu calls POST /api/haproxy/settings/toggleCpu
// Parameters:
//   - uuid
//   - enabled (optional, default: null)
func (c *Client) SettingsToggleCpu(ctx context.Context, uuid string, opts ...string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/haproxy/settings/toggleCpu/%s", uuid)
	for _, o := range opts {
		path += "/" + o
	}
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// SettingsToggleFrontend calls POST /api/haproxy/settings/toggleFrontend
// Parameters:
//   - uuid
func (c *Client) SettingsToggleFrontend(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/haproxy/settings/toggleFrontend/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// SettingsToggleGroup calls POST /api/haproxy/settings/toggleGroup
// Parameters:
//   - uuid
//   - enabled (optional, default: null)
func (c *Client) SettingsToggleGroup(ctx context.Context, uuid string, opts ...string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/haproxy/settings/toggleGroup/%s", uuid)
	for _, o := range opts {
		path += "/" + o
	}
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// SettingsToggleLua calls POST /api/haproxy/settings/toggleLua
// Parameters:
//   - uuid
//   - enabled (optional, default: null)
func (c *Client) SettingsToggleLua(ctx context.Context, uuid string, opts ...string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/haproxy/settings/toggleLua/%s", uuid)
	for _, o := range opts {
		path += "/" + o
	}
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// SettingsToggleServer calls POST /api/haproxy/settings/toggleServer
// Parameters:
//   - uuid
//   - enabled (optional, default: null)
func (c *Client) SettingsToggleServer(ctx context.Context, uuid string, opts ...string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/haproxy/settings/toggleServer/%s", uuid)
	for _, o := range opts {
		path += "/" + o
	}
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// SettingsToggleUser calls POST /api/haproxy/settings/toggleUser
// Parameters:
//   - uuid
//   - enabled (optional, default: null)
func (c *Client) SettingsToggleUser(ctx context.Context, uuid string, opts ...string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/haproxy/settings/toggleUser/%s", uuid)
	for _, o := range opts {
		path += "/" + o
	}
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// SettingsTogglemailer calls POST /api/haproxy/settings/togglemailer
// Parameters:
//   - uuid
//   - enabled (optional, default: null)
func (c *Client) SettingsTogglemailer(ctx context.Context, uuid string, body any, opts ...string) (any, error) {
	path := fmt.Sprintf("/api/haproxy/settings/togglemailer/%s", uuid)
	for _, o := range opts {
		path += "/" + o
	}
	var resp any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// SettingsToggleresolver calls POST /api/haproxy/settings/toggleresolver
// Parameters:
//   - uuid
//   - enabled (optional, default: null)
func (c *Client) SettingsToggleresolver(ctx context.Context, uuid string, body any, opts ...string) (any, error) {
	path := fmt.Sprintf("/api/haproxy/settings/toggleresolver/%s", uuid)
	for _, o := range opts {
		path += "/" + o
	}
	var resp any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// StatisticsCounters calls GET /api/haproxy/statistics/counters
func (c *Client) StatisticsCounters(ctx context.Context) (any, error) {
	path := "/api/haproxy/statistics/counters"
	var resp any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// StatisticsInfo calls GET /api/haproxy/statistics/info
func (c *Client) StatisticsInfo(ctx context.Context) (any, error) {
	path := "/api/haproxy/statistics/info"
	var resp any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// StatisticsTables calls GET /api/haproxy/statistics/tables
func (c *Client) StatisticsTables(ctx context.Context) (any, error) {
	path := "/api/haproxy/statistics/tables"
	var resp any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}
