// Code generated by opnsense-cli/generate; DO NOT EDIT.

// Package monit provides a client for the OPNsense monit API.
package monit

import (
	"context"
	"fmt"

	"github.com/jontk/opnsense-cli/opnsense"
)

// Client wraps the base OPNsense client for monit API calls.
type Client struct {
	client *opnsense.Client
}

// NewClient creates a new monit API client.
func NewClient(c *opnsense.Client) *Client {
	return &Client{client: c}
}

// ServiceCheck calls POST /api/monit/service/check
func (c *Client) ServiceCheck(ctx context.Context, body any) (any, error) {
	path := "/api/monit/service/check"
	var resp any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// ServiceReconfigure calls POST /api/monit/service/reconfigure
func (c *Client) ServiceReconfigure(ctx context.Context, body any) (any, error) {
	path := "/api/monit/service/reconfigure"
	var resp any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// ServiceRestart calls POST /api/monit/service/restart
func (c *Client) ServiceRestart(ctx context.Context, body any) (any, error) {
	path := "/api/monit/service/restart"
	var resp any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// ServiceStart calls POST /api/monit/service/start
func (c *Client) ServiceStart(ctx context.Context, body any) (any, error) {
	path := "/api/monit/service/start"
	var resp any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// ServiceStatus calls GET /api/monit/service/status
func (c *Client) ServiceStatus(ctx context.Context) (any, error) {
	path := "/api/monit/service/status"
	var resp any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// ServiceStop calls POST /api/monit/service/stop
func (c *Client) ServiceStop(ctx context.Context, body any) (any, error) {
	path := "/api/monit/service/stop"
	var resp any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// SettingsAddAlert calls POST /api/monit/settings/addAlert
func (c *Client) SettingsAddAlert(ctx context.Context, body *Alert) (*opnsense.GenericResponse, error) {
	path := "/api/monit/settings/addAlert"
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"alert": body}, &resp)
	return &resp, err
}

// SettingsAddService calls POST /api/monit/settings/addService
func (c *Client) SettingsAddService(ctx context.Context, body *Service) (*opnsense.GenericResponse, error) {
	path := "/api/monit/settings/addService"
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"service": body}, &resp)
	return &resp, err
}

// SettingsAddTest calls POST /api/monit/settings/addTest
func (c *Client) SettingsAddTest(ctx context.Context, body *Test) (*opnsense.GenericResponse, error) {
	path := "/api/monit/settings/addTest"
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"test": body}, &resp)
	return &resp, err
}

// SettingsDelAlert calls POST /api/monit/settings/delAlert
// Parameters:
//   - uuid
func (c *Client) SettingsDelAlert(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/monit/settings/delAlert/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// SettingsDelService calls POST /api/monit/settings/delService
// Parameters:
//   - uuid
func (c *Client) SettingsDelService(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/monit/settings/delService/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// SettingsDelTest calls POST /api/monit/settings/delTest
// Parameters:
//   - uuid
func (c *Client) SettingsDelTest(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/monit/settings/delTest/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// SettingsGet calls GET /api/monit/settings/get
func (c *Client) SettingsGet(ctx context.Context) (any, error) {
	path := "/api/monit/settings/get"
	var resp any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// SettingsGetAlert calls GET /api/monit/settings/getAlert
// Parameters:
//   - uuid (optional, default: null)
func (c *Client) SettingsGetAlert(ctx context.Context, opts ...string) (*Alert, error) {
	path := "/api/monit/settings/getAlert"
	for _, o := range opts {
		path += "/" + o
	}
	var resp alertGetItemResponse
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return &resp.Alert, err
}

// SettingsGetGeneral calls GET /api/monit/settings/getGeneral
func (c *Client) SettingsGetGeneral(ctx context.Context) (*General, error) {
	path := "/api/monit/settings/getGeneral"
	var resp generalGetItemResponse
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return &resp.General, err
}

// SettingsGetService calls GET /api/monit/settings/getService
// Parameters:
//   - uuid (optional, default: null)
func (c *Client) SettingsGetService(ctx context.Context, opts ...string) (*Service, error) {
	path := "/api/monit/settings/getService"
	for _, o := range opts {
		path += "/" + o
	}
	var resp serviceGetItemResponse
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return &resp.Service, err
}

// SettingsGetTest calls GET /api/monit/settings/getTest
// Parameters:
//   - uuid (optional, default: null)
func (c *Client) SettingsGetTest(ctx context.Context, opts ...string) (*Test, error) {
	path := "/api/monit/settings/getTest"
	for _, o := range opts {
		path += "/" + o
	}
	var resp testGetItemResponse
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return &resp.Test, err
}

// SettingsSearchAlert calls GET,POST /api/monit/settings/searchAlert
func (c *Client) SettingsSearchAlert(ctx context.Context, body any) (*opnsense.SearchResult[Alert], error) {
	path := "/api/monit/settings/searchAlert"
	var resp opnsense.SearchResult[Alert]
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return &resp, err
}

// SettingsSearchService calls GET,POST /api/monit/settings/searchService
func (c *Client) SettingsSearchService(ctx context.Context, body any) (*opnsense.SearchResult[Service], error) {
	path := "/api/monit/settings/searchService"
	var resp opnsense.SearchResult[Service]
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return &resp, err
}

// SettingsSearchTest calls GET,POST /api/monit/settings/searchTest
func (c *Client) SettingsSearchTest(ctx context.Context, body any) (*opnsense.SearchResult[Test], error) {
	path := "/api/monit/settings/searchTest"
	var resp opnsense.SearchResult[Test]
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return &resp, err
}

// SettingsSet calls POST /api/monit/settings/set
func (c *Client) SettingsSet(ctx context.Context, body any) (any, error) {
	path := "/api/monit/settings/set"
	var resp any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// SettingsSetAlert calls POST /api/monit/settings/setAlert
// Parameters:
//   - uuid
func (c *Client) SettingsSetAlert(ctx context.Context, uuid string, body *Alert) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/monit/settings/setAlert/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"alert": body}, &resp)
	return &resp, err
}

// SettingsSetService calls POST /api/monit/settings/setService
// Parameters:
//   - uuid
func (c *Client) SettingsSetService(ctx context.Context, uuid string, body *Service) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/monit/settings/setService/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"service": body}, &resp)
	return &resp, err
}

// SettingsSetTest calls POST /api/monit/settings/setTest
// Parameters:
//   - uuid
func (c *Client) SettingsSetTest(ctx context.Context, uuid string, body *Test) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/monit/settings/setTest/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"test": body}, &resp)
	return &resp, err
}

// SettingsToggleAlert calls POST /api/monit/settings/toggleAlert
// Parameters:
//   - uuid
//   - enabled (optional, default: null)
func (c *Client) SettingsToggleAlert(ctx context.Context, uuid string, opts ...string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/monit/settings/toggleAlert/%s", uuid)
	for _, o := range opts {
		path += "/" + o
	}
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// SettingsToggleService calls POST /api/monit/settings/toggleService
// Parameters:
//   - uuid
//   - enabled (optional, default: null)
func (c *Client) SettingsToggleService(ctx context.Context, uuid string, opts ...string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/monit/settings/toggleService/%s", uuid)
	for _, o := range opts {
		path += "/" + o
	}
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// StatusGet calls GET /api/monit/status/get
// Parameters:
//   - format (optional, default: xml)
func (c *Client) StatusGet(ctx context.Context, opts ...string) (any, error) {
	path := "/api/monit/status/get"
	for _, o := range opts {
		path += "/" + o
	}
	var resp any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}
