// Code generated by opnsense-cli/generate; DO NOT EDIT.

package caddy

import (
	"context"
	"fmt"

	"github.com/jontk/opnsense-cli/opnsense"
)

// Client wraps the base OPNsense client for caddy API calls.
type Client struct {
	client *opnsense.Client
}

// NewClient creates a new caddy API client.
func NewClient(c *opnsense.Client) *Client {
	return &Client{client: c}
}

// DiagnosticsCaddyfile calls GET /api/caddy/diagnostics/caddyfile
func (c *Client) DiagnosticsCaddyfile(ctx context.Context) (map[string]any, error) {
	path := "/api/caddy/diagnostics/caddyfile"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// DiagnosticsConfig calls GET /api/caddy/diagnostics/config
func (c *Client) DiagnosticsConfig(ctx context.Context) (map[string]any, error) {
	path := "/api/caddy/diagnostics/config"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// DiagnosticsGet calls GET /api/caddy/diagnostics/get
func (c *Client) DiagnosticsGet(ctx context.Context) (map[string]any, error) {
	path := "/api/caddy/diagnostics/get"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// DiagnosticsSet calls POST /api/caddy/diagnostics/set
func (c *Client) DiagnosticsSet(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/caddy/diagnostics/set"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// GeneralGet calls GET /api/caddy/general/get
func (c *Client) GeneralGet(ctx context.Context) (map[string]any, error) {
	path := "/api/caddy/general/get"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// GeneralSet calls POST /api/caddy/general/set
func (c *Client) GeneralSet(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/caddy/general/set"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// ReverseProxyAddAccessList calls POST /api/caddy/reverse_proxy/addAccessList
func (c *Client) ReverseProxyAddAccessList(ctx context.Context, body *Accesslist) (*opnsense.GenericResponse, error) {
	path := "/api/caddy/reverse_proxy/addAccessList"
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"accesslist": body}, &resp)
	return &resp, err
}

// ReverseProxyAddBasicAuth calls POST /api/caddy/reverse_proxy/addBasicAuth
func (c *Client) ReverseProxyAddBasicAuth(ctx context.Context, body *Basicauth) (*opnsense.GenericResponse, error) {
	path := "/api/caddy/reverse_proxy/addBasicAuth"
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"basicauth": body}, &resp)
	return &resp, err
}

// ReverseProxyAddHandle calls POST /api/caddy/reverse_proxy/addHandle
func (c *Client) ReverseProxyAddHandle(ctx context.Context, body *Handle) (*opnsense.GenericResponse, error) {
	path := "/api/caddy/reverse_proxy/addHandle"
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"handle": body}, &resp)
	return &resp, err
}

// ReverseProxyAddHeader calls POST /api/caddy/reverse_proxy/addHeader
func (c *Client) ReverseProxyAddHeader(ctx context.Context, body *Header) (*opnsense.GenericResponse, error) {
	path := "/api/caddy/reverse_proxy/addHeader"
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"header": body}, &resp)
	return &resp, err
}

// ReverseProxyAddLayer4 calls POST /api/caddy/reverse_proxy/addLayer4
func (c *Client) ReverseProxyAddLayer4(ctx context.Context, body *Layer4) (*opnsense.GenericResponse, error) {
	path := "/api/caddy/reverse_proxy/addLayer4"
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"layer4": body}, &resp)
	return &resp, err
}

// ReverseProxyAddLayer4Openvpn calls POST /api/caddy/reverse_proxy/addLayer4Openvpn
func (c *Client) ReverseProxyAddLayer4Openvpn(ctx context.Context, body *Layer4openvpn) (*opnsense.GenericResponse, error) {
	path := "/api/caddy/reverse_proxy/addLayer4Openvpn"
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"layer4openvpn": body}, &resp)
	return &resp, err
}

// ReverseProxyAddReverseProxy calls POST /api/caddy/reverse_proxy/addReverseProxy
func (c *Client) ReverseProxyAddReverseProxy(ctx context.Context, body *Reverse) (*opnsense.GenericResponse, error) {
	path := "/api/caddy/reverse_proxy/addReverseProxy"
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"reverse": body}, &resp)
	return &resp, err
}

// ReverseProxyAddSubdomain calls POST /api/caddy/reverse_proxy/addSubdomain
func (c *Client) ReverseProxyAddSubdomain(ctx context.Context, body *Subdomain) (*opnsense.GenericResponse, error) {
	path := "/api/caddy/reverse_proxy/addSubdomain"
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"subdomain": body}, &resp)
	return &resp, err
}

// ReverseProxyDelAccessList calls POST /api/caddy/reverse_proxy/delAccessList
// Parameters:
//   - uuid
func (c *Client) ReverseProxyDelAccessList(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/caddy/reverse_proxy/delAccessList/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// ReverseProxyDelBasicAuth calls POST /api/caddy/reverse_proxy/delBasicAuth
// Parameters:
//   - uuid
func (c *Client) ReverseProxyDelBasicAuth(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/caddy/reverse_proxy/delBasicAuth/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// ReverseProxyDelHandle calls POST /api/caddy/reverse_proxy/delHandle
// Parameters:
//   - uuid
func (c *Client) ReverseProxyDelHandle(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/caddy/reverse_proxy/delHandle/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// ReverseProxyDelHeader calls POST /api/caddy/reverse_proxy/delHeader
// Parameters:
//   - uuid
func (c *Client) ReverseProxyDelHeader(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/caddy/reverse_proxy/delHeader/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// ReverseProxyDelLayer4 calls POST /api/caddy/reverse_proxy/delLayer4
// Parameters:
//   - uuid
func (c *Client) ReverseProxyDelLayer4(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/caddy/reverse_proxy/delLayer4/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// ReverseProxyDelLayer4Openvpn calls POST /api/caddy/reverse_proxy/delLayer4Openvpn
// Parameters:
//   - uuid
func (c *Client) ReverseProxyDelLayer4Openvpn(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/caddy/reverse_proxy/delLayer4Openvpn/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// ReverseProxyDelReverseProxy calls POST /api/caddy/reverse_proxy/delReverseProxy
// Parameters:
//   - uuid
func (c *Client) ReverseProxyDelReverseProxy(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/caddy/reverse_proxy/delReverseProxy/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// ReverseProxyDelSubdomain calls POST /api/caddy/reverse_proxy/delSubdomain
// Parameters:
//   - uuid
func (c *Client) ReverseProxyDelSubdomain(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/caddy/reverse_proxy/delSubdomain/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// ReverseProxyGet calls GET /api/caddy/reverse_proxy/get
func (c *Client) ReverseProxyGet(ctx context.Context) (map[string]any, error) {
	path := "/api/caddy/reverse_proxy/get"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// ReverseProxyGetAccessList calls GET /api/caddy/reverse_proxy/getAccessList
// Parameters:
//   - uuid (optional, default: null)
func (c *Client) ReverseProxyGetAccessList(ctx context.Context, opts ...string) (*Accesslist, error) {
	path := "/api/caddy/reverse_proxy/getAccessList"
	for _, o := range opts {
		path += "/" + o
	}
	var resp accesslistGetItemResponse
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return &resp.Accesslist, err
}

// ReverseProxyGetAllReverseDomains calls GET /api/caddy/reverse_proxy/getAllReverseDomains
func (c *Client) ReverseProxyGetAllReverseDomains(ctx context.Context) (map[string]any, error) {
	path := "/api/caddy/reverse_proxy/getAllReverseDomains"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// ReverseProxyGetBasicAuth calls GET /api/caddy/reverse_proxy/getBasicAuth
// Parameters:
//   - uuid (optional, default: null)
func (c *Client) ReverseProxyGetBasicAuth(ctx context.Context, opts ...string) (*Basicauth, error) {
	path := "/api/caddy/reverse_proxy/getBasicAuth"
	for _, o := range opts {
		path += "/" + o
	}
	var resp basicauthGetItemResponse
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return &resp.Basicauth, err
}

// ReverseProxyGetHandle calls GET /api/caddy/reverse_proxy/getHandle
// Parameters:
//   - uuid (optional, default: null)
func (c *Client) ReverseProxyGetHandle(ctx context.Context, opts ...string) (*Handle, error) {
	path := "/api/caddy/reverse_proxy/getHandle"
	for _, o := range opts {
		path += "/" + o
	}
	var resp handleGetItemResponse
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return &resp.Handle, err
}

// ReverseProxyGetHeader calls GET /api/caddy/reverse_proxy/getHeader
// Parameters:
//   - uuid (optional, default: null)
func (c *Client) ReverseProxyGetHeader(ctx context.Context, opts ...string) (*Header, error) {
	path := "/api/caddy/reverse_proxy/getHeader"
	for _, o := range opts {
		path += "/" + o
	}
	var resp headerGetItemResponse
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return &resp.Header, err
}

// ReverseProxyGetLayer4 calls GET /api/caddy/reverse_proxy/getLayer4
// Parameters:
//   - uuid (optional, default: null)
func (c *Client) ReverseProxyGetLayer4(ctx context.Context, opts ...string) (*Layer4, error) {
	path := "/api/caddy/reverse_proxy/getLayer4"
	for _, o := range opts {
		path += "/" + o
	}
	var resp layer4GetItemResponse
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return &resp.Layer4, err
}

// ReverseProxyGetLayer4Openvpn calls GET /api/caddy/reverse_proxy/getLayer4Openvpn
// Parameters:
//   - uuid (optional, default: null)
func (c *Client) ReverseProxyGetLayer4Openvpn(ctx context.Context, opts ...string) (*Layer4openvpn, error) {
	path := "/api/caddy/reverse_proxy/getLayer4Openvpn"
	for _, o := range opts {
		path += "/" + o
	}
	var resp layer4openvpnGetItemResponse
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return &resp.Layer4openvpn, err
}

// ReverseProxyGetReverseProxy calls GET /api/caddy/reverse_proxy/getReverseProxy
// Parameters:
//   - uuid (optional, default: null)
func (c *Client) ReverseProxyGetReverseProxy(ctx context.Context, opts ...string) (*Reverse, error) {
	path := "/api/caddy/reverse_proxy/getReverseProxy"
	for _, o := range opts {
		path += "/" + o
	}
	var resp reverseGetItemResponse
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return &resp.Reverse, err
}

// ReverseProxyGetSubdomain calls GET /api/caddy/reverse_proxy/getSubdomain
// Parameters:
//   - uuid (optional, default: null)
func (c *Client) ReverseProxyGetSubdomain(ctx context.Context, opts ...string) (*Subdomain, error) {
	path := "/api/caddy/reverse_proxy/getSubdomain"
	for _, o := range opts {
		path += "/" + o
	}
	var resp subdomainGetItemResponse
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return &resp.Subdomain, err
}

// ReverseProxySearchAccessList calls GET,POST /api/caddy/reverse_proxy/searchAccessList
func (c *Client) ReverseProxySearchAccessList(ctx context.Context, body any) (*opnsense.SearchResult[Accesslist], error) {
	path := "/api/caddy/reverse_proxy/searchAccessList"
	var resp opnsense.SearchResult[Accesslist]
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return &resp, err
}

// ReverseProxySearchBasicAuth calls GET,POST /api/caddy/reverse_proxy/searchBasicAuth
func (c *Client) ReverseProxySearchBasicAuth(ctx context.Context, body any) (*opnsense.SearchResult[Basicauth], error) {
	path := "/api/caddy/reverse_proxy/searchBasicAuth"
	var resp opnsense.SearchResult[Basicauth]
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return &resp, err
}

// ReverseProxySearchHandle calls GET,POST /api/caddy/reverse_proxy/searchHandle
func (c *Client) ReverseProxySearchHandle(ctx context.Context, body any) (*opnsense.SearchResult[Handle], error) {
	path := "/api/caddy/reverse_proxy/searchHandle"
	var resp opnsense.SearchResult[Handle]
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return &resp, err
}

// ReverseProxySearchHeader calls GET,POST /api/caddy/reverse_proxy/searchHeader
func (c *Client) ReverseProxySearchHeader(ctx context.Context, body any) (*opnsense.SearchResult[Header], error) {
	path := "/api/caddy/reverse_proxy/searchHeader"
	var resp opnsense.SearchResult[Header]
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return &resp, err
}

// ReverseProxySearchLayer4 calls GET,POST /api/caddy/reverse_proxy/searchLayer4
func (c *Client) ReverseProxySearchLayer4(ctx context.Context, body any) (*opnsense.SearchResult[Layer4], error) {
	path := "/api/caddy/reverse_proxy/searchLayer4"
	var resp opnsense.SearchResult[Layer4]
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return &resp, err
}

// ReverseProxySearchLayer4Openvpn calls GET,POST /api/caddy/reverse_proxy/searchLayer4Openvpn
func (c *Client) ReverseProxySearchLayer4Openvpn(ctx context.Context, body any) (*opnsense.SearchResult[Layer4openvpn], error) {
	path := "/api/caddy/reverse_proxy/searchLayer4Openvpn"
	var resp opnsense.SearchResult[Layer4openvpn]
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return &resp, err
}

// ReverseProxySearchReverseProxy calls GET,POST /api/caddy/reverse_proxy/searchReverseProxy
func (c *Client) ReverseProxySearchReverseProxy(ctx context.Context, body any) (*opnsense.SearchResult[Reverse], error) {
	path := "/api/caddy/reverse_proxy/searchReverseProxy"
	var resp opnsense.SearchResult[Reverse]
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return &resp, err
}

// ReverseProxySearchSubdomain calls GET,POST /api/caddy/reverse_proxy/searchSubdomain
func (c *Client) ReverseProxySearchSubdomain(ctx context.Context, body any) (*opnsense.SearchResult[Subdomain], error) {
	path := "/api/caddy/reverse_proxy/searchSubdomain"
	var resp opnsense.SearchResult[Subdomain]
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return &resp, err
}

// ReverseProxySet calls POST /api/caddy/reverse_proxy/set
func (c *Client) ReverseProxySet(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/caddy/reverse_proxy/set"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// ReverseProxySetAccessList calls POST /api/caddy/reverse_proxy/setAccessList
// Parameters:
//   - uuid
func (c *Client) ReverseProxySetAccessList(ctx context.Context, uuid string, body *Accesslist) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/caddy/reverse_proxy/setAccessList/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"accesslist": body}, &resp)
	return &resp, err
}

// ReverseProxySetBasicAuth calls POST /api/caddy/reverse_proxy/setBasicAuth
// Parameters:
//   - uuid
func (c *Client) ReverseProxySetBasicAuth(ctx context.Context, uuid string, body *Basicauth) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/caddy/reverse_proxy/setBasicAuth/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"basicauth": body}, &resp)
	return &resp, err
}

// ReverseProxySetHandle calls POST /api/caddy/reverse_proxy/setHandle
// Parameters:
//   - uuid
func (c *Client) ReverseProxySetHandle(ctx context.Context, uuid string, body *Handle) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/caddy/reverse_proxy/setHandle/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"handle": body}, &resp)
	return &resp, err
}

// ReverseProxySetHeader calls POST /api/caddy/reverse_proxy/setHeader
// Parameters:
//   - uuid
func (c *Client) ReverseProxySetHeader(ctx context.Context, uuid string, body *Header) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/caddy/reverse_proxy/setHeader/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"header": body}, &resp)
	return &resp, err
}

// ReverseProxySetLayer4 calls POST /api/caddy/reverse_proxy/setLayer4
// Parameters:
//   - uuid
func (c *Client) ReverseProxySetLayer4(ctx context.Context, uuid string, body *Layer4) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/caddy/reverse_proxy/setLayer4/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"layer4": body}, &resp)
	return &resp, err
}

// ReverseProxySetLayer4Openvpn calls POST /api/caddy/reverse_proxy/setLayer4Openvpn
// Parameters:
//   - uuid
func (c *Client) ReverseProxySetLayer4Openvpn(ctx context.Context, uuid string, body *Layer4openvpn) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/caddy/reverse_proxy/setLayer4Openvpn/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"layer4openvpn": body}, &resp)
	return &resp, err
}

// ReverseProxySetReverseProxy calls POST /api/caddy/reverse_proxy/setReverseProxy
// Parameters:
//   - uuid
func (c *Client) ReverseProxySetReverseProxy(ctx context.Context, uuid string, body *Reverse) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/caddy/reverse_proxy/setReverseProxy/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"reverse": body}, &resp)
	return &resp, err
}

// ReverseProxySetSubdomain calls POST /api/caddy/reverse_proxy/setSubdomain
// Parameters:
//   - uuid
func (c *Client) ReverseProxySetSubdomain(ctx context.Context, uuid string, body *Subdomain) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/caddy/reverse_proxy/setSubdomain/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"subdomain": body}, &resp)
	return &resp, err
}

// ReverseProxyToggleHandle calls POST /api/caddy/reverse_proxy/toggleHandle
// Parameters:
//   - uuid
//   - enabled (optional, default: null)
func (c *Client) ReverseProxyToggleHandle(ctx context.Context, uuid string, opts ...string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/caddy/reverse_proxy/toggleHandle/%s", uuid)
	for _, o := range opts {
		path += "/" + o
	}
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// ReverseProxyToggleLayer4 calls POST /api/caddy/reverse_proxy/toggleLayer4
// Parameters:
//   - uuid
//   - enabled (optional, default: null)
func (c *Client) ReverseProxyToggleLayer4(ctx context.Context, uuid string, opts ...string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/caddy/reverse_proxy/toggleLayer4/%s", uuid)
	for _, o := range opts {
		path += "/" + o
	}
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// ReverseProxyToggleLayer4Openvpn calls POST /api/caddy/reverse_proxy/toggleLayer4Openvpn
// Parameters:
//   - uuid
//   - enabled (optional, default: null)
func (c *Client) ReverseProxyToggleLayer4Openvpn(ctx context.Context, uuid string, opts ...string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/caddy/reverse_proxy/toggleLayer4Openvpn/%s", uuid)
	for _, o := range opts {
		path += "/" + o
	}
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// ReverseProxyToggleReverseProxy calls POST /api/caddy/reverse_proxy/toggleReverseProxy
// Parameters:
//   - uuid
//   - enabled (optional, default: null)
func (c *Client) ReverseProxyToggleReverseProxy(ctx context.Context, uuid string, opts ...string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/caddy/reverse_proxy/toggleReverseProxy/%s", uuid)
	for _, o := range opts {
		path += "/" + o
	}
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// ReverseProxyToggleSubdomain calls POST /api/caddy/reverse_proxy/toggleSubdomain
// Parameters:
//   - uuid
//   - enabled (optional, default: null)
func (c *Client) ReverseProxyToggleSubdomain(ctx context.Context, uuid string, opts ...string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/caddy/reverse_proxy/toggleSubdomain/%s", uuid)
	for _, o := range opts {
		path += "/" + o
	}
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// ServiceReconfigure calls POST /api/caddy/service/reconfigure
func (c *Client) ServiceReconfigure(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/caddy/service/reconfigure"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// ServiceRestart calls POST /api/caddy/service/restart
func (c *Client) ServiceRestart(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/caddy/service/restart"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// ServiceStart calls POST /api/caddy/service/start
func (c *Client) ServiceStart(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/caddy/service/start"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// ServiceStatus calls GET /api/caddy/service/status
func (c *Client) ServiceStatus(ctx context.Context) (map[string]any, error) {
	path := "/api/caddy/service/status"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// ServiceStop calls POST /api/caddy/service/stop
func (c *Client) ServiceStop(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/caddy/service/stop"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// ServiceValidate calls GET /api/caddy/service/validate
func (c *Client) ServiceValidate(ctx context.Context) (map[string]any, error) {
	path := "/api/caddy/service/validate"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}
