// Code generated by opnsense-cli/generate; DO NOT EDIT.

package caddy

import "github.com/jontk/opnsense-cli/opnsense"

// General represents a general model item.
type General struct {
	Enabled                        opnsense.OPNBool  `json:"enabled"`
	EnableLayer4                   *opnsense.OPNBool `json:"EnableLayer4,omitempty"`
	HttpPort                       string            `json:"HttpPort,omitempty"`
	HttpsPort                      string            `json:"HttpsPort,omitempty"`
	TlsEmail                       string            `json:"TlsEmail,omitempty"`
	TlsAutoHttps                   string            `json:"TlsAutoHttps,omitempty"`   // Valid values: off, disable_redirects, disable_certs, ignore_loaded_certs
	TlsDnsProvider                 string            `json:"TlsDnsProvider,omitempty"` // Valid values: cloudflare
	TlsDnsApiKey                   string            `json:"TlsDnsApiKey,omitempty"`
	TlsDnsPropagationTimeout       *opnsense.OPNBool `json:"TlsDnsPropagationTimeout,omitempty"`
	TlsDnsPropagationTimeoutPeriod *opnsense.OPNInt  `json:"TlsDnsPropagationTimeoutPeriod,omitempty"`
	TlsDnsPropagationDelay         *opnsense.OPNInt  `json:"TlsDnsPropagationDelay,omitempty"`
	TlsDnsPropagationResolvers     string            `json:"TlsDnsPropagationResolvers,omitempty"`
	TlsDnsEchDomain                string            `json:"TlsDnsEchDomain,omitempty"`
	Accesslist                     string            `json:"accesslist,omitempty"`
	ClientIpHeaders                string            `json:"ClientIpHeaders,omitempty"`
	DisableSuperuser               string            `json:"DisableSuperuser"` // Valid values: root, www
	GracePeriod                    opnsense.OPNInt   `json:"GracePeriod"`
	HttpVersions                   string            `json:"HttpVersions"` // Valid values: h1, h2, h3
	TimeoutReadBody                *opnsense.OPNInt  `json:"timeout_read_body,omitempty"`
	TimeoutReadHeader              *opnsense.OPNInt  `json:"timeout_read_header,omitempty"`
	TimeoutWrite                   *opnsense.OPNInt  `json:"timeout_write,omitempty"`
	TimeoutIdle                    *opnsense.OPNInt  `json:"timeout_idle,omitempty"`
	LogCredentials                 *opnsense.OPNBool `json:"LogCredentials,omitempty"`
	LogAccessPlain                 *opnsense.OPNBool `json:"LogAccessPlain,omitempty"`
	LogAccessPlainKeep             opnsense.OPNInt   `json:"LogAccessPlainKeep"`
	LogLevel                       string            `json:"LogLevel,omitempty"` // Valid values: DEBUG, WARN, ERROR, PANIC, FATAL
	DynDnsSimpleHttp               string            `json:"DynDnsSimpleHttp,omitempty"`
	DynDnsInterface                string            `json:"DynDnsInterface,omitempty"`
	DynDnsInterval                 *opnsense.OPNInt  `json:"DynDnsInterval,omitempty"`
	DynDnsIpVersions               string            `json:"DynDnsIpVersions,omitempty"` // Valid values: ipv4, ipv6
	DynDnsTtl                      *opnsense.OPNInt  `json:"DynDnsTtl,omitempty"`
	DynDnsUpdateOnly               *opnsense.OPNBool `json:"DynDnsUpdateOnly,omitempty"`
	AuthProvider                   string            `json:"AuthProvider,omitempty"` // Valid values: authelia, authentik
	AuthToDomain                   string            `json:"AuthToDomain,omitempty"`
	AuthToPort                     string            `json:"AuthToPort,omitempty"`
	AuthToTls                      string            `json:"AuthToTls"` // Valid values: http, https
	AuthToUri                      string            `json:"AuthToUri,omitempty"`
	CopyHeaders                    string            `json:"CopyHeaders,omitempty"`
}

// Reverse represents a reverse model item.
type Reverse struct {
	Enabled                    opnsense.OPNBool  `json:"enabled"`
	FromDomain                 string            `json:"FromDomain"`
	FromPort                   string            `json:"FromPort,omitempty"`
	Accesslist                 string            `json:"accesslist,omitempty"`
	Basicauth                  string            `json:"basicauth,omitempty"`
	Description                string            `json:"description,omitempty"`
	DnsChallenge               *opnsense.OPNBool `json:"DnsChallenge,omitempty"`
	DnsChallengeOverrideDomain string            `json:"DnsChallengeOverrideDomain,omitempty"`
	CustomCertificate          string            `json:"CustomCertificate,omitempty"`
	AccessLog                  *opnsense.OPNBool `json:"AccessLog,omitempty"`
	DynDns                     *opnsense.OPNBool `json:"DynDns,omitempty"`
	AcmePassthrough            string            `json:"AcmePassthrough,omitempty"`
	DisableTls                 string            `json:"DisableTls"`               // Valid values: https, http
	ClientAuthMode             string            `json:"ClientAuthMode,omitempty"` // Valid values: request, require, verify_if_given
	ClientAuthTrustPool        string            `json:"ClientAuthTrustPool,omitempty"`
}

// Subdomain represents a subdomain model item.
type Subdomain struct {
	Enabled             opnsense.OPNBool  `json:"enabled"`
	Reverse             string            `json:"reverse"`
	FromDomain          string            `json:"FromDomain"`
	Accesslist          string            `json:"accesslist,omitempty"`
	Basicauth           string            `json:"basicauth,omitempty"`
	Description         string            `json:"description,omitempty"`
	DynDns              *opnsense.OPNBool `json:"DynDns,omitempty"`
	AcmePassthrough     string            `json:"AcmePassthrough,omitempty"`
	ClientAuthMode      string            `json:"ClientAuthMode,omitempty"` // Valid values: request, require, verify_if_given
	ClientAuthTrustPool string            `json:"ClientAuthTrustPool,omitempty"`
}

// Handle represents a handle model item.
type Handle struct {
	Enabled                            opnsense.OPNBool  `json:"enabled"`
	Reverse                            string            `json:"reverse"`
	Subdomain                          string            `json:"subdomain,omitempty"`
	HandleType                         string            `json:"HandleType"` // Valid values: handle, handle_path
	HandlePath                         string            `json:"HandlePath,omitempty"`
	Accesslist                         string            `json:"accesslist,omitempty"`
	Basicauth                          string            `json:"basicauth,omitempty"`
	Header                             string            `json:"header,omitempty"`
	HandleDirective                    string            `json:"HandleDirective"` // Valid values: reverse_proxy, redir
	ToDomain                           string            `json:"ToDomain"`
	ToPort                             string            `json:"ToPort,omitempty"`
	ToPath                             string            `json:"ToPath,omitempty"`
	ForwardAuth                        *opnsense.OPNBool `json:"ForwardAuth,omitempty"`
	HttpTls                            string            `json:"HttpTls"`               // Valid values: http, https, h2c
	HttpVersion                        string            `json:"HttpVersion,omitempty"` // Valid values: http1, http2, http3
	HttpKeepalive                      *opnsense.OPNInt  `json:"HttpKeepalive,omitempty"`
	HttpNtlm                           *opnsense.OPNBool `json:"HttpNtlm,omitempty"`
	HttpTlsInsecureSkipVerify          *opnsense.OPNBool `json:"HttpTlsInsecureSkipVerify,omitempty"`
	HttpTlsTrustedCaCerts              string            `json:"HttpTlsTrustedCaCerts,omitempty"`
	HttpTlsServerName                  string            `json:"HttpTlsServerName,omitempty"`
	LbPolicy                           string            `json:"lb_policy,omitempty"` // Valid values: first, round_robin, least_conn, ip_hash, client_ip_hash, uri_hash
	LbRetries                          *opnsense.OPNInt  `json:"lb_retries,omitempty"`
	LbTryDuration                      *opnsense.OPNInt  `json:"lb_try_duration,omitempty"`
	LbTryInterval                      *opnsense.OPNInt  `json:"lb_try_interval,omitempty"`
	PassiveHealthFailDuration          *opnsense.OPNInt  `json:"PassiveHealthFailDuration,omitempty"`
	PassiveHealthMaxFails              *opnsense.OPNInt  `json:"PassiveHealthMaxFails,omitempty"`
	PassiveHealthUnhealthyStatus       string            `json:"PassiveHealthUnhealthyStatus,omitempty"`
	PassiveHealthUnhealthyLatency      *opnsense.OPNInt  `json:"PassiveHealthUnhealthyLatency,omitempty"`
	PassiveHealthUnhealthyRequestCount *opnsense.OPNInt  `json:"PassiveHealthUnhealthyRequestCount,omitempty"`
	Description                        string            `json:"description,omitempty"`
	HealthUri                          string            `json:"health_uri,omitempty"`
	HealthUpstream                     string            `json:"health_upstream,omitempty"`
	HealthPort                         *opnsense.OPNInt  `json:"health_port,omitempty"`
	HealthInterval                     *opnsense.OPNInt  `json:"health_interval,omitempty"`
	HealthPasses                       *opnsense.OPNInt  `json:"health_passes,omitempty"`
	HealthFails                        *opnsense.OPNInt  `json:"health_fails,omitempty"`
	HealthTimeout                      *opnsense.OPNInt  `json:"health_timeout,omitempty"`
	HealthStatus                       string            `json:"health_status,omitempty"`
	HealthBody                         string            `json:"health_body,omitempty"`
	HealthFollowRedirects              *opnsense.OPNBool `json:"health_follow_redirects,omitempty"`
}

// Accesslist represents a accesslist model item.
type Accesslist struct {
	AccesslistName      string            `json:"accesslistName"`
	ClientIps           string            `json:"clientIps"`
	AccesslistInvert    *opnsense.OPNBool `json:"accesslistInvert,omitempty"`
	HttpResponseCode    *opnsense.OPNInt  `json:"HttpResponseCode,omitempty"`
	HttpResponseMessage string            `json:"HttpResponseMessage,omitempty"`
	RequestMatcher      string            `json:"RequestMatcher"` // Valid values: client_ip, remote_ip
	Description         string            `json:"description,omitempty"`
}

// Basicauth represents a basicauth model item.
type Basicauth struct {
	Basicauthuser string `json:"basicauthuser"`
	Basicauthpass string `json:"basicauthpass"`
	Description   string `json:"description,omitempty"`
}

// Header represents a header model item.
type Header struct {
	HeaderUpDown  string `json:"HeaderUpDown"` // Valid values: header_up, header_down
	HeaderType    string `json:"HeaderType"`
	HeaderValue   string `json:"HeaderValue,omitempty"`
	HeaderReplace string `json:"HeaderReplace,omitempty"`
	Description   string `json:"description,omitempty"`
}

// Layer4 represents a layer4 model item.
type Layer4 struct {
	Enabled                   opnsense.OPNBool  `json:"enabled"`
	Sequence                  string            `json:"Sequence,omitempty"`
	Type                      string            `json:"Type"`     // Valid values: listener_wrappers, global
	Protocol                  string            `json:"Protocol"` // Valid values: tcp, udp
	FromPort                  string            `json:"FromPort,omitempty"`
	FromDomain                string            `json:"FromDomain,omitempty"`
	FromOpenvpnModes          string            `json:"FromOpenvpnModes,omitempty"` // Valid values: auth_sha256_normal, auth_sha256_inverse, auth_sha512_normal, auth_sha512_inverse, crypt, crypt2_client, crypt2_server
	FromOpenvpnStaticKey      string            `json:"FromOpenvpnStaticKey,omitempty"`
	Matchers                  string            `json:"Matchers"` // Valid values: any, dns, http, httphost, openvpn, postgres, proxy_protocol, quic, quicsni, rdp, socks4, socks5, ssh, tls, tlssni, winbox, wireguard, xmpp
	InvertMatchers            *opnsense.OPNBool `json:"InvertMatchers,omitempty"`
	ToDomain                  string            `json:"ToDomain"`
	TerminateTls              *opnsense.OPNBool `json:"TerminateTls,omitempty"`
	ToPort                    string            `json:"ToPort"`
	ProxyProtocol             string            `json:"ProxyProtocol,omitempty"` // Valid values: v1, v2
	LbPolicy                  string            `json:"lb_policy,omitempty"`     // Valid values: first, round_robin, least_conn, ip_hash, client_ip_hash, uri_hash
	PassiveHealthFailDuration *opnsense.OPNInt  `json:"PassiveHealthFailDuration,omitempty"`
	PassiveHealthMaxFails     *opnsense.OPNInt  `json:"PassiveHealthMaxFails,omitempty"`
	RemoteIp                  string            `json:"RemoteIp,omitempty"`
	Description               string            `json:"description,omitempty"`
}

// Layer4openvpn represents a layer4openvpn model item.
type Layer4openvpn struct {
	StaticKey   string `json:"StaticKey"`
	Description string `json:"description"`
}

type accesslistGetItemResponse struct {
	Accesslist Accesslist `json:"accesslist"`
}

type basicauthGetItemResponse struct {
	Basicauth Basicauth `json:"basicauth"`
}

type handleGetItemResponse struct {
	Handle Handle `json:"handle"`
}

type headerGetItemResponse struct {
	Header Header `json:"header"`
}

type layer4GetItemResponse struct {
	Layer4 Layer4 `json:"layer4"`
}

type layer4openvpnGetItemResponse struct {
	Layer4openvpn Layer4openvpn `json:"layer4openvpn"`
}

type reverseGetItemResponse struct {
	Reverse Reverse `json:"reverse"`
}

type subdomainGetItemResponse struct {
	Subdomain Subdomain `json:"subdomain"`
}
