// Code generated by opnsense-cli/generate; DO NOT EDIT.

package syslog

import (
	"context"
	"fmt"

	"github.com/jontk/opnsense-cli/opnsense"
)

// Client wraps the base OPNsense client for syslog API calls.
type Client struct {
	client *opnsense.Client
}

// NewClient creates a new syslog API client.
func NewClient(c *opnsense.Client) *Client {
	return &Client{client: c}
}

// ServiceReconfigure calls POST /api/syslog/service/reconfigure
func (c *Client) ServiceReconfigure(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/syslog/service/reconfigure"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// ServiceReset calls POST /api/syslog/service/reset
func (c *Client) ServiceReset(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/syslog/service/reset"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// ServiceRestart calls POST /api/syslog/service/restart
func (c *Client) ServiceRestart(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/syslog/service/restart"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// ServiceStart calls POST /api/syslog/service/start
func (c *Client) ServiceStart(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/syslog/service/start"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// ServiceStats calls GET /api/syslog/service/stats
func (c *Client) ServiceStats(ctx context.Context) (map[string]any, error) {
	path := "/api/syslog/service/stats"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// ServiceStatus calls GET /api/syslog/service/status
func (c *Client) ServiceStatus(ctx context.Context) (map[string]any, error) {
	path := "/api/syslog/service/status"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// ServiceStop calls POST /api/syslog/service/stop
func (c *Client) ServiceStop(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/syslog/service/stop"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// SettingsAddDestination calls POST /api/syslog/settings/addDestination
func (c *Client) SettingsAddDestination(ctx context.Context, body *Destination) (*opnsense.GenericResponse, error) {
	path := "/api/syslog/settings/addDestination"
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"destination": body}, &resp)
	return &resp, err
}

// SettingsDelDestination calls POST /api/syslog/settings/delDestination
// Parameters:
//   - uuid
func (c *Client) SettingsDelDestination(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/syslog/settings/delDestination/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// SettingsGet calls GET /api/syslog/settings/get
func (c *Client) SettingsGet(ctx context.Context) (map[string]any, error) {
	path := "/api/syslog/settings/get"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// SettingsGetDestination calls GET /api/syslog/settings/getDestination
// Parameters:
//   - uuid (optional, default: null)
func (c *Client) SettingsGetDestination(ctx context.Context, opts ...string) (*Destination, error) {
	path := "/api/syslog/settings/getDestination"
	for _, o := range opts {
		path += "/" + o
	}
	var resp destinationGetItemResponse
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return &resp.Destination, err
}

// SettingsSearchDestinations calls GET,POST /api/syslog/settings/searchDestinations
func (c *Client) SettingsSearchDestinations(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/syslog/settings/searchDestinations"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// SettingsSet calls POST /api/syslog/settings/set
func (c *Client) SettingsSet(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/syslog/settings/set"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// SettingsSetDestination calls POST /api/syslog/settings/setDestination
// Parameters:
//   - uuid
func (c *Client) SettingsSetDestination(ctx context.Context, uuid string, body *Destination) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/syslog/settings/setDestination/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"destination": body}, &resp)
	return &resp, err
}

// SettingsToggleDestination calls POST /api/syslog/settings/toggleDestination
// Parameters:
//   - uuid
//   - enabled (optional, default: null)
func (c *Client) SettingsToggleDestination(ctx context.Context, uuid string, opts ...string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/syslog/settings/toggleDestination/%s", uuid)
	for _, o := range opts {
		path += "/" + o
	}
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}
