// Code generated by opnsense-cli/generate; DO NOT EDIT.

// Package tayga provides a client for the OPNsense tayga API.
package tayga

import (
	"context"
	"fmt"

	"github.com/jontk/opnsense-cli/opnsense"
)

// Client wraps the base OPNsense client for tayga API calls.
type Client struct {
	client *opnsense.Client
}

// NewClient creates a new tayga API client.
func NewClient(c *opnsense.Client) *Client {
	return &Client{client: c}
}

// GeneralGet calls GET /api/tayga/general/get
func (c *Client) GeneralGet(ctx context.Context) (map[string]any, error) {
	path := "/api/tayga/general/get"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// GeneralSet calls POST /api/tayga/general/set
func (c *Client) GeneralSet(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/tayga/general/set"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// MappingAddStaticmapping calls POST /api/tayga/mapping/addStaticmapping
func (c *Client) MappingAddStaticmapping(ctx context.Context, body *Staticmapping) (*opnsense.GenericResponse, error) {
	path := "/api/tayga/mapping/addStaticmapping"
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"staticmapping": body}, &resp)
	return &resp, err
}

// MappingDelStaticmapping calls POST /api/tayga/mapping/delStaticmapping
// Parameters:
//   - uuid
func (c *Client) MappingDelStaticmapping(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/tayga/mapping/delStaticmapping/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// MappingGet calls GET /api/tayga/mapping/get
func (c *Client) MappingGet(ctx context.Context) (map[string]any, error) {
	path := "/api/tayga/mapping/get"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// MappingGetStaticmapping calls GET /api/tayga/mapping/getStaticmapping
// Parameters:
//   - uuid (optional, default: null)
func (c *Client) MappingGetStaticmapping(ctx context.Context, opts ...string) (*Staticmapping, error) {
	path := "/api/tayga/mapping/getStaticmapping"
	for _, o := range opts {
		path += "/" + o
	}
	var resp staticmappingGetItemResponse
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return &resp.Staticmapping, err
}

// MappingSearchStaticmapping calls GET,POST /api/tayga/mapping/searchStaticmapping
func (c *Client) MappingSearchStaticmapping(ctx context.Context, body any) (*opnsense.SearchResult[Staticmapping], error) {
	path := "/api/tayga/mapping/searchStaticmapping"
	var resp opnsense.SearchResult[Staticmapping]
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return &resp, err
}

// MappingSet calls POST /api/tayga/mapping/set
func (c *Client) MappingSet(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/tayga/mapping/set"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// MappingSetStaticmapping calls POST /api/tayga/mapping/setStaticmapping
// Parameters:
//   - uuid
func (c *Client) MappingSetStaticmapping(ctx context.Context, uuid string, body *Staticmapping) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/tayga/mapping/setStaticmapping/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"staticmapping": body}, &resp)
	return &resp, err
}

// MappingToggleStaticmapping calls POST /api/tayga/mapping/toggleStaticmapping
// Parameters:
//   - uuid
func (c *Client) MappingToggleStaticmapping(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/tayga/mapping/toggleStaticmapping/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// ServiceReconfigure calls POST /api/tayga/service/reconfigure
func (c *Client) ServiceReconfigure(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/tayga/service/reconfigure"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// ServiceRestart calls POST /api/tayga/service/restart
func (c *Client) ServiceRestart(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/tayga/service/restart"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// ServiceStart calls POST /api/tayga/service/start
func (c *Client) ServiceStart(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/tayga/service/start"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// ServiceStatus calls GET /api/tayga/service/status
func (c *Client) ServiceStatus(ctx context.Context) (map[string]any, error) {
	path := "/api/tayga/service/status"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// ServiceStop calls POST /api/tayga/service/stop
func (c *Client) ServiceStop(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/tayga/service/stop"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}
