// Code generated by opnsense-cli/generate; DO NOT EDIT.

// Package firewall provides a client for the OPNsense firewall API.
package firewall

import (
	"context"
	"fmt"

	"github.com/jontk/opnsense-cli/opnsense"
)

// Client wraps the base OPNsense client for firewall API calls.
type Client struct {
	client *opnsense.Client
}

// NewClient creates a new firewall API client.
func NewClient(c *opnsense.Client) *Client {
	return &Client{client: c}
}

// AliasAddItem calls POST /api/firewall/alias/addItem
func (c *Client) AliasAddItem(ctx context.Context, body *Alias) (*opnsense.GenericResponse, error) {
	path := "/api/firewall/alias/addItem"
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"alias": body}, &resp)
	return &resp, err
}

// AliasDelItem calls POST /api/firewall/alias/delItem
// Parameters:
//   - uuid
func (c *Client) AliasDelItem(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/firewall/alias/delItem/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// AliasExport calls GET,POST /api/firewall/alias/export
func (c *Client) AliasExport(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/firewall/alias/export"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// AliasGet calls GET /api/firewall/alias/get
func (c *Client) AliasGet(ctx context.Context) (map[string]any, error) {
	path := "/api/firewall/alias/get"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// AliasGetAliasUUID calls GET /api/firewall/alias/getAliasUUID
// Parameters:
//   - name
func (c *Client) AliasGetAliasUUID(ctx context.Context, name string) (*Alias, error) {
	path := fmt.Sprintf("/api/firewall/alias/getAliasUUID/%s", name)
	var resp aliasGetItemResponse
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return &resp.Alias, err
}

// AliasGetGeoIP calls GET /api/firewall/alias/getGeoIP
func (c *Client) AliasGetGeoIP(ctx context.Context) (*Geoip, error) {
	path := "/api/firewall/alias/getGeoIP"
	var resp geoipGetItemResponse
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return &resp.Geoip, err
}

// AliasGetItem calls GET /api/firewall/alias/getItem
// Parameters:
//   - uuid (optional, default: null)
func (c *Client) AliasGetItem(ctx context.Context, opts ...string) (*Alias, error) {
	path := "/api/firewall/alias/getItem"
	for _, o := range opts {
		path += "/" + o
	}
	var resp aliasGetItemResponse
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return &resp.Alias, err
}

// AliasGetTableSize calls GET /api/firewall/alias/getTableSize
func (c *Client) AliasGetTableSize(ctx context.Context) (map[string]any, error) {
	path := "/api/firewall/alias/getTableSize"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// AliasImport calls POST /api/firewall/alias/import
func (c *Client) AliasImport(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/firewall/alias/import"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// AliasListCategories calls GET /api/firewall/alias/listCategories
func (c *Client) AliasListCategories(ctx context.Context) (map[string]any, error) {
	path := "/api/firewall/alias/listCategories"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// AliasListCountries calls GET /api/firewall/alias/listCountries
func (c *Client) AliasListCountries(ctx context.Context) (map[string]any, error) {
	path := "/api/firewall/alias/listCountries"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// AliasListNetworkAliases calls GET /api/firewall/alias/listNetworkAliases
func (c *Client) AliasListNetworkAliases(ctx context.Context) (map[string]any, error) {
	path := "/api/firewall/alias/listNetworkAliases"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// AliasListUserGroups calls GET /api/firewall/alias/listUserGroups
func (c *Client) AliasListUserGroups(ctx context.Context) (map[string]any, error) {
	path := "/api/firewall/alias/listUserGroups"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// AliasReconfigure calls POST /api/firewall/alias/reconfigure
func (c *Client) AliasReconfigure(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/firewall/alias/reconfigure"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// AliasSearchItem calls GET,POST /api/firewall/alias/searchItem
func (c *Client) AliasSearchItem(ctx context.Context, body any) (*opnsense.SearchResult[Alias], error) {
	path := "/api/firewall/alias/searchItem"
	var resp opnsense.SearchResult[Alias]
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return &resp, err
}

// AliasSet calls POST /api/firewall/alias/set
func (c *Client) AliasSet(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/firewall/alias/set"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// AliasSetItem calls POST /api/firewall/alias/setItem
// Parameters:
//   - uuid
func (c *Client) AliasSetItem(ctx context.Context, uuid string, body *Alias) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/firewall/alias/setItem/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"alias": body}, &resp)
	return &resp, err
}

// AliasToggleItem calls POST /api/firewall/alias/toggleItem
// Parameters:
//   - uuid
//   - enabled (optional, default: null)
func (c *Client) AliasToggleItem(ctx context.Context, uuid string, opts ...string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/firewall/alias/toggleItem/%s", uuid)
	for _, o := range opts {
		path += "/" + o
	}
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// AliasUtilAdd calls POST /api/firewall/alias_util/add
// Parameters:
//   - alias
func (c *Client) AliasUtilAdd(ctx context.Context, alias string, body any) (map[string]any, error) {
	path := fmt.Sprintf("/api/firewall/alias_util/add/%s", alias)
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// AliasUtilAliases calls GET /api/firewall/alias_util/aliases
func (c *Client) AliasUtilAliases(ctx context.Context) (map[string]any, error) {
	path := "/api/firewall/alias_util/aliases"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// AliasUtilDelete calls POST /api/firewall/alias_util/delete
// Parameters:
//   - alias
func (c *Client) AliasUtilDelete(ctx context.Context, alias string, body any) (map[string]any, error) {
	path := fmt.Sprintf("/api/firewall/alias_util/delete/%s", alias)
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// AliasUtilFindReferences calls POST /api/firewall/alias_util/findReferences
func (c *Client) AliasUtilFindReferences(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/firewall/alias_util/findReferences"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// AliasUtilFlush calls POST /api/firewall/alias_util/flush
// Parameters:
//   - alias
func (c *Client) AliasUtilFlush(ctx context.Context, alias string, body any) (map[string]any, error) {
	path := fmt.Sprintf("/api/firewall/alias_util/flush/%s", alias)
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// AliasUtilList calls GET /api/firewall/alias_util/list
// Parameters:
//   - alias
func (c *Client) AliasUtilList(ctx context.Context, alias string) (map[string]any, error) {
	path := fmt.Sprintf("/api/firewall/alias_util/list/%s", alias)
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// AliasUtilUpdateBogons calls GET /api/firewall/alias_util/updateBogons
func (c *Client) AliasUtilUpdateBogons(ctx context.Context) (map[string]any, error) {
	path := "/api/firewall/alias_util/updateBogons"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// CategoryAddItem calls POST /api/firewall/category/addItem
func (c *Client) CategoryAddItem(ctx context.Context, body *Category) (*opnsense.GenericResponse, error) {
	path := "/api/firewall/category/addItem"
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"category": body}, &resp)
	return &resp, err
}

// CategoryDelItem calls POST /api/firewall/category/delItem
// Parameters:
//   - uuid
func (c *Client) CategoryDelItem(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/firewall/category/delItem/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// CategoryGet calls GET /api/firewall/category/get
func (c *Client) CategoryGet(ctx context.Context) (map[string]any, error) {
	path := "/api/firewall/category/get"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// CategoryGetItem calls GET /api/firewall/category/getItem
// Parameters:
//   - uuid (optional, default: null)
func (c *Client) CategoryGetItem(ctx context.Context, opts ...string) (*Category, error) {
	path := "/api/firewall/category/getItem"
	for _, o := range opts {
		path += "/" + o
	}
	var resp categoryGetItemResponse
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return &resp.Category, err
}

// CategorySearchItem calls GET,POST /api/firewall/category/searchItem
// Parameters:
//   - add_empty (optional, default: 0)
func (c *Client) CategorySearchItem(ctx context.Context, body any, opts ...string) (*opnsense.SearchResult[Category], error) {
	path := "/api/firewall/category/searchItem"
	for _, o := range opts {
		path += "/" + o
	}
	var resp opnsense.SearchResult[Category]
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return &resp, err
}

// CategorySet calls POST /api/firewall/category/set
func (c *Client) CategorySet(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/firewall/category/set"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// CategorySetItem calls POST /api/firewall/category/setItem
// Parameters:
//   - uuid
func (c *Client) CategorySetItem(ctx context.Context, uuid string, body *Category) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/firewall/category/setItem/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"category": body}, &resp)
	return &resp, err
}

// DNatAddRule calls POST /api/firewall/d_nat/addRule
func (c *Client) DNatAddRule(ctx context.Context, body *Source) (*opnsense.GenericResponse, error) {
	path := "/api/firewall/d_nat/addRule"
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"source": body}, &resp)
	return &resp, err
}

// DNatDelRule calls POST /api/firewall/d_nat/delRule
// Parameters:
//   - uuid
func (c *Client) DNatDelRule(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/firewall/d_nat/delRule/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// DNatGetRule calls GET /api/firewall/d_nat/getRule
// Parameters:
//   - uuid (optional, default: null)
func (c *Client) DNatGetRule(ctx context.Context, opts ...string) (*Source, error) {
	path := "/api/firewall/d_nat/getRule"
	for _, o := range opts {
		path += "/" + o
	}
	var resp sourceGetItemResponse
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return &resp.Source, err
}

// DNatMoveRuleBefore calls GET /api/firewall/d_nat/moveRuleBefore
// Parameters:
//   - selected_uuid
//   - target_uuid
func (c *Client) DNatMoveRuleBefore(ctx context.Context, selected_uuid string, target_uuid string) (map[string]any, error) {
	path := fmt.Sprintf("/api/firewall/d_nat/moveRuleBefore/%s/%s", selected_uuid, target_uuid)
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// DNatSearchRule calls GET,POST /api/firewall/d_nat/searchRule
func (c *Client) DNatSearchRule(ctx context.Context, body any) (*opnsense.SearchResult[Source], error) {
	path := "/api/firewall/d_nat/searchRule"
	var resp opnsense.SearchResult[Source]
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return &resp, err
}

// DNatSetRule calls POST /api/firewall/d_nat/setRule
// Parameters:
//   - uuid
func (c *Client) DNatSetRule(ctx context.Context, uuid string, body *Source) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/firewall/d_nat/setRule/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"source": body}, &resp)
	return &resp, err
}

// DNatToggleRule calls POST /api/firewall/d_nat/toggleRule
// Parameters:
//   - uuid
//   - disabled (optional, default: null)
func (c *Client) DNatToggleRule(ctx context.Context, uuid string, opts ...string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/firewall/d_nat/toggleRule/%s", uuid)
	for _, o := range opts {
		path += "/" + o
	}
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// DNatToggleRuleLog calls GET /api/firewall/d_nat/toggleRuleLog
// Parameters:
//   - uuid
//   - log
func (c *Client) DNatToggleRuleLog(ctx context.Context, uuid string, log string) (map[string]any, error) {
	path := fmt.Sprintf("/api/firewall/d_nat/toggleRuleLog/%s/%s", uuid, log)
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// DNatApply calls POST /api/firewall/d_nat/apply
// Parameters:
//   - rollback_revision (optional, default: null)
func (c *Client) DNatApply(ctx context.Context, body any, opts ...string) (map[string]any, error) {
	path := "/api/firewall/d_nat/apply"
	for _, o := range opts {
		path += "/" + o
	}
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// DNatCancelRollback calls POST /api/firewall/d_nat/cancelRollback
// Parameters:
//   - rollback_revision
func (c *Client) DNatCancelRollback(ctx context.Context, rollback_revision string, body any) (map[string]any, error) {
	path := fmt.Sprintf("/api/firewall/d_nat/cancelRollback/%s", rollback_revision)
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// DNatGet calls GET /api/firewall/d_nat/get
func (c *Client) DNatGet(ctx context.Context) (map[string]any, error) {
	path := "/api/firewall/d_nat/get"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// DNatListCategories calls GET /api/firewall/d_nat/listCategories
func (c *Client) DNatListCategories(ctx context.Context) (map[string]any, error) {
	path := "/api/firewall/d_nat/listCategories"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// DNatListNetworkSelectOptions calls GET /api/firewall/d_nat/listNetworkSelectOptions
func (c *Client) DNatListNetworkSelectOptions(ctx context.Context) (map[string]any, error) {
	path := "/api/firewall/d_nat/listNetworkSelectOptions"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// DNatListPortSelectOptions calls GET /api/firewall/d_nat/listPortSelectOptions
func (c *Client) DNatListPortSelectOptions(ctx context.Context) (map[string]any, error) {
	path := "/api/firewall/d_nat/listPortSelectOptions"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// DNatRevert calls POST /api/firewall/d_nat/revert
// Parameters:
//   - revision
func (c *Client) DNatRevert(ctx context.Context, revision string, body any) (map[string]any, error) {
	path := fmt.Sprintf("/api/firewall/d_nat/revert/%s", revision)
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// DNatSavepoint calls POST /api/firewall/d_nat/savepoint
func (c *Client) DNatSavepoint(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/firewall/d_nat/savepoint"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// DNatSet calls POST /api/firewall/d_nat/set
func (c *Client) DNatSet(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/firewall/d_nat/set"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// FilterAddRule calls POST /api/firewall/filter/addRule
func (c *Client) FilterAddRule(ctx context.Context, body *Rule) (*opnsense.GenericResponse, error) {
	path := "/api/firewall/filter/addRule"
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"rule": body}, &resp)
	return &resp, err
}

// FilterDelRule calls POST /api/firewall/filter/delRule
// Parameters:
//   - uuid
func (c *Client) FilterDelRule(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/firewall/filter/delRule/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// FilterDownloadRules calls GET /api/firewall/filter/downloadRules
func (c *Client) FilterDownloadRules(ctx context.Context) (map[string]any, error) {
	path := "/api/firewall/filter/downloadRules"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// FilterFlushInspectCache calls POST /api/firewall/filter/flushInspectCache
func (c *Client) FilterFlushInspectCache(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/firewall/filter/flushInspectCache"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// FilterGetInterfaceList calls GET /api/firewall/filter/getInterfaceList
func (c *Client) FilterGetInterfaceList(ctx context.Context) (map[string]any, error) {
	path := "/api/firewall/filter/getInterfaceList"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// FilterGetRule calls GET /api/firewall/filter/getRule
// Parameters:
//   - uuid (optional, default: null)
func (c *Client) FilterGetRule(ctx context.Context, opts ...string) (*Rule, error) {
	path := "/api/firewall/filter/getRule"
	for _, o := range opts {
		path += "/" + o
	}
	var resp ruleGetItemResponse
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return &resp.Rule, err
}

// FilterMoveRuleBefore calls POST /api/firewall/filter/moveRuleBefore
// Parameters:
//   - selected_uuid
//   - target_uuid
func (c *Client) FilterMoveRuleBefore(ctx context.Context, selected_uuid string, target_uuid string, body any) (map[string]any, error) {
	path := fmt.Sprintf("/api/firewall/filter/moveRuleBefore/%s/%s", selected_uuid, target_uuid)
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// FilterSearchRule calls GET,POST /api/firewall/filter/searchRule
func (c *Client) FilterSearchRule(ctx context.Context, body any) (*opnsense.SearchResult[Rule], error) {
	path := "/api/firewall/filter/searchRule"
	var resp opnsense.SearchResult[Rule]
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return &resp, err
}

// FilterSetRule calls POST /api/firewall/filter/setRule
// Parameters:
//   - uuid
func (c *Client) FilterSetRule(ctx context.Context, uuid string, body *Rule) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/firewall/filter/setRule/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"rule": body}, &resp)
	return &resp, err
}

// FilterToggleRule calls POST /api/firewall/filter/toggleRule
// Parameters:
//   - uuid
//   - enabled (optional, default: null)
func (c *Client) FilterToggleRule(ctx context.Context, uuid string, opts ...string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/firewall/filter/toggleRule/%s", uuid)
	for _, o := range opts {
		path += "/" + o
	}
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// FilterToggleRuleLog calls GET /api/firewall/filter/toggleRuleLog
// Parameters:
//   - uuid
//   - log
func (c *Client) FilterToggleRuleLog(ctx context.Context, uuid string, log string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/firewall/filter/toggleRuleLog/%s/%s", uuid, log)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// FilterUploadRules calls POST /api/firewall/filter/uploadRules
func (c *Client) FilterUploadRules(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/firewall/filter/uploadRules"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// FilterApply calls POST /api/firewall/filter/apply
// Parameters:
//   - rollback_revision (optional, default: null)
func (c *Client) FilterApply(ctx context.Context, body any, opts ...string) (map[string]any, error) {
	path := "/api/firewall/filter/apply"
	for _, o := range opts {
		path += "/" + o
	}
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// FilterCancelRollback calls POST /api/firewall/filter/cancelRollback
// Parameters:
//   - rollback_revision
func (c *Client) FilterCancelRollback(ctx context.Context, rollback_revision string, body any) (map[string]any, error) {
	path := fmt.Sprintf("/api/firewall/filter/cancelRollback/%s", rollback_revision)
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// FilterGet calls GET /api/firewall/filter/get
func (c *Client) FilterGet(ctx context.Context) (map[string]any, error) {
	path := "/api/firewall/filter/get"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// FilterListCategories calls GET /api/firewall/filter/listCategories
func (c *Client) FilterListCategories(ctx context.Context) (map[string]any, error) {
	path := "/api/firewall/filter/listCategories"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// FilterListNetworkSelectOptions calls GET /api/firewall/filter/listNetworkSelectOptions
func (c *Client) FilterListNetworkSelectOptions(ctx context.Context) (map[string]any, error) {
	path := "/api/firewall/filter/listNetworkSelectOptions"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// FilterListPortSelectOptions calls GET /api/firewall/filter/listPortSelectOptions
func (c *Client) FilterListPortSelectOptions(ctx context.Context) (map[string]any, error) {
	path := "/api/firewall/filter/listPortSelectOptions"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// FilterRevert calls POST /api/firewall/filter/revert
// Parameters:
//   - revision
func (c *Client) FilterRevert(ctx context.Context, revision string, body any) (map[string]any, error) {
	path := fmt.Sprintf("/api/firewall/filter/revert/%s", revision)
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// FilterSavepoint calls POST /api/firewall/filter/savepoint
func (c *Client) FilterSavepoint(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/firewall/filter/savepoint"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// FilterSet calls POST /api/firewall/filter/set
func (c *Client) FilterSet(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/firewall/filter/set"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// FilterUtilRuleStats calls GET /api/firewall/filter_util/ruleStats
func (c *Client) FilterUtilRuleStats(ctx context.Context) (map[string]any, error) {
	path := "/api/firewall/filter_util/ruleStats"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// GroupAddItem calls POST /api/firewall/group/addItem
func (c *Client) GroupAddItem(ctx context.Context, body *Ifgroupentry) (*opnsense.GenericResponse, error) {
	path := "/api/firewall/group/addItem"
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"ifgroupentry": body}, &resp)
	return &resp, err
}

// GroupDelItem calls POST /api/firewall/group/delItem
// Parameters:
//   - uuid
func (c *Client) GroupDelItem(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/firewall/group/delItem/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// GroupGet calls GET /api/firewall/group/get
func (c *Client) GroupGet(ctx context.Context) (map[string]any, error) {
	path := "/api/firewall/group/get"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// GroupGetItem calls GET /api/firewall/group/getItem
// Parameters:
//   - uuid (optional, default: null)
func (c *Client) GroupGetItem(ctx context.Context, opts ...string) (*Ifgroupentry, error) {
	path := "/api/firewall/group/getItem"
	for _, o := range opts {
		path += "/" + o
	}
	var resp ifgroupentryGetItemResponse
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return &resp.Ifgroupentry, err
}

// GroupReconfigure calls POST /api/firewall/group/reconfigure
func (c *Client) GroupReconfigure(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/firewall/group/reconfigure"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// GroupSearchItem calls GET,POST /api/firewall/group/searchItem
func (c *Client) GroupSearchItem(ctx context.Context, body any) (*opnsense.SearchResult[Ifgroupentry], error) {
	path := "/api/firewall/group/searchItem"
	var resp opnsense.SearchResult[Ifgroupentry]
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return &resp, err
}

// GroupSet calls POST /api/firewall/group/set
func (c *Client) GroupSet(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/firewall/group/set"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// GroupSetItem calls POST /api/firewall/group/setItem
// Parameters:
//   - uuid
func (c *Client) GroupSetItem(ctx context.Context, uuid string, body *Ifgroupentry) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/firewall/group/setItem/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"ifgroupentry": body}, &resp)
	return &resp, err
}

// MigrationDownloadRules calls GET /api/firewall/migration/downloadRules
func (c *Client) MigrationDownloadRules(ctx context.Context) (map[string]any, error) {
	path := "/api/firewall/migration/downloadRules"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// MigrationFlush calls POST /api/firewall/migration/flush
func (c *Client) MigrationFlush(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/firewall/migration/flush"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// NptAddRule calls POST /api/firewall/npt/addRule
func (c *Client) NptAddRule(ctx context.Context, body *Rule) (*opnsense.GenericResponse, error) {
	path := "/api/firewall/npt/addRule"
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"rule": body}, &resp)
	return &resp, err
}

// NptDelRule calls POST /api/firewall/npt/delRule
// Parameters:
//   - uuid
func (c *Client) NptDelRule(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/firewall/npt/delRule/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// NptGetRule calls GET /api/firewall/npt/getRule
// Parameters:
//   - uuid (optional, default: null)
func (c *Client) NptGetRule(ctx context.Context, opts ...string) (*Rule, error) {
	path := "/api/firewall/npt/getRule"
	for _, o := range opts {
		path += "/" + o
	}
	var resp ruleGetItemResponse
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return &resp.Rule, err
}

// NptMoveRuleBefore calls GET /api/firewall/npt/moveRuleBefore
// Parameters:
//   - selected_uuid
//   - target_uuid
func (c *Client) NptMoveRuleBefore(ctx context.Context, selected_uuid string, target_uuid string) (map[string]any, error) {
	path := fmt.Sprintf("/api/firewall/npt/moveRuleBefore/%s/%s", selected_uuid, target_uuid)
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// NptSearchRule calls GET,POST /api/firewall/npt/searchRule
func (c *Client) NptSearchRule(ctx context.Context, body any) (*opnsense.SearchResult[Rule], error) {
	path := "/api/firewall/npt/searchRule"
	var resp opnsense.SearchResult[Rule]
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return &resp, err
}

// NptSetRule calls POST /api/firewall/npt/setRule
// Parameters:
//   - uuid
func (c *Client) NptSetRule(ctx context.Context, uuid string, body *Rule) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/firewall/npt/setRule/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"rule": body}, &resp)
	return &resp, err
}

// NptToggleRule calls POST /api/firewall/npt/toggleRule
// Parameters:
//   - uuid
//   - enabled (optional, default: null)
func (c *Client) NptToggleRule(ctx context.Context, uuid string, opts ...string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/firewall/npt/toggleRule/%s", uuid)
	for _, o := range opts {
		path += "/" + o
	}
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// NptToggleRuleLog calls GET /api/firewall/npt/toggleRuleLog
// Parameters:
//   - uuid
//   - log
func (c *Client) NptToggleRuleLog(ctx context.Context, uuid string, log string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/firewall/npt/toggleRuleLog/%s/%s", uuid, log)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// NptApply calls POST /api/firewall/npt/apply
// Parameters:
//   - rollback_revision (optional, default: null)
func (c *Client) NptApply(ctx context.Context, body any, opts ...string) (map[string]any, error) {
	path := "/api/firewall/npt/apply"
	for _, o := range opts {
		path += "/" + o
	}
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// NptCancelRollback calls POST /api/firewall/npt/cancelRollback
// Parameters:
//   - rollback_revision
func (c *Client) NptCancelRollback(ctx context.Context, rollback_revision string, body any) (map[string]any, error) {
	path := fmt.Sprintf("/api/firewall/npt/cancelRollback/%s", rollback_revision)
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// NptGet calls GET /api/firewall/npt/get
func (c *Client) NptGet(ctx context.Context) (map[string]any, error) {
	path := "/api/firewall/npt/get"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// NptListCategories calls GET /api/firewall/npt/listCategories
func (c *Client) NptListCategories(ctx context.Context) (map[string]any, error) {
	path := "/api/firewall/npt/listCategories"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// NptListNetworkSelectOptions calls GET /api/firewall/npt/listNetworkSelectOptions
func (c *Client) NptListNetworkSelectOptions(ctx context.Context) (map[string]any, error) {
	path := "/api/firewall/npt/listNetworkSelectOptions"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// NptListPortSelectOptions calls GET /api/firewall/npt/listPortSelectOptions
func (c *Client) NptListPortSelectOptions(ctx context.Context) (map[string]any, error) {
	path := "/api/firewall/npt/listPortSelectOptions"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// NptRevert calls POST /api/firewall/npt/revert
// Parameters:
//   - revision
func (c *Client) NptRevert(ctx context.Context, revision string, body any) (map[string]any, error) {
	path := fmt.Sprintf("/api/firewall/npt/revert/%s", revision)
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// NptSavepoint calls POST /api/firewall/npt/savepoint
func (c *Client) NptSavepoint(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/firewall/npt/savepoint"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// NptSet calls POST /api/firewall/npt/set
func (c *Client) NptSet(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/firewall/npt/set"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// OneToOneAddRule calls POST /api/firewall/one_to_one/addRule
func (c *Client) OneToOneAddRule(ctx context.Context, body *Rule) (*opnsense.GenericResponse, error) {
	path := "/api/firewall/one_to_one/addRule"
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"rule": body}, &resp)
	return &resp, err
}

// OneToOneDelRule calls POST /api/firewall/one_to_one/delRule
// Parameters:
//   - uuid
func (c *Client) OneToOneDelRule(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/firewall/one_to_one/delRule/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// OneToOneGetRule calls GET /api/firewall/one_to_one/getRule
// Parameters:
//   - uuid (optional, default: null)
func (c *Client) OneToOneGetRule(ctx context.Context, opts ...string) (*Rule, error) {
	path := "/api/firewall/one_to_one/getRule"
	for _, o := range opts {
		path += "/" + o
	}
	var resp ruleGetItemResponse
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return &resp.Rule, err
}

// OneToOneMoveRuleBefore calls GET /api/firewall/one_to_one/moveRuleBefore
// Parameters:
//   - selected_uuid
//   - target_uuid
func (c *Client) OneToOneMoveRuleBefore(ctx context.Context, selected_uuid string, target_uuid string) (map[string]any, error) {
	path := fmt.Sprintf("/api/firewall/one_to_one/moveRuleBefore/%s/%s", selected_uuid, target_uuid)
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// OneToOneSearchRule calls GET,POST /api/firewall/one_to_one/searchRule
func (c *Client) OneToOneSearchRule(ctx context.Context, body any) (*opnsense.SearchResult[Rule], error) {
	path := "/api/firewall/one_to_one/searchRule"
	var resp opnsense.SearchResult[Rule]
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return &resp, err
}

// OneToOneSetRule calls POST /api/firewall/one_to_one/setRule
// Parameters:
//   - uuid
func (c *Client) OneToOneSetRule(ctx context.Context, uuid string, body *Rule) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/firewall/one_to_one/setRule/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"rule": body}, &resp)
	return &resp, err
}

// OneToOneToggleRule calls POST /api/firewall/one_to_one/toggleRule
// Parameters:
//   - uuid
//   - enabled (optional, default: null)
func (c *Client) OneToOneToggleRule(ctx context.Context, uuid string, opts ...string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/firewall/one_to_one/toggleRule/%s", uuid)
	for _, o := range opts {
		path += "/" + o
	}
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// OneToOneToggleRuleLog calls GET /api/firewall/one_to_one/toggleRuleLog
// Parameters:
//   - uuid
//   - log
func (c *Client) OneToOneToggleRuleLog(ctx context.Context, uuid string, log string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/firewall/one_to_one/toggleRuleLog/%s/%s", uuid, log)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// OneToOneApply calls POST /api/firewall/one_to_one/apply
// Parameters:
//   - rollback_revision (optional, default: null)
func (c *Client) OneToOneApply(ctx context.Context, body any, opts ...string) (map[string]any, error) {
	path := "/api/firewall/one_to_one/apply"
	for _, o := range opts {
		path += "/" + o
	}
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// OneToOneCancelRollback calls POST /api/firewall/one_to_one/cancelRollback
// Parameters:
//   - rollback_revision
func (c *Client) OneToOneCancelRollback(ctx context.Context, rollback_revision string, body any) (map[string]any, error) {
	path := fmt.Sprintf("/api/firewall/one_to_one/cancelRollback/%s", rollback_revision)
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// OneToOneGet calls GET /api/firewall/one_to_one/get
func (c *Client) OneToOneGet(ctx context.Context) (map[string]any, error) {
	path := "/api/firewall/one_to_one/get"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// OneToOneListCategories calls GET /api/firewall/one_to_one/listCategories
func (c *Client) OneToOneListCategories(ctx context.Context) (map[string]any, error) {
	path := "/api/firewall/one_to_one/listCategories"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// OneToOneListNetworkSelectOptions calls GET /api/firewall/one_to_one/listNetworkSelectOptions
func (c *Client) OneToOneListNetworkSelectOptions(ctx context.Context) (map[string]any, error) {
	path := "/api/firewall/one_to_one/listNetworkSelectOptions"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// OneToOneListPortSelectOptions calls GET /api/firewall/one_to_one/listPortSelectOptions
func (c *Client) OneToOneListPortSelectOptions(ctx context.Context) (map[string]any, error) {
	path := "/api/firewall/one_to_one/listPortSelectOptions"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// OneToOneRevert calls POST /api/firewall/one_to_one/revert
// Parameters:
//   - revision
func (c *Client) OneToOneRevert(ctx context.Context, revision string, body any) (map[string]any, error) {
	path := fmt.Sprintf("/api/firewall/one_to_one/revert/%s", revision)
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// OneToOneSavepoint calls POST /api/firewall/one_to_one/savepoint
func (c *Client) OneToOneSavepoint(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/firewall/one_to_one/savepoint"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// OneToOneSet calls POST /api/firewall/one_to_one/set
func (c *Client) OneToOneSet(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/firewall/one_to_one/set"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// SourceNatAddRule calls POST /api/firewall/source_nat/addRule
func (c *Client) SourceNatAddRule(ctx context.Context, body *Rule) (*opnsense.GenericResponse, error) {
	path := "/api/firewall/source_nat/addRule"
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"rule": body}, &resp)
	return &resp, err
}

// SourceNatDelRule calls POST /api/firewall/source_nat/delRule
// Parameters:
//   - uuid
func (c *Client) SourceNatDelRule(ctx context.Context, uuid string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/firewall/source_nat/delRule/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// SourceNatGetRule calls GET /api/firewall/source_nat/getRule
// Parameters:
//   - uuid (optional, default: null)
func (c *Client) SourceNatGetRule(ctx context.Context, opts ...string) (*Rule, error) {
	path := "/api/firewall/source_nat/getRule"
	for _, o := range opts {
		path += "/" + o
	}
	var resp ruleGetItemResponse
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return &resp.Rule, err
}

// SourceNatMoveRuleBefore calls GET /api/firewall/source_nat/moveRuleBefore
// Parameters:
//   - selected_uuid
//   - target_uuid
func (c *Client) SourceNatMoveRuleBefore(ctx context.Context, selected_uuid string, target_uuid string) (map[string]any, error) {
	path := fmt.Sprintf("/api/firewall/source_nat/moveRuleBefore/%s/%s", selected_uuid, target_uuid)
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// SourceNatSearchRule calls GET,POST /api/firewall/source_nat/searchRule
func (c *Client) SourceNatSearchRule(ctx context.Context, body any) (*opnsense.SearchResult[Rule], error) {
	path := "/api/firewall/source_nat/searchRule"
	var resp opnsense.SearchResult[Rule]
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return &resp, err
}

// SourceNatSetRule calls POST /api/firewall/source_nat/setRule
// Parameters:
//   - uuid
func (c *Client) SourceNatSetRule(ctx context.Context, uuid string, body *Rule) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/firewall/source_nat/setRule/%s", uuid)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, map[string]any{"rule": body}, &resp)
	return &resp, err
}

// SourceNatToggleRule calls POST /api/firewall/source_nat/toggleRule
// Parameters:
//   - uuid
//   - enabled (optional, default: null)
func (c *Client) SourceNatToggleRule(ctx context.Context, uuid string, opts ...string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/firewall/source_nat/toggleRule/%s", uuid)
	for _, o := range opts {
		path += "/" + o
	}
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// SourceNatToggleRuleLog calls GET /api/firewall/source_nat/toggleRuleLog
// Parameters:
//   - uuid
//   - log
func (c *Client) SourceNatToggleRuleLog(ctx context.Context, uuid string, log string) (*opnsense.GenericResponse, error) {
	path := fmt.Sprintf("/api/firewall/source_nat/toggleRuleLog/%s/%s", uuid, log)
	var resp opnsense.GenericResponse
	err := c.client.Do(ctx, "POST", path, nil, &resp)
	return &resp, err
}

// SourceNatApply calls POST /api/firewall/source_nat/apply
// Parameters:
//   - rollback_revision (optional, default: null)
func (c *Client) SourceNatApply(ctx context.Context, body any, opts ...string) (map[string]any, error) {
	path := "/api/firewall/source_nat/apply"
	for _, o := range opts {
		path += "/" + o
	}
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// SourceNatCancelRollback calls POST /api/firewall/source_nat/cancelRollback
// Parameters:
//   - rollback_revision
func (c *Client) SourceNatCancelRollback(ctx context.Context, rollback_revision string, body any) (map[string]any, error) {
	path := fmt.Sprintf("/api/firewall/source_nat/cancelRollback/%s", rollback_revision)
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// SourceNatGet calls GET /api/firewall/source_nat/get
func (c *Client) SourceNatGet(ctx context.Context) (map[string]any, error) {
	path := "/api/firewall/source_nat/get"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// SourceNatListCategories calls GET /api/firewall/source_nat/listCategories
func (c *Client) SourceNatListCategories(ctx context.Context) (map[string]any, error) {
	path := "/api/firewall/source_nat/listCategories"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// SourceNatListNetworkSelectOptions calls GET /api/firewall/source_nat/listNetworkSelectOptions
func (c *Client) SourceNatListNetworkSelectOptions(ctx context.Context) (map[string]any, error) {
	path := "/api/firewall/source_nat/listNetworkSelectOptions"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// SourceNatListPortSelectOptions calls GET /api/firewall/source_nat/listPortSelectOptions
func (c *Client) SourceNatListPortSelectOptions(ctx context.Context) (map[string]any, error) {
	path := "/api/firewall/source_nat/listPortSelectOptions"
	var resp map[string]any
	err := c.client.Do(ctx, "GET", path, nil, &resp)
	return resp, err
}

// SourceNatRevert calls POST /api/firewall/source_nat/revert
// Parameters:
//   - revision
func (c *Client) SourceNatRevert(ctx context.Context, revision string, body any) (map[string]any, error) {
	path := fmt.Sprintf("/api/firewall/source_nat/revert/%s", revision)
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// SourceNatSavepoint calls POST /api/firewall/source_nat/savepoint
func (c *Client) SourceNatSavepoint(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/firewall/source_nat/savepoint"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}

// SourceNatSet calls POST /api/firewall/source_nat/set
func (c *Client) SourceNatSet(ctx context.Context, body any) (map[string]any, error) {
	path := "/api/firewall/source_nat/set"
	var resp map[string]any
	err := c.client.Do(ctx, "POST", path, body, &resp)
	return resp, err
}
