// Code generated by opnsense-cli/generate; DO NOT EDIT.

package postfix

import "github.com/jontk/opnsense-cli/opnsense"

// Address represents a address model item.
type Address struct {
	Enabled opnsense.OPNBool `json:"enabled"`
	From    string           `json:"from"`
	To      string           `json:"to"`
}

// Settings represents a settings model item.
type Settings struct {
	EnableRspamd  opnsense.OPNBool `json:"enable_rspamd"`
	DefaultAction string           `json:"default_action"` // Valid values: accept, tempfail
}

// Domain represents a domain model item.
type Domain struct {
	Enabled     opnsense.OPNBool `json:"enabled"`
	Domainname  string           `json:"domainname"`
	Destination string           `json:"destination,omitempty"`
}

// Headercheck represents a headercheck model item.
type Headercheck struct {
	Enabled    opnsense.OPNBool `json:"enabled"`
	Expression string           `json:"expression"`
	Filter     string           `json:"filter"` // Valid values: WHILE_DELIVERING, WHILE_RECEIVING
}

// Recipient represents a recipient model item.
type Recipient struct {
	Enabled opnsense.OPNBool `json:"enabled"`
	Address string           `json:"address"`
	Action  string           `json:"action"` // Valid values: OK, REJECT
}

// Recipientbcc represents a recipientbcc model item.
type Recipientbcc struct {
	Enabled opnsense.OPNBool `json:"enabled"`
	From    string           `json:"from"`
	To      string           `json:"to"`
}

// Sender represents a sender model item.
type Sender struct {
	Enabled opnsense.OPNBool `json:"enabled"`
	Address string           `json:"address"`
	Action  string           `json:"action"` // Valid values: OK, REJECT
}

// Senderbcc represents a senderbcc model item.
type Senderbcc struct {
	Enabled opnsense.OPNBool `json:"enabled"`
	From    string           `json:"from"`
	To      string           `json:"to"`
}

// Sendercanonical represents a sendercanonical model item.
type Sendercanonical struct {
	Enabled opnsense.OPNBool `json:"enabled"`
	From    string           `json:"from"`
	To      string           `json:"to"`
}

type addressGetItemResponse struct {
	Address Address `json:"address"`
}

type domainGetItemResponse struct {
	Domain Domain `json:"domain"`
}

type headercheckGetItemResponse struct {
	Headercheck Headercheck `json:"headercheck"`
}

type recipientGetItemResponse struct {
	Recipient Recipient `json:"recipient"`
}

type recipientbccGetItemResponse struct {
	Recipientbcc Recipientbcc `json:"recipientbcc"`
}

type senderGetItemResponse struct {
	Sender Sender `json:"sender"`
}

type senderbccGetItemResponse struct {
	Senderbcc Senderbcc `json:"senderbcc"`
}

type sendercanonicalGetItemResponse struct {
	Sendercanonical Sendercanonical `json:"sendercanonical"`
}
