// Code generated by opnsense-cli/generate; DO NOT EDIT.

package beats

// Settings represents a settings model item.
type Settings struct {
	Enabled string `json:"enabled"`
}

// Modules represents a modules model item.
type Modules struct {
	Enabled string `json:"enabled,omitempty"` // Valid values: suricata
}

// Inputs represents a inputs model item.
type Inputs struct {
	Enabled string `json:"enabled,omitempty"` // Valid values: audit, configd, boot, system, lighttpd
}

// Elasticsearch represents a elasticsearch model item.
type Elasticsearch struct {
	Hosts  string `json:"hosts"`
	ApiKey string `json:"api_key"`
}
