// Code generated by opnsense-cli/generate; DO NOT EDIT.

package kea

import "github.com/jontk/opnsense-cli/opnsense"

// General represents a general model item.
type General struct {
	Enabled  opnsense.OPNBool `json:"enabled"`
	HttpHost string           `json:"http_host"`
	HttpPort string           `json:"http_port"`
}

// Lexpire represents a lexpire model item.
type Lexpire struct {
	HoldReclaimedTime           *opnsense.OPNInt `json:"hold_reclaimed_time,omitempty"`
	ReclaimTimerWaitTime        *opnsense.OPNInt `json:"reclaim_timer_wait_time,omitempty"`
	FlushReclaimedTimerWaitTime *opnsense.OPNInt `json:"flush_reclaimed_timer_wait_time,omitempty"`
	MaxReclaimTime              *opnsense.OPNInt `json:"max_reclaim_time,omitempty"`
	MaxReclaimLeases            *opnsense.OPNInt `json:"max_reclaim_leases,omitempty"`
	UnwarnedReclaimCycles       *opnsense.OPNInt `json:"unwarned_reclaim_cycles,omitempty"`
}

// Ha represents a ha model item.
type Ha struct {
	Enabled           opnsense.OPNBool `json:"enabled"`
	ThisServerName    string           `json:"this_server_name,omitempty"`
	MaxUnackedClients opnsense.OPNInt  `json:"max_unacked_clients"`
}

// Subnet4 represents a subnet4 model item.
type Subnet4 struct {
	Subnet                string           `json:"subnet"`
	NextServer            string           `json:"next_server,omitempty"`
	OptionDataAutocollect opnsense.OPNBool `json:"option_data_autocollect"`
	MatchClientId         opnsense.OPNBool `json:"match-client-id"`
	Pools                 string           `json:"pools,omitempty"`
	Description           string           `json:"description,omitempty"`
}

// Reservation represents a reservation model item.
type Reservation struct {
	Subnet      string `json:"subnet"`
	IpAddress   string `json:"ip_address,omitempty"`
	HwAddress   string `json:"hw_address"`
	Hostname    string `json:"hostname,omitempty"`
	Description string `json:"description,omitempty"`
}

// Peer represents a peer model item.
type Peer struct {
	Name string `json:"name"`
	Role string `json:"role"` // Valid values: primary, standby
	Url  string `json:"url"`
}

// Subnet6 represents a subnet6 model item.
type Subnet6 struct {
	Subnet      string `json:"subnet"`
	Allocator   string `json:"allocator,omitempty"`    // Valid values: iterative, random
	PdAllocator string `json:"pd-allocator,omitempty"` // Valid values: iterative, random, flq
	Pools       string `json:"pools,omitempty"`
	Interface   string `json:"interface"`
	Description string `json:"description,omitempty"`
}

// PdPool represents a pd_pool model item.
type PdPool struct {
	Subnet       string          `json:"subnet"`
	Prefix       string          `json:"prefix,omitempty"`
	PrefixLen    opnsense.OPNInt `json:"prefix_len"`
	DelegatedLen opnsense.OPNInt `json:"delegated_len"`
	Description  string          `json:"description,omitempty"`
}

type peerGetItemResponse struct {
	Peer Peer `json:"peer"`
}

type reservationGetItemResponse struct {
	Reservation Reservation `json:"reservation"`
}

type subnet4GetItemResponse struct {
	Subnet4 Subnet4 `json:"subnet4"`
}

type pd_poolGetItemResponse struct {
	PdPool PdPool `json:"pd_pool"`
}

type subnet6GetItemResponse struct {
	Subnet6 Subnet6 `json:"subnet6"`
}
