// Code generated by opnsense-cli/generate; DO NOT EDIT.

package siproxd

import "github.com/jontk/opnsense-cli/opnsense"

// Domain represents a domain model item.
type Domain struct {
	Enabled opnsense.OPNBool `json:"enabled"` // Required. Default: 1.
	Name    string           `json:"name"`    // Required.
	Host    string           `json:"host"`    // Required.
	Port    opnsense.OPNInt  `json:"port"`    // Required. Default: 5060.
}

// User represents a user model item.
type User struct {
	Enabled  opnsense.OPNBool `json:"enabled"`  // Required. Default: 1.
	Username string           `json:"username"` // Required.
	Password string           `json:"password"` // Required.
}

type domainGetItemResponse struct {
	Domain Domain `json:"domain"`
}

type userGetItemResponse struct {
	User User `json:"user"`
}
